### ISSUE TITLE
`runtime error: invalid memory address or nil pointer dereference`. when a step has both output parameters and exit hook

### ISSUE THREAD

**Issue by Hakuyume** [argoproj/argo-workflows#10049]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

happened:

The argo controller raises `runtime error: invalid memory address or nil pointer dereference`.

Situation:
- The workflow consists of two steps (A and B).
- A outputs a parameter (a-out)
- B outputs a parameter (b-out)
- B has an exit hook and it uses a-out.
- A succeeds and B fails

expected:

The controller runs B's exit hook and marks the entire workflow as Failed since B's exit hook does not depends on B's output.

If I understand correctly, this line causes the error. The controller always tries to resolve outputs of steps even if exit hooks do not require these parameters.
https://github.com/argoproj/argo-workflows/blob/v3.4.3/workflow/controller/exit_handler.go#L60

### Version

3.4.3

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: with-exit
  templates:
  - name: with-exit
    steps:
    - - name: echo
        template: echo
        arguments:
          parameters:
          - name: src
            value: hello world
    - - name: error
        template: error
        hooks:
          exit:
            template: echo
            arguments:
              parameters:
              - name: param0
                value: '{{steps.echo.outputs.parameters.dest}}'
  - name: echo
    inputs:
      parameters:
      - name: src
    outputs:
      parameters:
      - name: dest
        valueFrom:
          path: /output
    script:
      image: alpine
      command:
      - sh
      source: 'echo {{inputs.parameters.src}} | tee /output'
  - name: error
    outputs:
      parameters:
      - name: dest
        valueFrom:
          path: /output
    script:
      image: alpine
      command:
      - 'false'
```

### Logs from the workflow controller

```
time="2022-11-17T04:45:46.670Z" level=info msg="Processing workflow" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.671Z" level=info msg="Updated phase  -> Running" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.672Z" level=info msg="Steps node workflow-nwxbq initialized Running" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.672Z" level=info msg="StepGroup node workflow-nwxbq-2522224485 initialized Running" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.672Z" level=info msg="Pod node workflow-nwxbq-3427287056 initialized Pending" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.678Z" level=info msg="Created pod: workflow-nwxbq[0].echo (workflow-nwxbq-echo-3427287056)" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.678Z" level=info msg="Workflow step group node workflow-nwxbq-2522224485 not yet completed" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.678Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.678Z" level=info msg=reconcileAgentPod namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:46.682Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=4431 workflow=workflow-nwxbq
time="2022-11-17T04:45:56.679Z" level=info msg="Processing workflow" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:56.680Z" level=info msg="Task-result reconciliation" namespace=default numObjs=1 workflow=workflow-nwxbq
time="2022-11-17T04:45:56.680Z" level=info msg="task-result changed" namespace=default nodeID=workflow-nwxbq-3427287056 workflow=workflow-nwxbq
time="2022-11-17T04:45:56.680Z" level=info msg="node changed" namespace=default new.message= new.phase=Running new.progress=0/1 nodeID=workflow-nwxbq-3427287056 old.message= old.phase=Pending old.progress=0/1 workflow=workflow-nwxbq
time="2022-11-17T04:45:56.681Z" level=info msg="Workflow step group node workflow-nwxbq-2522224485 not yet completed" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:56.681Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:56.681Z" level=info msg=reconcileAgentPod namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:45:56.685Z" level=info msg="cleaning up pod" action=terminateContainers key=default/workflow-nwxbq-echo-3427287056/terminateContainers
time="2022-11-17T04:45:56.697Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=4467 workflow=workflow-nwxbq
time="2022-11-17T04:46:06.699Z" level=info msg="Processing workflow" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.699Z" level=info msg="Task-result reconciliation" namespace=default numObjs=1 workflow=workflow-nwxbq
time="2022-11-17T04:46:06.699Z" level=info msg="node changed" namespace=default new.message= new.phase=Succeeded new.progress=0/1 nodeID=workflow-nwxbq-3427287056 old.message= old.phase=Running old.progress=0/1 workflow=workflow-nwxbq
time="2022-11-17T04:46:06.700Z" level=info msg="Step group node workflow-nwxbq-2522224485 successful" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.700Z" level=info msg="node workflow-nwxbq-2522224485 phase Running -> Succeeded" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.700Z" level=info msg="node workflow-nwxbq-2522224485 finished: 2022-11-17 04:46:06.700652193 +0000 UTC" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.700Z" level=info msg="StepGroup node workflow-nwxbq-1381596656 initialized Running" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.700Z" level=info msg="SG Outbound nodes of workflow-nwxbq-3427287056 are [workflow-nwxbq-3427287056]" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.701Z" level=info msg="Pod node workflow-nwxbq-439498460 initialized Pending" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.701Z" level=warning msg="'script.source' is empty, suggest change template into 'container'" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.712Z" level=info msg="Created pod: workflow-nwxbq[1].error (workflow-nwxbq-error-439498460)" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.712Z" level=info msg="Workflow step group node workflow-nwxbq-1381596656 not yet completed" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.712Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.712Z" level=info msg=reconcileAgentPod namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:06.719Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=4486 workflow=workflow-nwxbq
time="2022-11-17T04:46:06.724Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/workflow-nwxbq-echo-3427287056/labelPodCompleted
time="2022-11-17T04:46:16.715Z" level=info msg="Processing workflow" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:16.715Z" level=info msg="Task-result reconciliation" namespace=default numObjs=2 workflow=workflow-nwxbq
time="2022-11-17T04:46:16.715Z" level=info msg="task-result changed" namespace=default nodeID=workflow-nwxbq-439498460 workflow=workflow-nwxbq
time="2022-11-17T04:46:16.716Z" level=info msg="node changed" namespace=default new.message= new.phase=Running new.progress=0/1 nodeID=workflow-nwxbq-439498460 old.message= old.phase=Pending old.progress=0/1 workflow=workflow-nwxbq
time="2022-11-17T04:46:16.716Z" level=info msg="SG Outbound nodes of workflow-nwxbq-3427287056 are [workflow-nwxbq-3427287056]" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:16.717Z" level=info msg="Workflow step group node workflow-nwxbq-1381596656 not yet completed" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:16.717Z" level=info msg="TaskSet Reconciliation" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:16.717Z" level=info msg=reconcileAgentPod namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:16.722Z" level=info msg="cleaning up pod" action=terminateContainers key=default/workflow-nwxbq-error-439498460/terminateContainers
time="2022-11-17T04:46:16.730Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=4524 workflow=workflow-nwxbq
time="2022-11-17T04:46:26.687Z" level=info msg="cleaning up pod" action=killContainers key=default/workflow-nwxbq-echo-3427287056/killContainers
time="2022-11-17T04:46:26.732Z" level=info msg="Processing workflow" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.732Z" level=info msg="Task-result reconciliation" namespace=default numObjs=2 workflow=workflow-nwxbq
time="2022-11-17T04:46:26.733Z" level=info msg="node changed" namespace=default new.message="Error (exit code 1)" new.phase=Failed new.progress=0/1 nodeID=workflow-nwxbq-439498460 old.message= old.phase=Running old.progress=0/1 workflow=workflow-nwxbq
time="2022-11-17T04:46:26.733Z" level=info msg="SG Outbound nodes of workflow-nwxbq-3427287056 are [workflow-nwxbq-3427287056]" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.734Z" level=info msg="Running OnExit handler" lifeCycleHook="&LifecycleHook{Template:echo,Arguments:Arguments{Parameters:[]Parameter{Parameter{Name:param0,Default:nil,Value:*hello world,ValueFrom:nil,GlobalName:,Enum:[],Description:nil,},},Artifacts:[]Artifact{},},TemplateRef:nil,Expression:,}" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.734Z" level=error msg="Recovered from panic" namespace=default r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 230 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:192 +0xbc\npanic({0x1e6ca40, 0x34cd4a0})\n\t/usr/local/go/src/runtime/panic.go:844 +0x258\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).resolveExitTmplArgument(0xc00032ba20, {{0xc001073c20, 0x1, 0x1}, {0x0, 0x0, 0x0}}, {0xc000b92540, 0xb}, 0xc000672200, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/exit_handler.go:60 +0xc72\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).runOnExitNode(0xc00032ba20, {0x24cfb20, 0xc000056018}, 0xc001073bc0, 0xc000d9e348, {0xc00072cb60, 0xe}, 0xe?, {0xc000b92540, 0xb}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/exit_handler.go:37 +0x4bc\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc00032ba20, {0x24cfb20, 0xc000056018}, {0xc000767500, 0x1, 0x4}, {0xc00053d500, 0x11}, 0xc000d9e7c0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:285 +0x180c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc00032ba20, {0x24cfb20, 0xc000056018}, {0xc00097ea20, 0xe}, 0xc000672500, {0xc00053d410, 0x14}, 0xc000c1a000, {0x24d28e0, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:95 +0xcc5\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc00032ba20, {0x24cfb20, 0xc000056018}, {0xc00097ea20, 0xe}, {0x24d28e0, 0xc000764b40?}, 0xc000181e80?, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1950 +0x258c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00032ba20, {0x24cfb20, 0xc000056018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:346 +0x16ed\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000044d80, {0x24cfb20, 0xc000056018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:762 +0x759\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc000a29ea0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:684 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x24ade20, 0xc00085d440}, 0x1, 0xc000640600)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:317 +0x19c5\n" workflow=workflow-nwxbq
time="2022-11-17T04:46:26.735Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.735Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.735Z" level=info msg="Marking workflow completed" namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.735Z" level=info msg="Checking daemoned children of " namespace=default workflow=workflow-nwxbq
time="2022-11-17T04:46:26.741Z" level=info msg="cleaning up pod" action=deletePod key=default/workflow-nwxbq-1340600742-agent/deletePod
time="2022-11-17T04:46:26.744Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=4542 workflow=workflow-nwxbq
time="2022-11-17T04:46:26.758Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/workflow-nwxbq-error-439498460/labelPodCompleted
time="2022-11-17T04:46:46.723Z" level=info msg="cleaning up pod" action=killContainers key=default/workflow-nwxbq-error-439498460/killContainers
```

### Logs from in your workflow's wait container

```
time="2022-11-17T04:45:54.566Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2022-11-17T04:45:54.566Z" level=info msg="Saving output parameters"
time="2022-11-17T04:45:54.566Z" level=info msg="Saving path output parameter: dest"
time="2022-11-17T04:45:54.566Z" level=info msg="Copying /output from base image layer"
time="2022-11-17T04:45:54.567Z" level=info msg="Successfully saved output parameter: dest"
time="2022-11-17T04:45:54.567Z" level=info msg="No output artifacts"
time="2022-11-17T04:45:54.587Z" level=info msg="Create workflowtaskresults 201"
time="2022-11-17T04:45:54.589Z" level=info msg="Deadline monitor stopped"
time="2022-11-17T04:45:54.589Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-11-17T04:45:54.590Z" level=info msg="Alloc=7155 TotalAlloc=12550 Sys=19410 NumGC=4 Goroutines=8"
time="2022-11-17T04:46:14.721Z" level=info msg="Saving output parameters"
time="2022-11-17T04:46:14.721Z" level=info msg="Saving path output parameter: dest"
time="2022-11-17T04:46:14.721Z" level=info msg="Copying /output from base image layer"
time="2022-11-17T04:46:14.721Z" level=error msg="executor error: open /var/run/argo/outputs/parameters/output: no such file or directory"
time="2022-11-17T04:46:14.721Z" level=info msg="No output artifacts"
time="2022-11-17T04:46:14.733Z" level=info msg="Create workflowtaskresults 201"
time="2022-11-17T04:46:14.734Z" level=info msg="Deadline monitor stopped"
time="2022-11-17T04:46:14.734Z" level=info msg="stopping progress monitor (context done)" error="context canceled"
time="2022-11-17T04:46:14.734Z" level=info msg="Alloc=6692 TotalAlloc=12514 Sys=19410 NumGC=4 Goroutines=6"
time="2022-11-17T04:46:14.735Z" level=fatal msg="open /var/run/argo/outputs/parameters/output: no such file or directory"
```

**Comment by realLyans** [comment]
Up this - we are hitting a similar bug in production (which unfortunately I cannot share the code) but when I remove output from the called template, the workflow seems to run normally.
Using version 3.3.8

**Comment by realLyans** [comment]
@sarabala1979 are you intended to work on this one? If not I might start looking into it.

**Comment by tooptoop4** [comment]
@Hakuyume can u try latest 3.5 release? this looks like a dupe of https://github.com/argoproj/argo-workflows/issues/13445 which was fixed

**Comment by Hakuyume** [comment]
> @Hakuyume can u try latest 3.5 release? this looks like a dupe of https://github.com/argoproj/argo-workflows/issues/13445 which was fixed

Thank you. It seems fixed :tada: 

I tried with the following manifest (slightly different from one above).
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-
spec:
  entrypoint: with-exit
  templates:
  - name: with-exit
    steps:
    - - name: echo
        template: echo
        arguments:
          parameters:
          - name: src
            value: hello world
    - - name: error
        template: error
        hooks:
          exit:
            template: echo
            arguments:
              parameters:
              - name: src
                value: '{{steps.echo.outputs.parameters.dest}}'
  - name: echo
    inputs:
      parameters:
      - name: src
    outputs:
      parameters:
      - name: dest
        valueFrom:
          path: /output
    script:
      image: alpine
      command:
      - sh
      source: 'echo {{inputs.parameters.src}} | tee /output'
  - name: error
    outputs:
      parameters:
      - name: dest
        valueFrom:
          path: /output
    script:
      image: alpine
      command:
      - 'false'
```

with argo 3.4.3
```console
$ argo --context=kind-argo-3.4.3 --namespace=argo get @latest
Name:                workflow-2z2lc
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Error
Message:             runtime error: invalid memory address or nil pointer dereference
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Nov 13 16:11:34 +0900 (1 minute ago)
Started:             Wed Nov 13 16:11:34 +0900 (1 minute ago)
Finished:            Wed Nov 13 16:11:54 +0900 (50 seconds ago)
Duration:            20 seconds
Progress:            1/2
ResourcesDuration:   8s*(1 cpu),8s*(100Mi memory)

STEP               TEMPLATE   PODNAME                          DURATION  MESSAGE
 ⚠ workflow-2z2lc  with-exit                                             Workflow operation error  
 ├───✔ echo        echo       workflow-2z2lc-echo-27284571     6s                                  
 └───✖ error       error      workflow-2z2lc-error-1803454181  5s        Error (exit code 1)       
 ```

with argo 3.5.12
```console
$ argo --context=kind-argo-3.5.12 --namespace=argo get @latest
Name:                workflow-qh5bj
Namespace:           argo
ServiceAccount:      unset (will run with the default ServiceAccount)
Status:              Failed
Message:             child 'workflow-qh5bj-2124204668' failed
Conditions:          
 PodRunning          False
 Completed           True
Created:             Wed Nov 13 16:11:41 +0900 (1 minute ago)
Started:             Wed Nov 13 16:11:41 +0900 (1 minute ago)
Finished:            Wed Nov 13 16:12:11 +0900 (42 seconds ago)
Duration:            30 seconds
Progress:            2/3
ResourcesDuration:   0s*(1 cpu),14s*(100Mi memory)

STEP               TEMPLATE   PODNAME                          DURATION  MESSAGE
 ✖ workflow-qh5bj  with-exit                                             child 'workflow-qh5bj-2124204668' failed  
 ├───✔ echo        echo       workflow-qh5bj-echo-4273829552   5s                                                  
 ├───✖ error       error      workflow-qh5bj-error-2124204668  5s        Error (exit code 1)                       
 └─✔ error.onExit  echo       workflow-qh5bj-echo-1199161007   5s  
 ```
