### ISSUE TITLE
"invalid memory address or nil pointer dereference" with archive retry command

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#10536]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

command:
```
argo-linux-amd64 archive retry 581b0a15-21d2-4913-8f02-46a8ddb6d034 -n auth --restart-successful --node-field-selector 'templateName=redactstepname' --argo-server redact:2746
```

```
time="2023-02-16T01:34:28.307Z" level=info msg="Processing workflow" namespace=auth workflow=redact
time="2023-02-16T01:34:28.325Z" level=info msg="Task-result reconciliation" namespace=auth numObjs=0 workflow=redact
time="2023-02-16T01:34:28.330Z" level=info msg="Retry node redact initialized Running" namespace=auth workflow=redact
time="2023-02-16T01:34:28.335Z" level=error msg="Recovered from panic" namespace=auth r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 267 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:192 +0xbc\npanic({0x1e6c9e0, 0x34cd500})\n\t/usr/local/go/src/runtime/panic.go:844 +0x258\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc000582630, 0xc001617960, {0xc002a59bb0, 0xf}, 0x1?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2772 +0xa3\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc000582630, {0x24cfe00, 0xc00019a000}, {0xc002f97f40, 0x33}, 0xc001c0bd40, {0xc001e82d00, 0x36}, 0xc000aba900, {0x24d2bc0, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:142 +0x1319\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000582630, {0x24cfe00, 0xc00019a000}, {0xc0026f7530, 0x30}, {0x24d2bc0, 0xc0012bcb40?}, 0x0?, {{0xc0008e2f60, 0x1, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1958 +0x258c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000582630, {0x24cfe00, 0xc00019a000})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:346 +0x16ed\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00059e900, {0x24cfe00, 0xc00019a000})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:762 +0x759\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc000a856a0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:684 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005531c0?, {0x24ae100, 0xc000d31c20}, 0x1, 0xc00005d080)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a857b0?, 0x3b9aca00, 0x0, 0x0?, 0xc0005538e0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x9338ea?, 0xc0004b6a80?, 0xc0004b69c0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:317 +0x19c5\n" workflow=redact
time="2023-02-16T01:34:28.335Z" level=info msg="Updated phase Running -> Error" namespace=auth workflow=redact
time="2023-02-16T01:34:28.335Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=auth workflow=redact
time="2023-02-16T01:34:28.335Z" level=info msg="Marking workflow completed" namespace=auth workflow=redact
time="2023-02-16T01:34:28.335Z" level=info msg="Marking workflow as pending archiving" namespace=auth workflow=redact
time="2023-02-16T01:34:28.336Z" level=info msg="Checking daemoned children of " namespace=auth workflow=redact
time="2023-02-16T01:34:28.336Z" level=info msg="Workflow to be dehydrated" Workflow Size=39183
time="2023-02-16T01:34:28.343Z" level=info msg="cleaning up pod" action=deletePod key=auth/redact-1340600742-agent/deletePod
time="2023-02-16T01:34:28.350Z" level=info msg="Create events 201"
time="2023-02-16T01:34:28.350Z" level=info msg="Delete pods 404"
time="2023-02-16T01:34:28.362Z" level=info msg="Update workflows 200"
time="2023-02-16T01:34:28.366Z" level=info msg="Workflow update successful" namespace=auth phase=Error resourceVersion=10216505 workflow=redact
time="2023-02-16T01:34:28.378Z" level=info msg="Create events 201"
time="2023-02-16T01:34:28.379Z" level=info msg="DeleteCollection workflowtaskresults 200"
time="2023-02-16T01:34:28.383Z" level=info msg="archiving workflow" namespace=auth uid=866994de-409c-487f-be39-dd5fa68eb5ab workflow=redact
time="2023-02-16T01:34:28.383Z" level=info msg="Create events 201"
time="2023-02-16T01:34:28.468Z" level=info msg="Patch workflows 200"
```

if i omit --node-field-selector 'templateName=redactstepname'  then i don't get this issue

### Version

3.4.4

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

**Comment by tooptoop4** [comment]
crunchy

**Comment by Joibel** [comment]
Both nil dereferences reported here are fixed on `main` and on supported releases.
