### ISSUE TITLE
`digital envelope routines::unsupported` issue with 3.4.9 release build

### ISSUE THREAD

**Issue by chenrui333** [argoproj/argo-workflows#11404]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

```
node:internal/crypto/hash:69
    this[kHandle] = new _Hash(algorithm, xofLen);
                    ^
  
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:69:19)
      at Object.createHash (node:crypto:138:10)
      at module.exports (/private/tmp/argo-20230720-48[394](https://github.com/Homebrew/homebrew-core/actions/runs/5612007335/jobs/10269330959?pr=137118#step:3:395)-1xggx70/ui/node_modules/webpack/lib/util/createHash.js:135:53)
      at NormalModule._initBuildHash (/private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/webpack/lib/NormalModule.js:417:16)
      at handleParseError (/private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/webpack/lib/NormalModule.js:471:10)
      at /private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/webpack/lib/NormalModule.js:503:5
      at /private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/webpack/lib/NormalModule.js:358:12
      at /private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
      at iterateNormalLoaders (/private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
      at Array.<anonymous> (/private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
      at Storage.finished (/private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
      at /private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
      at /private/tmp/argo-20230720-48394-1xggx70/ui/node_modules/graceful-fs/graceful-fs.js:123:16
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }
  
  Node.js v20.4.0
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  make: *** [ui/dist/app/index.html] Error 1
```

relates to https://github.com/Homebrew/homebrew-core/pull/137118

### Version

3.4.9

**Comment by JPZ13** [comment]
From @terrytangyuan 
> Can you try again now that all release artifacts are uploaded?
cc @chenrui333

**Comment by chenrui333** [comment]
let me give it another try, it is less about brew formula, more about the nodejs script refs.

**Comment by chenrui333** [comment]
> I am not familiar with how Argo's brew formula is set up but perhaps wait to try again once the release and image is created? Note that this workflow is still running. https://github.com/argoproj/argo-workflows/actions/runs/5611926849/jobs/10270813989

This is the issue with building node 18+

**Comment by chenrui333** [comment]
any plan to build with newer version of nodejs? (node v16 is gonna to be EOL on 11 Sep 2023)
