### ISSUE TITLE
nil pointer error in Controller during exit handler step

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#11572]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

this wf is submitted by an argoevents sqs sensor, i have had 10000s of successful runs before, first time getting error like below. the error is on the exithandler step, note that no templates/hooks are referenced by this workflow

```
level=error msg=\"Recovered from panic\" namespace=auth r=\"runtime error: invalid memory address or nil pointer dereference\" stack=\"goroutine 281 [running]:\
runtime/debug.Stack()\
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:193 +0xbc\
panic({0x1f4b760, 0x3602b60})\
	/usr/local/go/src/runtime/panic.go:890 +0x263\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc004cae6e0, 0xc004f06a60, {0xc002a9d950, 0x11}, 0x1?)\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2812 +0xa3\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc004cae6e0, {0x25a0b48, 0xc000128010}, {0xc006faa9c0, 0x3a}, 0xc002e59b40, {0xc004e25480, 0x36}, 0xc003cb18c0, {0x25a42b8, ...}, ...)\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:142 +0x1328\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc004cae6e0, {0x25a0b48, 0xc000128010}, {0xc004e25340, 0x37}, {0x25a42b8, 0xc00342b2c0?}, 0xc0028f3e70?, {{0xc00770b500, 0x1, ...}, ...}, ...)\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1998 +0x220f\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc004cae6e0, {0x25a0b48, 0xc000128010})\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:426 +0x2d79\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000628000, {0x25a0b48, 0xc000128010})\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:768 +0x759\
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0017ec6a0?)\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:690 +0x9e\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7273656c69662f67?, {0x257ea00, 0xc001773800}, 0x1, 0xc00065a540)\
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2045632d20706572?, 0x3b9aca00, 0x0, 0x69?, 0x5d20302074672d20?)\
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\
k8s.io/apimachinery/pkg/util/wait.Until(0x6365282422205b20?, 0x7033732422206f68?, 0x7c20227869666572?)\
	/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:317 +0x1a45\
```

### Version

3.4.8

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

```text
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

{"time":"2023-08-14T06:42:47.292405957Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=info msg=\"StepGroup node mywf-20230811t111346701z4w2sp-1977054014 initialized Running\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.292656212Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=info msg=\"Step group node mywf-20230811t111346701z4w2sp-1977054014 successful\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.292667392Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=info msg=\"node mywf-20230811t111346701z4w2sp-1977054014 phase Running -> Succeeded\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.292722293Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=info msg=\"node mywf-20230811t111346701z4w2sp-1977054014 finished: 2023-08-14 06:42:47.292622971 +0000 UTC\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.293020399Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=error msg=\"Recovered from panic\" namespace=auth r=\"runtime error: invalid memory address or nil pointer dereference\" stack=\"goroutine 281 [running]:\\nruntime/debug.Stack()\\n\\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:193 +0xbc\\npanic({0x1f4b760, 0x3602b60})\\n\\t/usr/local/go/src/runtime/panic.go:890 +0x263\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc004cae6e0, 0xc004f06a60, {0xc002a9d950, 0x11}, 0x1?)\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2812 +0xa3\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc004cae6e0, {0x25a0b48, 0xc000128010}, {0xc006faa9c0, 0x3a}, 0xc002e59b40, {0xc004e25480, 0x36}, 0xc003cb18c0, {0x25a42b8, ...}, ...)\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:142 +0x1328\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc004cae6e0, {0x25a0b48, 0xc000128010}, {0xc004e25340, 0x37}, {0x25a42b8, 0xc00342b2c0?}, 0xc0028f3e70?, {{0xc00770b500, 0x1, ...}, ...}, ...)\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1998 +0x220f\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc004cae6e0, {0x25a0b48, 0xc000128010})\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:426 +0x2d79\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000628000, {0x25a0b48, 0xc000128010})\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:768 +0x759\\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0017ec6a0?)\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:690 +0x9e\\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\\n\\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7273656c69662f67?, {0x257ea00, 0xc001773800}, 0x1, 0xc00065a540)\\n\\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x2045632d20706572?, 0x3b9aca00, 0x0, 0x69?, 0x5d20302074672d20?)\\n\\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\\nk8s.io/apimachinery/pkg/util/wait.Until(0x6365282422205b20?, 0x7033732422206f68?, 0x7c20227869666572?)\\n\\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\\n\\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:317 +0x1a45\\n\" workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.29304949Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.292Z\" level=info msg=\"Updated phase Running -> Error\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.293120101Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.293Z\" level=info msg=\"Updated message  -> runtime error: invalid memory address or nil pointer dereference\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.293130121Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.293Z\" level=info msg=\"Marking workflow completed\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
{"time":"2023-08-14T06:42:47.293134881Z","stream":"stderr","_p":"F","log":"time=\"2023-08-14T06:42:47.293Z\" level=info msg=\"Marking workflow as pending archiving\" namespace=auth workflow=mywf-20230811t111346701z4w2sp
```

### Logs from in your workflow's wait container

```text
kubectl logs -n argo -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

n/a
```

**Comment by guruprasathTT** [comment]
Hi, Thanks for raising this issue.

We also face the similar runtime error. And we run using ArgoWorkflow `3.4.10v`.
```
Message:             runtime error: invalid memory address or nil pointer dereference
```

**Comment by terrytangyuan** [comment]
@guruprasathTT @tooptoop4 Can you try v3.5-rc1?

**Comment by CK-Yong** [comment]
Can report that we see the same issue on 3.4.11:

```
time="2023-09-14T07:28:37.796Z" level=error msg="Recovered from panic" namespace=watch r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 424 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:193 +0xbc\npanic({0x2101740, 0x3937520})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc0051a9550, 0xc004ece0a0, {0xc003d1cf60, 0x1e}, 0x1?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2902 +0xa3\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc0051a9550, {0x27b4b78, 0xc000126000}, {0xc0031abf50, 0x27}, 0xc00568ea40, {0xc002a74880, 0x6}, 0xc0036ead80, {0x27b8838, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:159 +0x1555\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0051a9550, {0x27b4b78, 0xc000126000}, {0xc001c5cab0, 0x24}, {0x27b8838, 0xc00349d680?}, 0x1ff2c80?, {{0xc00661a840, 0x1, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2041 +0x250f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc0051a9550, {0x27b4b78, 0xc000126000})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:427 +0x2d59\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000002500, {0x27b4b78, 0xc000126000})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:773 +0x759\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc002591ea0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:695 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x27954c0, 0xc001c320c0}, 0x1, 0xc000115b60)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:318 +0x1a13\n" workflow=live2vod-video-pipeline-9bxz2 pod=argoworkflows-workflow-controller-847b6d4c95-cnqhq filename=/var/log/pods/argo_argoworkflows-workflow-controller-847b6d4c95-cnqhq_3cf8f368-c7ab-4c15-8e8e-fe2824b76340/controller/0.log node_name=aks-standardhigh-16716760-vmss0000io
```

In our case, we do have an exit-handler that calls other WFTs. However, most of the time these exit handlers are working (on both successful and failed runs).

**Comment by guruprasathTT** [comment]
@terrytangyuan  We tried with `v3.5-rc1` in our dev environment. And still this error happens. 🙇 

```
Status:              Error
Message:             runtime error: invalid memory address or nil pointer dereference
Conditions:
 PodRunning          False
 Completed           True
Created:             Fri Sep 15 10:00:02 +0900 (16 hours ago)
Started:             Fri Sep 15 10:00:05 +0900 (16 hours ago)
Finished:            Fri Sep 15 11:31:07 +0900 (14 hours ago)
Duration:            1 hour 31 minutes
Progress:            0/2
ResourcesDuration:   9m9s*(1 cpu),27m53s*(100Mi memory)
```

**Comment by toyamagu-2021** [comment]
Coud you give us a workflow that can reproduce your error?

**Comment by toyamagu-2021** [comment]
Naively thinking from the error message, this can be fixed by nil checking in `buildLocalScope`.
https://github.com/argoproj/argo-workflows/blob/803c5cadb17f9ab9539085aca9035120d3a1072d/workflow/controller/operator.go#L2921

But I wonder if there is any situation nil node is passed to the above function.

**Comment by tooptoop4** [comment]
3.4.11:

```
time="2023-09-28T02:23:16.534Z" level=info msg="node redact-wf-3972248539 phase Running -> Succeeded" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.534Z" level=info msg="node redact-wf-3972248539 finished: 2023-09-28 02:23:16.534864548 +0000 UTC" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.535Z" level=info msg="node redact-wf phase Running -> Succeeded" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.535Z" level=info msg="node redact-wf finished: 2023-09-28 02:23:16.535927078 +0000 UTC" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.535Z" level=info msg="TaskSet Reconciliation" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.535Z" level=info msg=reconcileAgentPod namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.535Z" level=info msg="Running OnExit handler: exit-handler" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.536Z" level=info msg="node redact-wf-1559964155 message: retryStrategy.expression evaluated to false" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.541Z" level=error msg="was unable to obtain node for redact-306350044"
time="2023-09-28T02:23:16.541Z" level=info msg="StepGroup node redact-wf-3919149672 initialized Running" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.541Z" level=info msg="Step group node redact-wf-3919149672 successful" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.541Z" level=info msg="node redact-wf-3919149672 phase Running -> Succeeded" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.541Z" level=info msg="node redact-wf-3919149672 finished: 2023-09-28 02:23:16.541724712 +0000 UTC" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.541Z" level=error msg="Recovered from panic" namespace=auth r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 327 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:193 +0xbc\npanic({0x2101740, 0x3937520})\n\t/usr/local/go/src/runtime/panic.go:890 +0x263\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).buildLocalScope(0xc003225e40, 0xc001ad9bd0, {0xc002abcb40, 0x11}, 0x1?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2902 +0xa3\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc003225e40, {0x27b4b78, 0xc00019a010}, {0xc0055492c0, 0x2b}, 0xc0031ea8c0, {0xc002fa44e0, 0x6}, 0xc00210ad80, {0x27b8838, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:159 +0x1555\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc003225e40, {0x27b4b78, 0xc00019a010}, {0xc002ac6840, 0x28}, {0x27b8838, 0xc0022c6840?}, 0x745ef2?, {{0xc003124b40, 0x1, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2041 +0x250f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc003225e40, {0x27b4b78, 0xc00019a010})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:427 +0x2d59\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00037e500, {0x27b4b78, 0xc00019a010})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:773 +0x759\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0007f2ea0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:695 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:155 +0x3e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a76960?, {0x27954c0, 0xc0007c6150}, 0x1, 0xc000a76300)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a76960?, 0x3b9aca00, 0x0, 0x80?, 0xc0007f2fd0?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x9dee60?, 0xc0004d61b0?, 0xc0007f2fb8?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.24.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:318 +0x1a13\n" workflow=redact-wf
time="2023-09-28T02:23:16.542Z" level=info msg="Updated phase Running -> Error" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.542Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.542Z" level=info msg="Marking workflow completed" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.542Z" level=info msg="Marking workflow as pending archiving" namespace=auth workflow=redact-wf
time="2023-09-28T02:23:16.544Z" level=info msg="Workflow to be dehydrated" Workflow Size=292906
time="2023-09-28T02:23:16.547Z" level=info msg="cleaning up pod" action=deletePod key=auth/redact-wf-1340600742-agent/deletePod
time="2023-09-28T02:23:16.604Z" level=info msg="Workflow update successful" namespace=auth phase=Error resourceVersion=70504180 workflow=redact-wf
time="2023-09-28T02:23:16.661Z" level=info msg="archiving workflow" namespace=auth uid=451e4776-c3ad-4408-baf5-9373e9998175 workflow=redact-wf
```

**Comment by guruprasathTT** [comment]
@toyamagu-2021 We upgrade to v3.5.0 and the issue still continued😢

**Comment by tooptoop4** [comment]
i notice ```.onExit(0)``` step is missing an outboundNodes value completely. whereas normally would expect it to have outboundNodes to ```.onExit(0)[0].notifyError```

**Comment by tooptoop4** [comment]
has anyone tested this in 3.5.5+ https://github.com/argoproj/argo-workflows/pull/12491/files#diff-f321d4af83fcf8311dc80c0d50c59ac4c240f761206e7bb652709870eb9feb43R2999 looks like it should fix
