### ISSUE TITLE
GKE Workload Identity Service Account Failure

### ISSUE THREAD

**Issue by martin-redmaple** [argoproj/argo-workflows#12781]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issue exists when I tested with `:latest`
- [X] I have searched existing issues and could not find a match for this bug
- [X] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

When attempting to run a workflow as a service account that is configured for [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/concepts/workload-identity), the `Init` container fails with the following error:

```
time="2024-03-11T10:36:37.831Z" level=info msg="Starting Workflow Executor" version=v3.5.5
panic: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.checkErr({0x3574f80, 0xc00091c0d8})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:147 +0x5f
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.initExecutor()
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/root.go:82 +0x1a5
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.loadArtifacts({0x35a2c38?, 0x4dc7e20})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:27 +0x48
github.com/argoproj/argo-workflows/v3/cmd/argoexec/commands.NewRootCommand.NewInitCommand.func4(0xc000abd200?, {0x2d04f13?, 0x4?, 0x2d04ef7?})
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/commands/init.go:17 +0x18
github.com/spf13/cobra.(*Command).execute(0xc000539200, {0xc000697e00, 0x8, 0x8})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000538300)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(0x35a2c38?, {0x35a2df8?, 0xc000b09f80?})
        /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985 +0x47
main.main()
        /go/src/github.com/argoproj/argo-workflows/cmd/argoexec/main.go:21 +0x85
```

This error appears to be originating from `client-go` functionality. There is an [issue raised against client-go](https://github.com/kubernetes/client-go/issues/1065) that describes known problems when using the library with workload identity, and some potential work arounds.

Has anyone been able to use Argo Workflows and Workload Identity? Does anyone know of a workaround? Or, could someone suggest how best to go about incorporating some of the steps suggested in the `client-go` issue?

### Version

v3.5.5

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

1. Using Google Kubernetes Engine, create a service account configured to use Workload Identity (this involves a number of steps, but involves annotating the service account with something similar to iam.gke.io/gcp-service-account: service-account-name@gcpProject.iam.gserviceaccount.com).
2. Deploy a simple workload (I used https://github.com/argoproj/argo-workflows/blob/v3.5.5/examples/dag-diamond.yaml) updated to run as the service account above.

e.g.
```YAML
# The following workflow executes a diamond workflow
# 
#   A
#  / \
# B   C
#  \ /
#   D
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  serviceAccountName: test ## This is the modified line
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        depends: "B && C"
        template: echo
        arguments:
          parameters: [{name: message, value: D}]

  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
```

### Logs from the workflow controller

```text
time="2024-03-11T10:36:36.724Z" level=info msg="Processing workflow" Phase= ResourceVersion=395612986 namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=info msg="Task-result reconciliation" namespace=test numObjs=0 workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=info msg="Updated phase  -> Running" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=info msg="DAG node dag-diamond-m5gjk initialized Running" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3691877333, taskName D"
time="2024-03-11T10:36:36.730Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3591211619, taskName B"
time="2024-03-11T10:36:36.730Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3607989238, taskName A"
time="2024-03-11T10:36:36.730Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3607989238, taskName A"
time="2024-03-11T10:36:36.730Z" level=info msg="All of node dag-diamond-m5gjk.A dependencies [] completed" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.730Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.731Z" level=info msg="Pod node dag-diamond-m5gjk-3607989238 initialized Pending" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.750Z" level=info msg="Created pod: dag-diamond-m5gjk.A (dag-diamond-m5gjk-echo-3607989238)" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3591211619, taskName B"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3574434000, taskName C"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3574434000, taskName C"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3675099714, taskName E"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3675099714, taskName E"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3691877333, taskName D"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3591211619, taskName B"
time="2024-03-11T10:36:36.751Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3691877333, taskName D"
time="2024-03-11T10:36:36.751Z" level=info msg="TaskSet Reconciliation" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.751Z" level=info msg=reconcileAgentPod namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:36.761Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=395612989 workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.724Z" level=info msg="Processing workflow" Phase=Running ResourceVersion=395612989 namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.725Z" level=info msg="Task-result reconciliation" namespace=test numObjs=0 workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.725Z" level=info msg="Pod failed: Error (exit code 2): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" displayName=A namespace=test pod=dag-diamond-m5gjk-echo-3607989238 templateName=echo workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.725Z" level=info msg="marking node as failed since init container has non-zero exit code" namespace=test new.phase=Failed workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.725Z" level=info msg="node changed" namespace=test new.message="Error (exit code 2): invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" new.phase=Failed new.progress=0/1 nodeID=dag-diamond-m5gjk-3607989238 old.message= old.phase=Pending old.progress=0/1 workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3691877333, taskName D"
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3591211619, taskName B"
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3591211619, taskName B"
time="2024-03-11T10:36:46.726Z" level=info msg="Skipped node dag-diamond-m5gjk-3591211619 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3574434000, taskName C"
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3574434000, taskName C"
time="2024-03-11T10:36:46.726Z" level=info msg="Skipped node dag-diamond-m5gjk-3574434000 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3675099714, taskName E"
time="2024-03-11T10:36:46.726Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3675099714, taskName E"
time="2024-03-11T10:36:46.727Z" level=info msg="Skipped node dag-diamond-m5gjk-3675099714 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=warning msg="was unable to obtain the node for dag-diamond-m5gjk-3691877333, taskName D"
time="2024-03-11T10:36:46.727Z" level=info msg="Skipped node dag-diamond-m5gjk-3691877333 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="Outbound nodes of dag-diamond-m5gjk set to [dag-diamond-m5gjk-3691877333]" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="node dag-diamond-m5gjk phase Running -> Failed" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="node dag-diamond-m5gjk finished: 2024-03-11 10:36:46.727351929 +0000 UTC" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="TaskSet Reconciliation" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg=reconcileAgentPod namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="Updated phase Running -> Failed" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.727Z" level=info msg="Marking workflow completed" namespace=test workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.732Z" level=info msg="cleaning up pod" action=deletePod key=test/dag-diamond-m5gjk-1340600742-agent/deletePod
time="2024-03-11T10:36:46.736Z" level=info msg="Workflow update successful" namespace=test phase=Failed resourceVersion=395613091 workflow=dag-diamond-m5gjk
time="2024-03-11T10:36:46.745Z" level=info msg="cleaning up pod" action=labelPodCompleted key=test/dag-diamond-m5gjk-echo-3607989238/labelPodCompleted
```
### Logs from in your workflow's wait container
N/A - `wait` container is not yet running. See `init` container logs above.

**Comment by partomatl** [comment]
Our workflows (using v3.5.5) work well on GKE with workload identity federation.
Could you show what your `workflow-controller-configmap` and your service accounts look like?

**Comment by martin-redmaple** [comment]
Hi @partomatl - thanks for confirming that GKE and workload identity is running OK for you.

Digging a little deeper, I realised that I had `automountServiceAccountToken: false` set on the service account I was attempting to use. This was stopping the SA access token being mounted within the container resulting in the error above. Removing this and all works fine.
