### ISSUE TITLE
Broken redirect to archived workflows

### ISSUE THREAD

**Issue by apiwoni** [argoproj/argo-workflows#13056]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened/what did you expect to happen?

The following URL https://{{serverUrl}}/workflows/{namespace}/{workflowName} no longer redirects to  https://{{serverUrl}}/archived-workflows/{namespace}/{metadata.uid} starting with v3.4.14 when [fix(ui): missing uiUrl in ArchivedWorkflowsList #12172](https://github.com/argoproj/argo-workflows/pull/12172) has been committed.

Argo UI shows the following:

`
Error: Failed to execute 'pushState' on 'History': A history state object with URL 'https://archived-workflows/{{namepsace}}/87e895f1-50df-443b-971d-218beae9d25f' cannot be created in a document with origin 'https://xxx' and URL 'https://xxx/archived-workflows?namespace={namespace}&name=workflowName&deep=true'.
    at https://xxx/main.fa82dae05c4e68e1ec09.js:446:1047769
    at Object.confirmTransitionTo (https://xxx/main.fa82dae05c4e68e1ec09.js:446:1045618)
    at Object.push (https://xxx/main.fa82dae05c4e68e1ec09.js:446:1047680)
    at t.componentDidUpdate (https://xxx/main.fa82dae05c4e68e1ec09.js:433:843312)
    at is (https://xxx/main.fa82dae05c4e68e1ec09.js:398:83471)
    at hc (https://xxx/main.fa82dae05c4e68e1ec09.js:398:101246)
    at t.unstable_runWithPriority (https://xxx/main.fa82dae05c4e68e1ec09.js:406:3844)
    at Ho (https://xxx/main.fa82dae05c4e68e1ec09.js:398:45024)
    at pc (https://xxx/main.fa82dae05c4e68e1ec09.js:398:97718)
    at Qs (https://xxx/main.fa82dae05c4e68e1ec09.js:398:93872)
`

componentDidUpdate has added uiUrl in v3.4.14 per https://github.com/argoproj/argo-workflows/pull/12172/files

### Version

v3.4.16

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
N/A
```

### Logs from the workflow controller

```text
N/A
```

### Logs from in your workflow's wait container

```text
N/A
```

**Comment by diegofd** [comment]
We're still experiencing the same issue on 3.4.17.

Navigating to `https://SERVER/workflows/NAMESPACE/WORKFLOW_NAME` on an already archived workflow doesn't redirect to it, but fails with above `Error: Failed to execute 'pushState' on 'History'` error.

Navigating directly to the archived workflow on `https://SERVER/archived-workflows/NAMESPACE/UUID` works.

**Comment by apiwoni** [comment]
@diegofd This has not been fixed yet

**Comment by diegofd** [comment]
@apiwoni I know, sorry if my wording told a different thing :)
I just wanted to highlight that we're also hitting this issue.

**Comment by ShannonHickey** [comment]
We're encountering this issue too (or similar):

Navigating to https://SERVER/workflows/NAMESPACE/WORKFLOW_NAME instead lands me on:
https://SERVER/archived-workflows?namespace=NAMESPACE&name=WORKFLOW_NAME&deep=true

This page doesn't work for most of us (but seems to for admins).

Manually changing the link to this works:
https://SERVER/archived-workflows/NAMESPACE?name=WORKFLOW_NAME&deep=true

I wonder if this wasn't caught since it's not affecting admins.

**Comment by tooptoop4** [comment]
any idea @terrytangyuan ?

**Comment by agilgur5** [comment]
On a second look, I believe the closing paren on `uiUrl` was placed a little too far in #12172. Should be a simple fix

**Comment by agilgur5** [comment]
> including the preceding PR #9790


> ```
> Error: Failed to execute 'pushState' on 'History': A history state object with URL 'https://archived-workflows/{{namepsace}}/87e895f1-50df-443b-971d-218beae9d25f' cannot be created in a document with origin 'https://xxx' and URL 'https://xxx/archived-workflows?namespace={namespace}&name=workflowName&deep=true'.
> ```

I see the diff now, the first slash needed to be removed when `uiUrl` was added

**Comment by agilgur5** [comment]
Fixed in #13712 and should be released in the next 3.4 patch, 3.4.18
