### ISSUE TITLE
devcontainer failed to build with error: `/usr/local/share/nvm/nvm.sh: No such file or directory`

### ISSUE THREAD

**Issue by SouthWest7** [argoproj/argo-workflows#13435]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

VS Code creates the dev-container, but always failed to find nvm.sh
logs follows:
```
[+] Building 6.0s (17/18)                                        docker:default
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 4.80kB                                     0.0s
 => resolve image config for docker-image://docker.io/docker/dockerfile:1  2.3s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io           0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531b  0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/b  0.5s
 => [context dev_containers_feature_content_source] load .dockerignore     0.0s
 => => transferring dev_containers_feature_content_source: 2B              0.0s
 => [context dev_containers_feature_content_source] load from client       0.0s
 => => transferring dev_containers_feature_content_source: 57.83kB         0.0s
 => [dev_containers_target_stage 1/8] FROM mcr.microsoft.com/vscode/devco  0.0s
 => CACHED [dev_containers_target_stage 2/8] RUN mkdir -p /tmp/dev-contai  0.0s
 => CACHED [dev_containers_feature_content_normalize 2/3] COPY --from=dev  0.0s
 => CACHED [dev_containers_feature_content_normalize 3/3] RUN chmod -R 07  0.0s
 => CACHED [dev_containers_target_stage 3/8] COPY --from=dev_containers_f  0.0s
 => CACHED [dev_containers_target_stage 4/8] RUN echo "_CONTAINER_USER_HO  0.0s
 => CACHED [dev_containers_target_stage 5/8] RUN --mount=type=bind,from=d  0.0s
 => CACHED [dev_containers_target_stage 6/8] RUN --mount=type=bind,from=d  0.0s
 => ERROR [dev_containers_target_stage 7/8] RUN --mount=type=bind,from=de  2.9s
------                                                                          
 > [dev_containers_target_stage 7/8] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_2,target=/tmp/build-features-src/node_2     cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_2  && cd /tmp/dev-container-features/node_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_2:
0.485 ===========================================================================
0.485 Feature       : Node.js (via nvm), yarn and pnpm
0.485 Description   : Installs Node.js, nvm, yarn, pnpm, and needed dependencies.
0.485 Id            : ghcr.io/devcontainers/features/node
0.485 Version       : 1.5.0
0.485 Documentation : https://github.com/devcontainers/features/tree/main/src/node
0.485 Options       :
0.485     VERSION="20"
0.485     NODEGYPDEPENDENCIES="true"
0.485     NVMINSTALLPATH="/usr/local/share/nvm"
0.485     NVMVERSION="latest"
0.485     INSTALLYARNUSINGAPT="true"
0.485 ===========================================================================
1.618 NVM_VERSION=0.40.0
2.837 bash: line 10: /usr/local/share/nvm/nvm.sh: No such file or directory
2.839 ERROR: Feature "Node.js (via nvm), yarn and pnpm" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
------
Dockerfile.extended:46
--------------------
  45 |     ENV PATH="/usr/local/share/nvm/current/bin:${PATH}"
  46 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_2,target=/tmp/build-features-src/node_2 \
  47 | >>>     cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features \
  48 | >>>  && chmod -R 0755 /tmp/dev-container-features/node_2 \
  49 | >>>  && cd /tmp/dev-container-features/node_2 \
  50 | >>>  && chmod +x ./devcontainer-features-install.sh \
  51 | >>>  && ./devcontainer-features-install.sh \
  52 | >>>  && rm -rf /tmp/dev-container-features/node_2
  53 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/node_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_2  && cd /tmp/dev-container-features/node_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_2" did not complete successfully: exit code: 1
[27033 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-rog/container-features/0.65.0-1722869993223 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f /tmp/devcontainercli-rog/container-features/0.65.0-1722869993223/Dockerfile.extended -t vsc-argo-workflows-c6cfddef44ba12ff4e2f6cccd88157656146feded1c726fef06cadefa4f5cdc0-features /tmp/devcontainercli-rog/empty-folder
[27033 ms]     at ptA (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1260)
[27033 ms]     at NH (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:465:1002)
[27033 ms]     at async KtA (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:3771)
[27033 ms]     at async eB (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:482:4886)
[27033 ms]     at async hrA (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:663:200)
[27034 ms]     at async lrA (/home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js:662:13452)
[27039 ms] Exit code 1
[27045 ms] Command failed: /home/rog/.vscode-server/bin/b1c0a14de1414fcdaa400695b4db1c0799bc3124/node /home/rog/.vscode-remote-containers/dist/dev-containers-cli-0.380.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-96b9507f-1dfb-4e3f-89f9-3142897c82a01722869988063 --workspace-folder /home/rog/go/src/github.com/argoproj/argo-workflows --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu\home\rog\go\src\github.com\argoproj\argo-workflows --id-label devcontainer.config_file=/home/rog/go/src/github.com/argoproj/argo-workflows/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/rog/go/src/github.com/argoproj/argo-workflows/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-956232f1-e9a7-44a3-b398-8d5a3c941923.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[27045 ms] Exit code 1
```

### Version(s)

v3.5.8

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
nothing
```

### Logs from the workflow controller

```text
nothing
```

### Logs from in your workflow's wait container

```text
nothing
```

**Comment by agilgur5** [comment]
Huh, this error is actually from within the devcontainer `node` feature itself `ghcr.io/devcontainers/features/node:1` and not in our build code.

I wonder if its latest version has an issue? Although in this case, it couldn't find a file, so I also wonder if there might've been a network error. Have you tried rebuilding and clearing your cache?

**Comment by SouthWest7** [comment]
> Huh, this error is actually from within the devcontainer `node` feature itself `ghcr.io/devcontainers/features/node:1` and not in our build code.
> 
> I wonder if its latest version has an issue? Although in this case, it couldn't find a file, so I also wonder if there might've been a network error. Have you tried rebuilding and clearing your cache?

Hi, I build it in WSL and the feature `ghcr.io/devcontainers/features/go:1` works well. I tried to rebuild but causing the same error.
