### ISSUE TITLE
runtime error when submitting suspend template with invalid outputs

### ISSUE THREAD

**Issue by michaelzulian** [argoproj/argo-workflows#13929]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I have tested with the `:latest` image tag (i.e. `quay.io/argoproj/workflow-controller:latest`) and can confirm the issue still exists on `:latest`. If not, I have explained why, **in detail**, in my description below.
- [X] I have searched existing issues and could not find a match for this bug
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/main/docs/CONTRIBUTING.md))

### What happened? What did you expect to happen?

successfully executes the suspend template

### Version(s)

v3.6.0

### Paste a minimal workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: placeholder
  namespace: "argo"
spec:
  entrypoint: main
  templates:
    - name: main
      suspend:
        duration: "1s"

    - name: set-runtime-config
      outputs:
        parameters:
          - name: consumerConfig
            value: "{}"
      suspend:
        duration: "1"
```

### Logs from the workflow controller

```text
time="2024-11-21T20:31:25.940Z" level=info msg="Processing workflow" Phase= ResourceVersion=471623 namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=info msg="resolved artifact repository" artifactRepositoryRef="argo/#"
time="2024-11-21T20:31:25.952Z" level=info msg="Task-result reconciliation" namespace=argo numObjs=0 workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=warning msg="Node was nil, will be initialized as type Skipped" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=info msg="was unable to obtain node for , letting display name to be nodeName" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=info msg="Suspend node placeholder-mhtvc initialized Pending" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=error msg="Recovered from panic" namespace=argo r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 240 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26 +0x5e\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:195 +0xb1\npanic({0x249d5a0?, 0x4152140?})\n\t/usr/local/go/src/runtime/panic.go:785 +0x132\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.addRawOutputFields(0xc00084b200, 0x0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3512 +0x1db\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).initializeExecutableNode(0xc001dd2c00, {0xc000a0a120?, 0x22bd9c1?}, {0x287303c, 0x7}, {0xc000bafcd0?, 0x21e739f?}, 0xc00146f8c8, {0x2c8d838, 0xc001dd35c0}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2508 +0x22d\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSuspend(0xc001dd2c00, {0xc000a0a120, 0x11}, {0xc000bafcd0, 0x6}, 0xc00146f8c8, {0x2c8d838, 0xc001dd35c0}, 0xc000760780)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3435 +0x114\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001dd2c00, {0x2c87028, 0xc000b6fc80}, {0xc000a0a120, 0x11}, {0x2c8d838, 0xc001dd35c0}, 0xc0005aba40, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2184 +0x3315\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc001dd2c00, {0x2c87028, 0xc000b6fc80})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:368 +0x1ae9\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0004ee008, {0x2c86ff0, 0x41cfcc0})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:900 +0x6f7\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0004ee008)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:814 +0x85\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:226 +0x33\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000050080, {0x2c58ac0, 0xc000b00ea0}, 0x1, 0xc000300850)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:227 +0xaf\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000050080, 0x3b9aca00, 0x0, 0x1, 0xc000300850)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:204 +0x7f\nk8s.io/apimachinery/pkg/util/wait.Until(...)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:161\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run in goroutine 41\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:367 +0x182c\n" workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.952Z" level=warning msg="Recording template time"
time="2024-11-21T20:31:25.953Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.953Z" level=info msg="Marking workflow completed" namespace=argo workflow=placeholder-mhtvc
time="2024-11-21T20:31:25.953Z" level=info msg="Workflow to be dehydrated" Workflow Size=1629
time="2024-11-21T20:31:25.960Z" level=info msg="Workflow update successful" namespace=argo phase=Error resourceVersion=471624 workflow=placeholder-mhtvc
```

### Stacktrace
```
time="2024-11-21T19:14:18
.064Z" level=info msg="Suspend node placeholder-7nr42 initialized Pending" namespace=argowf workflow=placeholder-7nr42
time="2024-11-21T19:14:18
.065Z" level=error msg="Recovered from panic" namespace=argowf r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 214 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:26
 +0x5e\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:195
 +0xb1\npanic({0x249d5a0?, 0x4152140?})\n\t/usr/local/go/src/runtime/panic.go:785
 +0x132\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.addRawOutputFields(0xc0000ebc80, 0x0?)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3512
 +0x1db\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).initializeExecutableNode(0xc000387ec0, {0xc000161f38?, 0xc000619590?}, {0x287303c, 0x7}, {0xc000acacd0?, 0x0?}, 0xc0005686c8, {0x2c8d838, 0xc0005618c0}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2508
 +0x22d\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSuspend(0xc000387ec0, {0xc000161f38, 0x11}, {0xc000acacd0, 0x6}, 0xc0005686c8, {0x2c8d838, 0xc0005618c0}, 0xc000970780)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3435
 +0x114\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000387ec0, {0x2c87028, 0xc000a21e30}, {0xc000161f38, 0x11}, {0x2c8d838, 0xc0005618c0}, 0xc0009d91c0, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2184
 +0x3315\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000387ec0, {0x2c87028, 0xc000a21e30})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:368
 +0x1ae9\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000609608, {0x2c86ff0, 0x41cfcc0})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:900
 +0x6f7\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc000609608)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:814
 +0x85\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:226
 +0x33\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0005fc980, {0x2c58ac0, 0xc0009daa20}, 0x1, 0xc0005268c0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:227
 +0xaf\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005fc980, 0x3b9aca00, 0x0, 0x1, 0xc0005268c0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:204
 +0x7f\nk8s.io/apimachinery/pkg/util/wait.Until(...)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.30.3/pkg/util/wait/backoff.go:161
\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run in goroutine 60\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:367
 +0x182c\n" workflow=placeholder-7nr42
```

### Logs from in your workflow's wait container

```text
n/a
```

**Comment by Joibel** [comment]
This happens in 3.5.12 as well. The problem is a https://github.com/argoproj/argo-workflows/blob/1392ef516fd69a2cae875d746c1155f940e4948c/workflow/controller/operator.go#L3516 does not check that ValueFrom is set before using it.
The right fix feels more complex that just checking that it exists, and possibly should use HasValue() and GetValue() so all param source work in this scenario.
