### ISSUE TITLE
Constant Output Value on Template with Steps causes internal error

### ISSUE THREAD

**Issue by ebelisle** [argoproj/argo-workflows#1846]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

**What happened**:
Workflow ends with Error status.

**What you expected to happen**:
Workflow ends with Success status, globalName `causes-error` set to 'x'.

**How to reproduce it (as minimally and precisely as possible)**:
```
argo submit test-step-output.yaml
```
**Anything else we need to know?**:
* Change `entrypoint` to `invoke-container` and output parameters are correctly set.
* GlobalNames are not needed, but help demonstrate the issue.

**Environment**:
- Argo version:
```
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:38Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2019-08-19T11:13:54Z"
  compiler: gc
  gitCommit: 2d3c76f9091b6bec110a5e63777c332469e0cba2
  gitTreeState: clean
  gitVersion: v1.15.3
  goVersion: go1.12.9
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-10-18T17:56:01Z"
  compiler: gc
  gitCommit: b7174db5ee0e30c94a0b9899c20ac980c0850fc8
  gitTreeState: clean
  gitVersion: v1.14.8-eks-b7174d
  goVersion: go1.12.10
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                test-step-output-lwgc5
Namespace:           default
ServiceAccount:      developer
Status:              Error
Message:             runtime error: invalid memory address or nil pointer dereference
Created:             Fri Dec 13 12:54:17 -0700 (1 minute ago)
Started:             Fri Dec 13 12:54:17 -0700 (1 minute ago)
Finished:            Fri Dec 13 12:54:20 -0700 (1 minute ago)
Duration:            3 seconds
Output Parameters:
  error:             y

STEP                                        PODNAME                            DURATION  MESSAGE
 ⚠ test-step-output-lwgc5 (invoke-steps)                                                 Workflow operation error
 └---✔ invoke-container (invoke-container)  test-step-output-lwgc5-2356438053  2s
```
- executor logs:
```
% kc logs test-step-output-lwgc5-2356438053 -c init
Error from server (BadRequest): container init is not valid for pod test-step-output-lwgc5-2356438053
% kc logs test-step-output-lwgc5-2356438053 -c wait
time="2019-12-13T19:54:18Z" level=info msg="Creating a docker executor"
time="2019-12-13T19:54:18Z" level=info msg="Executor (version: v2.4.3, build_date: 2019-12-06T03:35:39Z) initialized (pod: default/test-step-output-lwgc5-2356438053) with template:\n{\"name\":\"invoke-container\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"parameters\":[{\"name\":\"no-error\",\"value\":\"y\",\"globalName\":\"error\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"alpine\",\"resources\":{}}}"
time="2019-12-13T19:54:18Z" level=info msg="Waiting on main container"
time="2019-12-13T19:54:19Z" level=info msg="main container started with container ID: a6a805685630fabad18c779e9776fe87d93a0c5c61f5c8a4fed0a3e8d7eab7e6"
time="2019-12-13T19:54:19Z" level=info msg="Starting annotations monitor"
time="2019-12-13T19:54:19Z" level=info msg="docker wait a6a805685630fabad18c779e9776fe87d93a0c5c61f5c8a4fed0a3e8d7eab7e6"
time="2019-12-13T19:54:19Z" level=info msg="Starting deadline monitor"
time="2019-12-13T19:54:19Z" level=info msg="Main container completed"
time="2019-12-13T19:54:19Z" level=info msg="Saving output parameters"
time="2019-12-13T19:54:19Z" level=info msg="Saving path output parameter: no-error"
time="2019-12-13T19:54:19Z" level=info msg="No output artifacts"
time="2019-12-13T19:54:19Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2019-12-13T19:54:19Z" level=info msg="Annotating pod with output"
time="2019-12-13T19:54:19Z" level=info msg="Annotations monitor stopped"
time="2019-12-13T19:54:19Z" level=info msg="Killing sidecars"
time="2019-12-13T19:54:19Z" level=info msg="Alloc=5466 TotalAlloc=11979 Sys=70590 NumGC=4 Goroutines=9"
```
- workflow-controller logs:
```
time="2019-12-13T19:54:17Z" level=info msg="Processing workflow" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Steps node test-step-output-lwgc5 (test-step-output-lwgc5) initialized Pending" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="node test-step-output-lwgc5 (test-step-output-lwgc5) phase Pending -> Running" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="StepGroup node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) initialized Running" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Pod node test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) initialized Pending" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Created pod: test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053)" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Workflow step group node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) not yet completed" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:17Z" level=info msg="Workflow update successful" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:18Z" level=info msg="Processing workflow" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:18Z" level=info msg="Updating node test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) message: ContainerCreating"
time="2019-12-13T19:54:18Z" level=info msg="Skipped pod test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) creation: already exists" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:18Z" level=info msg="Workflow step group node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) not yet completed" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:18Z" level=info msg="Workflow update successful" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:19Z" level=info msg="Processing workflow" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:19Z" level=info msg="Setting node test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) outputs"
time="2019-12-13T19:54:19Z" level=info msg="Updating node test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) status Pending -> Running"
time="2019-12-13T19:54:19Z" level=info msg="setting workflow.outputs.parameters.error: 'y'" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:19Z" level=info msg="Skipped pod test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) creation: already exists" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:19Z" level=info msg="Workflow step group node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) not yet completed" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:19Z" level=info msg="Workflow update successful" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Processing workflow" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Updating node test-step-output-lwgc5[0].invoke-container (test-step-output-lwgc5-2356438053) status Running -> Succeeded"
time="2019-12-13T19:54:20Z" level=info msg="Step group node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) successful" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) phase Running -> Succeeded" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="node test-step-output-lwgc5[0] (test-step-output-lwgc5-1720883083) finished: 2019-12-13 19:54:20.282351708 +0000 UTC" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Outbound nodes of test-step-output-lwgc5-2356438053 is [test-step-output-lwgc5-2356438053]" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Outbound nodes of test-step-output-lwgc5 is [test-step-output-lwgc5-2356438053]" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Marking workflow completed" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=error msg="Recovered from panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 126 [running]:\nruntime/debug.Stack(0xc0006b45a0, 0x18a9140, 0x25637b0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func2(0xc0006b45a0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:151 +0xb6\npanic(0x14f6d00, 0x25637b0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/argoproj/argo/workflow/controller.getTemplateOutputsFromScope(0xc0001f78c0, 0xc000fa74d0, 0x16, 0xc0001f78c0, 0xc0026397c0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1488 +0x194\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc0006b45a0, 0xc00103f960, 0x16, 0xc000d63080, 0xc0001f78c0, 0x0, 0x0, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:125 +0x5a4\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc0006b45a0, 0xc00103f8c0, 0x16, 0x18b4d00, 0xc00046d8c0, 0xc000d62dc0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1195 +0xeef\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc0006b45a0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:216 +0x5c7\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc000490400, 0xc0005a6900)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304 +0x53f\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc000490400)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230 +0x2b\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm()\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x2a\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000fa7a40)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000fa7a40, 0x3b9aca00, 0x0, 0x2020200a7b203a01, 0xc00057c360)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbe\nk8s.io/apimachinery/pkg/util/wait.Until(0xc000fa7a40, 0x3b9aca00, 0xc00057c360)\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d\ncreated by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171 +0x75f\n" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:20Z" level=info msg="Workflow update successful" namespace=default workflow=test-step-output-lwgc5
time="2019-12-13T19:54:21Z" level=info msg="Labeled pod default/test-step-output-lwgc5-2356438053 completed"
```
[test-step-output.yaml.txt](https://github.com/argoproj/argo/files/3962549/test-step-output.yaml.txt)

**Comment by alexec** [comment]
Please attach workflow YAML.
