### ISSUE TITLE
Failed to generate download URL for artifact : No module named 'ax.platform_client'

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#306]
A 1.0.1 cluster fails to download a completed log, failing with an import error with following stacktace:

```
2017-10-06T00:15:29 ERROR ax.devops.artifact.rest 49 DummyThread-53: Error occurred: code = ERR_API_INTERNAL_ERROR, message = Internal server error, detail = Failed to generate download URL for artifact (id: 81794a18-dafe-4531-9437-3e1ea388f92f): No module named 'ax.platform_client'
Traceback (most recent call last):
  File "/ax/src/ax/devops/artifact/artifactmanager.py", line 1121, in download_artifact
    location = Cloud().get_bucket(bucket).generate_signed_url(key)
  File "/ax/src/ax/cloud/cloud.py", line 157, in get_bucket
    return AXS3Bucket(bucket_name, aws_profile, region=region)
  File "/ax/src/ax/cloud/aws/aws_s3.py", line 100, in __init__
    self._region = region if region else self._get_bucket_region_from_aws()
  File "/usr/lib/python3.5/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python3.5/site-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/lib/python3.5/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/src/ax/cloud/aws/aws_s3.py", line 144, in _get_bucket_region_from_aws
    return _do_get_region(Cloud().meta_data().get_region())
  File "/ax/src/ax/cloud/cloud.py", line 120, in meta_data
    from ax.aws.meta_data import AWSMetaData
  File "/ax/src/ax/aws/meta_data.py", line 10, in <module>
    from ax.platform_client.env import AXEnv
ImportError: No module named 'ax.platform_client'
```

**Comment by sytianhe** [comment]
Check with @shrinandj

**Comment by pratulw** [comment]
@shrinandj Please look into this

**Comment by jessesuen** [comment]
This applies to all artifacts attempted to be downloaded from UI, not just logs.

**Comment by jessesuen** [comment]
The import is failing:
```
from ax.platform_client.env import AXEnv
```
but this file and class does exist:
```
$ find . -name env.py
./platform/source/lib/ax/platform_client/env.py
```

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2015-2016 Applatix, Inc. All rights reserved.
#

"""
Module library to identify python running environment.
"""

import os

from future.utils import with_metaclass

from ax.util.singleton import Singleton


class AXEnv(with_metaclass(Singleton, object)):
```

I'm wondering if the use of that Singleton metaclass is causing problems

**Comment by jessesuen** [comment]
It can't import `platform_client` because `platform_client` doesn't even exist in the container!

```
bash-4.3# ls -l /ax/src/ax
total 68
-rw-r--r--    1 root     root             0 Oct  4 01:07 __init__.py
drwxr-xr-x    2 root     root          4096 Oct  4 20:17 __pycache__
-rw-r--r--    1 root     root            85 Oct  4 01:07 _version.py
drwxr-xr-x    1 root     root          4096 Oct  6 00:04 aws
drwxr-xr-x    2 root     root          4096 Oct  4 01:07 axdb
drwxr-xr-x    2 root     root          4096 Oct  4 01:07 axevent
drwxr-xr-x    2 root     root          4096 Oct  4 01:07 cadvisor
drwxr-xr-x    1 root     root          4096 Oct  4 20:17 cloud
drwxr-xr-x    3 root     root          4096 Oct  4 01:07 cluster_management
drwxr-xr-x    1 root     root          4096 Oct  4 20:17 devops
-rw-r--r--    1 root     root          4863 Oct  4 01:07 exceptions.py
drwxr-xr-x    3 root     root          4096 Oct  4 01:07 kubernetes
drwxr-xr-x    2 root     root          4096 Oct  4 01:07 meta
-rw-r--r--    1 root     root          3533 Oct  4 01:07 notification_center.py
drwxr-xr-x    3 root     root          4096 Oct  4 01:07 test
drwxr-xr-x    1 root     root          4096 Oct  4 20:17 util
-rw-r--r--    1 root     root           950 Oct  4 01:07 version.py
```

This is a packaging issue with how the container image was built.

**Comment by shrinandj** [comment]
FILE: build/ax/build/devops.py

```
       if not re.search(‘devopsbuilder’, container_build_path):
            # DevOps source code is not protected (for the time being). Platform code is.
            # Do not copy platform code into devops containers to maintain this protection
            # and prevent exposure of our platform source to customers.
            shutil.rmtree(“{}/src/ax/platform”.format(docker_build_dir))
            shutil.rmtree(“{}/src/ax/platform_client”.format(docker_build_dir))
```

So.. the above code is in the v1.0 branch that explicitly avoids copying the `platform` and `platform_client` dirs in the axartifactmanager container. That causes the problem.

The above code was removed as part of commit 5a0c84af62c521c75e4bed1c353252d347c09711 on master. Therefore it works on master.

@sytianhe , can you cherry-pick the above commit (or the relevant parts of it) into the v1.0 branch?

**Comment by sytianhe** [comment]
That commit is about changing the devops builder to use platform builder. I don't see why it doesn't work without the commit as we have been using the devops builder all along.
