### ISSUE TITLE
Panic and ambigous error on watch endpoint

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#3604]
If the watch endpoint request is malformed; i.e., workflows to be watched are not specified with a `metadata.name=...` field selector, the server panics and an ambiguous error is returned.

Stacktrace
```
Recovered from panic: runtime error: slice bounds out of range [:-1]\ngoroutine 285 [running]:\nruntime/debug.Stack(0xc0009f7090, 0x2b42ba0, 0xc0009968e0)\n\t/usr/local/Cellar/go/1.13/libexec/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/argoproj/argo/util/grpc.PanicLoggerStreamServerInterceptor.func1.1(0xc00058aa10, 0xc0009f7920)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:31 +0x6e\npanic(0x2b42ba0, 0xc0009968e0)\n\t/usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2\ngithub.com/argoproj/argo/util.RecoverWorkflowNameFromSelectorString(0x0, 0x0, 0xc0003575c0, 0x3839d00, 0xc0003575c0, 0xc000a49080)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/util/util.go:111 +0x16e\ngithub.com/argoproj/argo/server/workflow.(*workflowServer).WatchWorkflows(0xc0009707b0, 0xc000d31dc0, 0x389a100, 0xc000895280, 0x0, 0x0)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/server/workflow/workflow_server.go:146 +0xbfa\ngithub.com/argoproj/argo/pkg/apiclient/workflow._WorkflowService_WatchWorkflows_Handler(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0xc000cf36b0, 0x0)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/pkg/apiclient/workflow/workflow.pb.go:1543 +0x10c\ngithub.com/argoproj/argo/server/auth.(*gatekeeper).StreamServerInterceptor.func1(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0xc000c0b040, 0x34ccd28, 0x0, 0x0)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/server/auth/gatekeeper.go:71 +0xcc\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0x0, 0x203000)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/argoproj/argo/util/grpc.glob..func2(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0xc000c0b040, 0xc000c0b080, 0xc, 0x2c9c8f4)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:45 +0x4e\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0x0, 0x0)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/argoproj/argo/util/grpc.PanicLoggerStreamServerInterceptor.func1(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0xc000c0b040, 0xc000c0b0a0, 0x0, 0x0)\n\t/Users/sbeharyutk/go/src/github.com/argoproj/argo/util/grpc/interceptor.go:35 +0xa8\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2bbbf80, 0xc0009707b0, 0x3893740, 0xc000c0b100, 0x28, 0xbfbfdb116ef5e578)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/logrus.StreamServerInterceptor.func1(0x2bbbf80, 0xc0009707b0, 0x3893920, 0xc0007e80c0, 0xc000c0b040, 0xc000c0b0c0, 0xc000c0b0e0, 0xc000c0b040)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/logging/logrus/server_interceptors.go:66 +0x176\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1(0x2bbbf80, 0xc0009707b0, 0x3893920, 0xc0007e80c0, 0xc000ca2c10, 0x100e798)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:49 +0x5f\ngithub.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1(0x2bbbf80, 0xc0009707b0, 0x3893920, 0xc0007e80c0, 0xc000c0b040, 0x34ccd28, 0x387e980, 0xc000cf3530)\n\t/Users/sbeharyutk/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.1.0/chain.go:58 +0xcf\ngoogle.golang.org/grpc.(*Server).processStreamingRPC(0xc000952340, 0x38a6100, 0xc000a49080, 0xc000105000, 0xc000970840, 0x4906100, 0x0, 0x0, 0x0)\n\t/Users/sbeharyutk/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1336 +0x486\ngoogle.golang.org/grpc.(*Server).handleStream(0xc000952340, 0x38a6100, 0xc000a49080, 0xc000105000, 0x0)\n\t/Users/sbeharyutk/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:1409 +0xcbe\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000225c00, 0xc000952340, 0x38a6100, 0xc000a49080, 0xc000105000)\n\t/Users/sbeharyutk/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:746 +0xbb\ncreated by google.golang.org/grpc.(*Server).serveStreams.func1\n\t/Users/sbeharyutk/go/pkg/mod/google.golang.org/grpc@v1.28.0/server.go:744 +0xa1\n
```

**Comment by alexec** [comment]
Available in [v2.9.5](https://github.com/argoproj/argo/releases/tag/v2.9.5)
