### ISSUE TITLE
installer fails when installing in minikube with no s3 key and secret

### ISSUE THREAD

**Issue by sandeepbhojwani** [argoproj/argo-workflows#377]
```
2017-10-15T17:15:12 INFO ax.cluster_management.argo_cluster_manager MainThread: s3 bucket endpoint: http://192.168.99.100:32034
2017-10-15T17:15:12 INFO ax.meta.cluster_id MainThread: Instantiating cluster bucket ...
2017-10-15T17:15:18 INFO ax.cluster_management.app.common MainThread: Cannot find cluster name id: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.. Cluster is not yet created.
2017-10-15T17:15:18 INFO ax.meta.cluster_id MainThread: Cluster id not provided, generate one.
2017-10-15T17:15:18 INFO ax.meta.cluster_id MainThread: Created new name-id sandeep-k8s5.test.eng.applatix.net-6aeb1320-b1cc-11e7-8419-025000000001
2017-10-15T17:15:18 INFO ax.meta.config_s3_path MainThread: Using AX cluster config path argo
2017-10-15T17:15:19 ERROR ax.cluster_management.argo_cluster_manager MainThread: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
Traceback (most recent call last):
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 79, in parse_args_and_run
    getattr(self, cmd)(args)
  File "/ax/python/ax/cluster_management/argo_cluster_manager.py", line 248, in install_platform_only
    PlatformOnlyInstaller(platform_install_config).run()
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 514, in __init__
    self._ci_installer = ClusterInstaller(cfg=self._cfg.get_install_config(), kubeconfig=self._cfg.kube_config)
  File "/ax/python/ax/cluster_management/app/cluster_installer.py", line 70, in __init__
    dry_run=self._cfg.dry_run
  File "/ax/python/ax/cluster_management/app/common.py", line 83, in __init__
    self._csm = ClusterStateMachine(cluster_name_id=self._idobj.get_cluster_name_id(), cloud_profile=cloud_profile)
  File "/ax/python/ax/cluster_management/app/state/state.py", line 44, in __init__
    self._cluster_info = AXClusterInfo(cluster_name_id=cluster_name_id, aws_profile=cloud_profile)
  File "/ax/python/ax/util/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/ax/python/ax/platform/ax_cluster_info.py", line 50, in __init__
    self._config = AXClusterConfig(cluster_name_id=cluster_name_id, aws_profile=aws_profile)
  File "/ax/python/ax/util/singleton.py", line 15, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/ax/python/ax/platform/cluster_config/cluster_config.py", line 33, in __init__
    self._bucket = Cloud().get_bucket(self._bucket_name, aws_profile=aws_profile)
  File "/ax/python/ax/cloud/cloud.py", line 157, in get_bucket
    return AXS3Bucket(bucket_name, aws_profile, region=region)
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 101, in __init__
    self._region = region if region else self._get_bucket_region_from_aws()
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 206, in call
    return attempt.get(self._wrap_exception)
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 169, in _get_bucket_region_from_aws
    bucket_region = _do_get_region(r)
  File "/ax/python/ax/cloud/aws/aws_s3.py", line 148, in _do_get_region
    config=Config(signature_version='s3v4'))
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 825, in create_client
    credentials = self.get_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 449, in get_credentials
    'credential_provider').load_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 1146, in load_credentials
    creds = provider.load()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 842, in load
    return self._load_creds_via_assume_role()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 861, in _load_creds_via_assume_role
    creds, response = self._retrieve_temp_credentials()
  File "/usr/local/lib/python2.7/dist-packages/botocore/credentials.py", line 970, in _retrieve_temp_credentials
    response = client.assume_role(**assume_role_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 601, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.

 !!! Operation failed due to runtime error: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid. 

```

**Comment by shrinandj** [comment]
There are no immediate plans of fixing this. The current code uses a fake-username and password.
