### ISSUE TITLE
nil pointer exception in workflow controller 

### ISSUE THREAD

**Issue by cscetbon** [argoproj/argo-workflows#4372]
## Summary 

What happened/what you expected to happen?
A step failed and instead of retrying the step like Argo usually does, it stopped there with the following message 
`runtime error: invalid memory address or nil pointer dereference`. It started since we upgraded Argo from v2.10 to v2.11.6

## Diagnostics

What Kubernetes provider are you using? 
```
$ k version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

What version of Argo Workflows are you running? 
```
$ argo version
argo: latest+5eebce9.dirty
  BuildDate: 2020-10-19T20:59:29Z
  GitCommit: 5eebce9af4409da9de536f189877542dd88692e0
  GitTreeState: dirty
  GitTag: v2.11.6
  GoVersion: go1.15.3
  Compiler: gc
  Platform: darwin/amd64

$ kdp -n argo workflow-controller-859896b4fc-7cks9|grep -m 1 Image
    Image:         argoproj/workflow-controller:v2.11.6
```

Here are the logs of the workflow controller
```Logos
time="2020-10-25T04:14:44Z" level=error msg="Recovered from panic" namespace=marketing r="runtime error: invalid memory address or nil pointer dereference" 
stack="goroutine 434 [running]:\nruntime/debug.Stack(0xc00b4df9b9, 0x17d5fa0, 0x2986ba0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 
+0x9d\ngithub.com/argoproj/argo/workflow/controller.*wfOperationCtx).operate.func2(0xc000671ce0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:172 
+0xc4\npanic(0x17d5fa0, 0x2986ba0)\n\t/usr/local/go/src/runtime/panic.go:679 
+0x1b2\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).processNodeRetries(0xc000671ce0, 0xc001adb380, 0xc0023be500, 0x0, 0x0, 0xc0007b25a0, 0xc000f895d8, 
0x0, 0x0, 0x2264656465656363, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:714 
+0x582\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000671ce0, 0xc0013ca380, 0x6a, 0x1c75480, 0xc0007e1970, 0xc000659080, 0xc000f087e0, 
0x3, 0x4, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1593 
+0xca9\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc000671ce0, 
0xc000269500, 0xf, 0x4, 0xc0023894d0, 0x26, 0xc000f8aa10, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:233 
+0x11ea\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc000671ce0, 
0xc001938db0, 0x23, 0xc000659080, 0xc0023885d0, 0x29, 0xc00016aa00, 0x1c75480, 0xc0006beb00, 0xc0005cd6c8, 
...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:91 
+0x474\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000671ce0, 0xc001938db0, 
0x23, 0x1c75480, 0xc0006beb00, 0xc000658a80, 0x0, 0x0, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1645 
+0x205f\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc000671ce0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:315 
+0xf43\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc00015a000, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:514 
+0x72b\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc00015a000)\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:430 
+0x2b\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0018c62f0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:152 
+0x5e\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0018c62f0, 0x3b9aca00, 0x0, 0x1, 0xc0006c4360)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:153 
+0xf8\nk8s.io/apimachinery/
pkg/util/wait.Until(0xc0018c62f0, 0x3b9aca00, 0xc0006c4360)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:88 
+0x4d\ncreated by github.com/argoproj/argo/workflow/controller.*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:202 
+0x9cd\n" workflow=marketing-spend-all-jobs-zjzmv
time="2020-10-25T04:14:44Z" level=info msg="Updated phase Running -> Error" namespace=marketing workflow=marketing-spend-all-jobs-zjzmv
time="2020-10-25T04:14:44Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=marketing workflow=marketing-spend-all-jobs-zjzmv
```
I can see that our last failed workflows are marked with that same exception:
```
$ argo list|awk '/Error/ {print $1}'|xargs -I XX argo get XX|grep Message
Message:             runtime error: invalid memory address or nil pointer dereference
Message:             runtime error: invalid memory address or nil pointer dereference
Message:             runtime error: invalid memory address or nil pointer dereference
```
---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
#4376 should be the fix, but can you add a workflow to reproduce to verify?

**Comment by cscetbon** [comment]
The workflow we have is really dependent on what we do so I would need some time to build a fake one. But what I can tell you is that we have that section in the workflow which seems to match your fix:
```
...
name: run-get-reports-job
      outputs: {}
retryStrategy:
        backoff:
          duration: 5m
        limit: 5
...
```

Also I hope you'll add some tests @simster7 to use that code with workflows that have or not a retry strategy etc...

**Comment by sarabala1979** [comment]
V2.10 to v2.11 upgrade could cause this issue. We have refactored IntStr in v2.11.

**Comment by cscetbon** [comment]
@simster7 I finally got one that you can test 
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nil-pointer-exception-
spec:
  entrypoint: entry
  templates:
  - name: entry
    steps:
    - - name: step1
        template: working
    - - name: step2
        template: failing
    
  - name: working
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo OK"]

  - name: failing
    retryStrategy:
      limit: 5
      backoff:
        duration: 5m
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo intentional failure; exit 1"]
```

```
Name:                nil-pointer-exception-pl64v
Namespace:           argo
ServiceAccount:      default
Status:              Error
Message:             runtime error: invalid memory address or nil pointer dereference
Conditions:
 Completed           True
Created:             Mon Oct 26 10:38:57 -0400 (8 seconds ago)
Started:             Mon Oct 26 10:38:57 -0400 (8 seconds ago)
Finished:            Mon Oct 26 10:39:05 -0400 (now)
Duration:            8 seconds
ResourcesDuration:   4s*(1 cpu),4s*(100Mi memory)

STEP                            TEMPLATE  PODNAME                                 DURATION  MESSAGE
 ⚠ nil-pointer-exception-pl64v  entry                                                       Workflow operation error
 ├---✔ step1                    working   nil-pointer-exception-pl64v-3219032554  3s
 └---✖ step2(0)                 failing   nil-pointer-exception-pl64v-2628947329  3s        failed with exit code 1
```

**Comment by simster7** [comment]
Thanks @cscetbon, I confirmed the fix works
