### ISSUE TITLE
v2.11.7: UI errors out with `Cannot read property 'forEach' of undefined`

### ISSUE THREAD

**Issue by kushthedude** [argoproj/argo-workflows#4661]
## Summary 

I navigated to the main workflows page http://localhost:2746/workflows/argo and received an error with a stack trace. I expected to see my workflows listed.

## Diagnostics

What Kubernetes provider are you using? 
AKS

What version of Argo Workflows are you running? 
v2.11.7

Stacktrace
```js
Cannot read property 'forEach' of undefined
 Reload this page to try again.
Stack Trace
TypeError: Cannot read property 'forEach' of undefined
    at t.get (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:89:265536)
    at t.saveHistory (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:89:265749)
    at oa (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:72729)
    at ra (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:72479)
    at Ha (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:82493)
    at Va (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:84967)
    at http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:98147
    at Object.t.unstable_runWithPriority (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:405:3194)
    at Ts (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:98082)
    at Es (http://localhost:2746/main.a56dcbe022dfd2a79d67.js:396:97858)
Component Stack

    in t
    in t
    in t
    in Unknown
    in t
    in t
    in t
    in div
    in Unknown
    in t
    in n
```

It works fine on incognito, also an error goes out when I clear my `localStorage`.

Similar to issue https://github.com/argoproj/argo/issues/4123

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
workaround = clear local storage

does this re-occur after local storage is cleared?

**Comment by kushthedude** [comment]
> workaround = clear local storage
> 
> does this re-occur after local storage is cleared?

Nope!

**Comment by alexec** [comment]
Good stuff. Maybe won't fix then :)
