### ISSUE TITLE
invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by duongnt** [argoproj/argo-workflows#4806]
## Summary 

When I upgraded to 2.12.2, I got this exception: `invalid memory address or nil pointer dereference`.

## Diagnostics

Full stack trace:
```
runtime error: invalid memory address or nil pointer dereference" stack="goroutine 474 [running]:
runtime/debug.Stack(0xc07be0a103, 0x183dfc0, 0x2a5aea0)
     /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func2(0xc002e23380)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:185 +0xbe
panic(0x183dfc0, 0x2a5aea0)
     /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).estimateNodeDuration(0xc002e23380, 0xc003e7f680, 0x30, 0x2a9b860)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1890 +0x31
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).initializeNode(0xc002e23380, 0xc003e7f680, 0x30, 0x1a65bd0, 0x3, 0xc003e7f890, 0x26, 0x1cf9d60, 0xc002c0b260, 0xc009a311a0, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1995 +0x36d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).initializeExecutableNode(0xc002e23380, 0xc003e7f680, 0x30, 0x1a65bd0, 0x3, 0xc003e7f890, 0x26, 0xc0056cb180, 0x1cf9d60, 0xc002c0b260, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1924 +0xf0
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeResource(0xc002e23380, 0xc003e7f680, 0x30, 0xc003e7f890, 0x26, 0xc0056cb180, 0x1cf9d60, 0xc002c0b260, 0xc001fe66c0, 0x696d5f6465746365, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:2587 +0x8f9
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc002e23380, 0xc003e7f680, 0x30, 0x1cf9d60, 0xc002c0b260, 0xc0064c4e40, 0x0, 0x0, 0x0, 0x0, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1709 +0x21de
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc002e23380, 0xc00032ba40, 0xc006e67561, 0xf)
     /go/src/github.com/argoproj/argo/workflow/controller/dag.go:458 +0x93b
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc002e23380, 0xc00032ba40, 0xc006fe5ac0, 0xb)
     /go/src/github.com/argoproj/argo/workflow/controller/dag.go:388 +0x4c9
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeDAG(0xc002e23380, 0xc009a30dc0, 0x20, 0xc0064c4e40, 0xc003e7f2f0, 0x26, 0xc0056ca500, 0x1cf9f20, 0xc00563a6e0, 0xc001feb660, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/dag.go:240 +0x2e9
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc002e23380, 0xc009a30dc0, 0x20, 0x1cf9f20, 0xc00563a6e0, 0xc0064c4e00, 0x0, 0x0, 0x0, 0x0, ...)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1711 +0x208e
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc002e23380)
     /go/src/github.com/argoproj/argo/workflow/controller/operator.go:339 +0xd3e
github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc000459500, 0x0)
     /go/src/github.com/argoproj/argo/workflow/controller/controller.go:580 +0x828
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc000459500)
     /go/src/github.com/argoproj/argo/workflow/controller/controller.go:502 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000d76d60)
     /go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d76d60, 0x3b9aca00, 0x0, 0x1d26401, 0xc000729500)
     /go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000d76d60, 0x3b9aca00, 0xc000729500)
     /go/pkg/mod/k8s.io/apimachinery@v0.17.8/pkg/util/wait/wait.go:88 +0x4d
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
     /go/src/github.com/argoproj/argo/workflow/controller/controller.go:216 +0xa50
```

This happened because `woc.controller.estimatorFactory.NewEstimator(woc.wf)` returns nil for estimator when there was an error fetching archived workflows (network issues in our case). The error was swallowed which made it hard to pinpoint the root cause.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
Fix for this is out on https://github.com/argoproj/argo/releases/tag/v2.12.3
