### ISSUE TITLE
Error when writing artifacts

### ISSUE THREAD

**Issue by Guillermogsjc** [argoproj/argo-workflows#5110]
## Summary 

I was in Argo version 2.12.7, executing passing artifacts example was working without any problem. I also tested the command on 2.12.8 and works fine.

After upgrading to 3.0.0-rc1 every artifact write started crashing with

```
failed to save outputs: runtime error: invalid memory address or nil pointer dereference
```

## Diagnostics

What Kubernetes provider are you using? 

EKS

What version of Argo Workflows are you running? 

3.0.0rc1

Reproducible command:

```yaml
argo submit https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/artifact-passing.yaml -n argo
```

Logs
```
time="2021-02-15T13:31:18.863Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.866Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.867Z" level=info msg="Steps node artifact-passing-tj9dl initialized Running" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.867Z" level=info msg="StepGroup node artifact-passing-tj9dl-698941965 initialized Running" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.867Z" level=info msg="Pod node artifact-passing-tj9dl-3297462087 initialized Pending" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.904Z" level=info msg="Created pod: artifact-passing-tj9dl[0].generate-artifact (artifact-passing-tj9dl-3297462087)" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.904Z" level=info msg="Workflow step group node artifact-passing-tj9dl-698941965 not yet completed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:18.916Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=8977025 workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.906Z" level=info msg="Processing workflow" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.906Z" level=info msg="Pod failed: failed to save outputs: runtime error: invalid memory address or nil pointer dereference" displayName=generate-artifact namespace=argo pod=artifact-passing-tj9dl-3297462087 templateName=whalesay workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.906Z" level=info msg="Updating node artifact-passing-tj9dl-3297462087 status Pending -> Error" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.906Z" level=info msg="Updating node artifact-passing-tj9dl-3297462087 message: failed to save outputs: runtime error: invalid memory address or nil pointer dereference" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Step group node artifact-passing-tj9dl-698941965 deemed failed: child 'artifact-passing-tj9dl-3297462087' failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl-698941965 phase Running -> Failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl-698941965 message: child 'artifact-passing-tj9dl-3297462087' failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl-698941965 finished: 2021-02-15 13:31:28.907169599 +0000 UTC" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="step group artifact-passing-tj9dl-698941965 was unsuccessful: child 'artifact-passing-tj9dl-3297462087' failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Outbound nodes of artifact-passing-tj9dl-3297462087 is [artifact-passing-tj9dl-3297462087]" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Outbound nodes of artifact-passing-tj9dl is [artifact-passing-tj9dl-3297462087]" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl phase Running -> Failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl message: child 'artifact-passing-tj9dl-3297462087' failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="node artifact-passing-tj9dl finished: 2021-02-15 13:31:28.90726204 +0000 UTC" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Checking daemoned children of artifact-passing-tj9dl" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Updated message  -> child 'artifact-passing-tj9dl-3297462087' failed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Marking workflow completed" namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.907Z" level=info msg="Checking daemoned children of " namespace=argo workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.920Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=8977080 workflow=artifact-passing-tj9dl
time="2021-02-15T13:31:28.926Z" level=info msg="cleaning up pod" action=labelPodCompleted key=argo/artifact-passing-tj9dl-3297462087/labelPodCompleted

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Thank you. Can you please include the logs of the containers `wait` for the pod that crashed?

**Comment by Guillermogsjc** [comment]
Hi, I guess that you ask for the stage pod log. Here are two examples:

```
time="2021-02-15T17:17:47.774Z" level=info msg="Starting Workflow Executor" version=v3.0.0-rc1
time="2021-02-15T17:17:47.782Z" level=info msg="Creating a docker executor"
time="2021-02-15T17:17:47.782Z" level=info msg="Executor (version: v3.0.0-rc1, build_date: 2021-02-08T22:54:02Z) initialized (pod: argo/artifact-passing-zd452-117216215) with template:\n{\"name\":\"whalesay\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"hello-art\",\"path\":\"/tmp/hello_world.txt\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"sleep 1; cowsay hello world | tee /tmp/hello_world.txt\"],\"resources\":{}},\"archiveLocation\":{\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"batch-artifact-repository-967366354780\",\"key\":\"artifact-passing-zd452/artifact-passing-zd452-117216215\"}}}"
time="2021-02-15T17:17:47.782Z" level=info msg="Waiting on main container"
time="2021-02-15T17:17:47.790Z" level=info msg="Watch pods 200"
time="2021-02-15T17:17:49.562Z" level=info msg="main container started with container ID: 72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439"
time="2021-02-15T17:17:49.562Z" level=info msg="Starting annotations monitor"
time="2021-02-15T17:17:49.566Z" level=info msg="Get pods 200"
time="2021-02-15T17:17:49.567Z" level=info msg="docker wait 72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439"
time="2021-02-15T17:17:49.567Z" level=info msg="Starting deadline monitor"
time="2021-02-15T17:17:50.193Z" level=info msg="Main container completed"
time="2021-02-15T17:17:50.193Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-02-15T17:17:50.193Z" level=info msg="Capturing script exit code"
time="2021-02-15T17:17:50.194Z" level=info msg="Annotations monitor stopped"
time="2021-02-15T17:17:50.220Z" level=info msg="No output parameters"
time="2021-02-15T17:17:50.220Z" level=info msg="Saving output artifacts"
time="2021-02-15T17:17:50.220Z" level=info msg="Staging artifact: hello-art"
time="2021-02-15T17:17:50.220Z" level=info msg="Copying /tmp/hello_world.txt from container base image layer to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:50.220Z" level=info msg="Archiving 72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439:/tmp/hello_world.txt to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:50.220Z" level=info msg="sh -c docker cp -a 72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439:/tmp/hello_world.txt - | gzip  > /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:50.403Z" level=info msg="Archiving completed"
time="2021-02-15T17:17:50.403Z" level=info msg="Killing sidecars"
time="2021-02-15T17:17:50.407Z" level=info msg="Get pods 200"
time="2021-02-15T17:17:50.408Z" level=info msg="Alloc=5912 TotalAlloc=10357 Sys=73041 NumGC=3 Goroutines=10"
time="2021-02-15T17:17:50.419Z" level=info msg="Patch pods 200"
time="2021-02-15T17:17:50.420Z" level=fatal msg="executor panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 1 [running]:\nruntime/debug.Stack(0x203767f, 0x14, 0xc00073d080)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).HandleError(0xc0000ec600, 0x2353480, 0xc000126010)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:132 +0x47d\npanic(0x1d94680, 0x3029d20)\n\t/usr/local/go/src/runtime/panic.go:975 +0x47a\ngithub.com/argoproj/argo/v3/workflow/artifacts.NewDriver(0x2353480, 0xc000126010, 0xc000656b40, 0x2315a40, 0xc0000ec600, 0x0, 0x0, 0xc0006ef728, 0x1b733f2)\n\t/go/src/github.com/argoproj/argo/workflow/artifacts/artifacts.go:39 +0x4d\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).InitDriver(0xc0000ec600, 0x2353480, 0xc000126010, 0xc000656b40, 0x0, 0xc000749540, 0xc0006ef7a8, 0x44090a)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:603 +0x65\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).saveArtifactFromFile(0xc0000ec600, 0x2353480, 0xc000126010, 0xc0006ef958, 0xc000741330, 0xd, 0xc00072b320, 0x29, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:325 +0xc5\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).saveArtifact(0xc0000ec600, 0x2353480, 0xc000126010, 0xc0003de509, 0x40, 0xc0006ef958, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:304 +0x31d\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).SaveArtifacts(0xc0000ec600, 0x2353480, 0xc000126010, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:282 +0x214\ngithub.com/argoproj/argo/v3/cmd/argoexec/commands.waitContainer(0x2353480, 0xc000126010, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:73 +0x9ba\ngithub.com/argoproj/argo/v3/cmd/argoexec/commands.NewWaitCommand.func1(0xc00004d600, 0x3087840, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:18 +0x3d\ngithub.com/spf13/cobra.(*Command).execute(0xc00004d600, 0x3087840, 0x0, 0x0, 0xc00004d600, 0x3087840)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc00004cdc0, 0xc000068778, 0xc000675f78, 0x4062c5)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main()\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:13 +0x2b\n"
```

```
time="2021-02-15T17:17:32.278Z" level=info msg="Starting Workflow Executor" version=v3.0.0-rc1
time="2021-02-15T17:17:32.291Z" level=info msg="Creating a docker executor"
time="2021-02-15T17:17:32.291Z" level=info msg="Executor (version: v3.0.0-rc1, build_date: 2021-02-08T22:54:02Z) initialized (pod: argo/artifact-passing-t82dm-3762044395) with template:\n{\"name\":\"whalesay\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"artifacts\":[{\"name\":\"hello-art\",\"path\":\"/tmp/hello_world.txt\"}]},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay:latest\",\"command\":[\"sh\",\"-c\"],\"args\":[\"sleep 1; cowsay hello world | tee /tmp/hello_world.txt\"],\"resources\":{}},\"archiveLocation\":{\"s3\":{\"endpoint\":\"s3.amazonaws.com\",\"bucket\":\"batch-artifact-repository-967366354780\",\"key\":\"artifact-passing-t82dm/artifact-passing-t82dm-3762044395\"}}}"
time="2021-02-15T17:17:32.291Z" level=info msg="Waiting on main container"
time="2021-02-15T17:17:32.319Z" level=info msg="Watch pods 200"
time="2021-02-15T17:17:33.779Z" level=info msg="main container started with container ID: 7d58e324009a211772547c3c923ca904e11f5f8cf850bdc7667aaa5ab29e12c3"
time="2021-02-15T17:17:33.779Z" level=info msg="Starting annotations monitor"
time="2021-02-15T17:17:33.782Z" level=info msg="Get pods 200"
time="2021-02-15T17:17:33.785Z" level=info msg="docker wait 7d58e324009a211772547c3c923ca904e11f5f8cf850bdc7667aaa5ab29e12c3"
time="2021-02-15T17:17:33.785Z" level=info msg="Starting deadline monitor"
time="2021-02-15T17:17:34.373Z" level=info msg="Main container completed"
time="2021-02-15T17:17:34.373Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2021-02-15T17:17:34.373Z" level=info msg="Capturing script exit code"
time="2021-02-15T17:17:34.373Z" level=info msg="Annotations monitor stopped"
time="2021-02-15T17:17:34.403Z" level=info msg="No output parameters"
time="2021-02-15T17:17:34.403Z" level=info msg="Saving output artifacts"
time="2021-02-15T17:17:34.403Z" level=info msg="Staging artifact: hello-art"
time="2021-02-15T17:17:34.404Z" level=info msg="Copying /tmp/hello_world.txt from container base image layer to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:34.404Z" level=info msg="Archiving 7d58e324009a211772547c3c923ca904e11f5f8cf850bdc7667aaa5ab29e12c3:/tmp/hello_world.txt to /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:34.404Z" level=info msg="sh -c docker cp -a 7d58e324009a211772547c3c923ca904e11f5f8cf850bdc7667aaa5ab29e12c3:/tmp/hello_world.txt - | gzip  > /tmp/argo/outputs/artifacts/hello-art.tgz"
time="2021-02-15T17:17:34.598Z" level=info msg="Archiving completed"
time="2021-02-15T17:17:34.600Z" level=info msg="Killing sidecars"
time="2021-02-15T17:17:34.603Z" level=info msg="Get pods 200"
time="2021-02-15T17:17:34.604Z" level=info msg="Alloc=4458 TotalAlloc=10317 Sys=72785 NumGC=4 Goroutines=10"
time="2021-02-15T17:17:34.620Z" level=info msg="Patch pods 200"
time="2021-02-15T17:17:34.621Z" level=fatal msg="executor panic: runtime error: invalid memory address or nil pointer dereference\ngoroutine 1 [running]:\nruntime/debug.Stack(0x203767f, 0x14, 0xc000136700)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).HandleError(0xc000140f00, 0x2353480, 0xc000056028)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:132 +0x47d\npanic(0x1d94680, 0x3029d20)\n\t/usr/local/go/src/runtime/panic.go:975 +0x47a\ngithub.com/argoproj/argo/v3/workflow/artifacts.NewDriver(0x2353480, 0xc000056028, 0xc000201500, 0x2315a40, 0xc000140f00, 0x0, 0x0, 0xc000749728, 0x1b733f2)\n\t/go/src/github.com/argoproj/argo/workflow/artifacts/artifacts.go:39 +0x4d\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).InitDriver(0xc000140f00, 0x2353480, 0xc000056028, 0xc000201500, 0x0, 0xc0005ec4c0, 0xc0007497a8, 0x44090a)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:603 +0x65\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).saveArtifactFromFile(0xc000140f00, 0x2353480, 0xc000056028, 0xc000749958, 0xc000780090, 0xd, 0xc00078c030, 0x29, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:325 +0xc5\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).saveArtifact(0xc000140f00, 0x2353480, 0xc000056028, 0xc0007aa009, 0x40, 0xc000749958, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:304 +0x31d\ngithub.com/argoproj/argo/v3/workflow/executor.(*WorkflowExecutor).SaveArtifacts(0xc000140f00, 0x2353480, 0xc000056028, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/workflow/executor/executor.go:282 +0x214\ngithub.com/argoproj/argo/v3/cmd/argoexec/commands.waitContainer(0x2353480, 0xc000056028, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:73 +0x9ba\ngithub.com/argoproj/argo/v3/cmd/argoexec/commands.NewWaitCommand.func1(0xc000147600, 0x3087840, 0x0, 0x0)\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:18 +0x3d\ngithub.com/spf13/cobra.(*Command).execute(0xc000147600, 0x3087840, 0x0, 0x0, 0xc000147600, 0x3087840)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2\ngithub.com/spf13/cobra.(*Command).ExecuteC(0xc000146dc0, 0xc000068778, 0xc0006a7f78, 0x4062c5)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375\ngithub.com/spf13/cobra.(*Command).Execute(...)\n\t/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main()\n\t/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:13 +0x2b\n"

```

**Comment by alexec** [comment]
```golang
		if art.S3.AccessKeySecret.Name != "" {
			accessKeyBytes, err := ri.GetSecret(ctx, art.S3.AccessKeySecret.Name, art.S3.AccessKeySecret.Key)
```

It looks like AccessKeySecret is nil. This is likely cause by key-only artifacts.

**Comment by alexec** [comment]
Hmmm. Works for me.

Can I requests some additional information?

* The YAMl of the pod
* Your `workflow-controller-configmap` as YAML.

**Comment by Guillermogsjc** [comment]
@alexec so which would be the necessary changes on https://github.com/argoproj/argo-workflows/blob/master/examples/artifact-passing.yaml so it can work on 3.0.0rc?

**Comment by Guillermogsjc** [comment]
Sure, here it is:

Pod yaml:

```
kind: Pod
apiVersion: v1
metadata:
  name: artifact-passing-zd452-117216215
  namespace: argo
  selfLink: /api/v1/namespaces/argo/pods/artifact-passing-zd452-117216215
  uid: e788b88d-46e5-4968-8829-9a66d0afc7e6
  resourceVersion: '9026313'
  creationTimestamp: '2021-02-15T17:17:46Z'
  labels:
    workflows.argoproj.io/completed: 'true'
    workflows.argoproj.io/workflow: artifact-passing-zd452
  annotations:
    kubernetes.io/psp: eks.privileged
    workflows.argoproj.io/node-message: 'runtime error: invalid memory address or nil pointer dereference'
    workflows.argoproj.io/node-name: 'artifact-passing-zd452[0].generate-artifact'
    workflows.argoproj.io/template: >-
      {"name":"whalesay","arguments":{},"inputs":{},"outputs":{"artifacts":[{"name":"hello-art","path":"/tmp/hello_world.txt"}]},"metadata":{},"container":{"name":"","image":"docker/whalesay:latest","command":["sh","-c"],"args":["sleep
      1; cowsay hello world | tee
      /tmp/hello_world.txt"],"resources":{}},"archiveLocation":{"s3":{"endpoint":"s3.amazonaws.com","bucket":"batch-artifact-repository-ZZZZ","key":"artifact-passing-zd452/artifact-passing-zd452-117216215"}}}
  ownerReferences:
    - apiVersion: argoproj.io/v1alpha1
      kind: Workflow
      name: artifact-passing-zd452
      uid: 665f77b8-c1c7-4118-86eb-6b1b84972a2d
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: argoexec
      operation: Update
      apiVersion: v1
      time: '2021-02-15T17:17:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:workflows.argoproj.io/node-message': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-02-15T17:17:50Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"172.80.138.74"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
    - manager: workflow-controller
      operation: Update
      apiVersion: v1
      time: '2021-02-15T17:17:56Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:workflows.argoproj.io/node-name': {}
            'f:workflows.argoproj.io/template': {}
          'f:labels':
            .: {}
            'f:workflows.argoproj.io/completed': {}
            'f:workflows.argoproj.io/workflow': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"665f77b8-c1c7-4118-86eb-6b1b84972a2d"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"main"}':
              .: {}
              'f:args': {}
              'f:command': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
            'k:{"name":"wait"}':
              .: {}
              'f:command': {}
              'f:env':
                .: {}
                'k:{"name":"ARGO_POD_NAME"}':
                  .: {}
                  'f:name': {}
                  'f:valueFrom':
                    .: {}
                    'f:fieldRef':
                      .: {}
                      'f:apiVersion': {}
                      'f:fieldPath': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/argo/podmetadata"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                'k:{"mountPath":"/var/run/docker.sock"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:readOnly': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"docker-sock"}':
              .: {}
              'f:hostPath':
                .: {}
                'f:path': {}
                'f:type': {}
              'f:name': {}
            'k:{"name":"podmetadata"}':
              .: {}
              'f:downwardAPI':
                .: {}
                'f:defaultMode': {}
                'f:items': {}
              'f:name': {}
spec:
  volumes:
    - name: podmetadata
      downwardAPI:
        items:
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
    - name: default-token-gg5gv
      secret:
        secretName: default-token-gg5gv
        defaultMode: 420
  containers:
    - name: wait
      image: 'argoproj/argoexec:v3.0.0-rc1'
      command:
        - argoexec
        - wait
      env:
        - name: ARGO_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      resources: {}
      volumeMounts:
        - name: podmetadata
          mountPath: /argo/podmetadata
        - name: docker-sock
          readOnly: true
          mountPath: /var/run/docker.sock
        - name: default-token-gg5gv
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: main
      image: 'docker/whalesay:latest'
      command:
        - sh
        - '-c'
      args:
        - sleep 1; cowsay hello world | tee /tmp/hello_world.txt
      resources: {}
      volumeMounts:
        - name: default-token-gg5gv
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: ip-172-80-132-231.eu-west-1.compute.internal
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-15T17:17:46Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-02-15T17:17:50Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [wait main]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-02-15T17:17:50Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [wait main]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-02-15T17:17:46Z'
  hostIP: 172.80.132.231
  podIP: 172.80.138.74
  podIPs:
    - ip: 172.80.138.74
  startTime: '2021-02-15T17:17:46Z'
  containerStatuses:
    - name: main
      state:
        terminated:
          exitCode: 0
          reason: Completed
          startedAt: '2021-02-15T17:17:49Z'
          finishedAt: '2021-02-15T17:17:50Z'
          containerID: >-
            docker://72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439
      lastState: {}
      ready: false
      restartCount: 0
      image: 'docker/whalesay:latest'
      imageID: >-
        docker-pullable://docker/whalesay@sha256:178598e51a26abbc958b8a2e48825c90bc22e641de3d31e18aaf55f3258ba93b
      containerID: >-
        docker://72b39b7d531007fad1463bad829314b8007222f977fcf1ae6e5a44261aded439
      started: false
    - name: wait
      state:
        terminated:
          exitCode: 1
          reason: Error
          message: 'runtime error: invalid memory address or nil pointer dereference'
          startedAt: '2021-02-15T17:17:47Z'
          finishedAt: '2021-02-15T17:17:50Z'
          containerID: >-
            docker://3e5a1562ad9fda312f5623f563ac5bc90b7f1694d5d52acef3618011b70c26a4
      lastState: {}
      ready: false
      restartCount: 0
      image: 'argoproj/argoexec:v3.0.0-rc1'
      imageID: >-
        docker-pullable://argoproj/argoexec@sha256:00ac3b908e93c8d6d2b6cb1b39ec447c8139692de38a5698e584fad77f578639
      containerID: >-
        docker://3e5a1562ad9fda312f5623f563ac5bc90b7f1694d5d52acef3618011b70c26a4
      started: false
  qosClass: BestEffort
```

Workflow controller configmap:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: workflow-controller-configmap
  namespace: argo
  selfLink: /api/v1/namespaces/argo/configmaps/workflow-controller-configmap
  uid: e662bbf8-7bd3-4905-94b7-25f36005fe71
  resourceVersion: '3274523'
  creationTimestamp: '2021-01-15T18:48:51Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      time: '2021-01-27T00:58:23Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:config': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
data:
  config: |-
    artifactRepository:
      s3:
        bucket: batch-artifact-repository-ZZZZ
        endpoint: s3.amazonaws.com

```

**Comment by alexec** [comment]
Let me get this right, your S3 bucket does not have a username or password, presumably, you use something else to auth?

**Comment by Guillermogsjc** [comment]
Every nodegroup that provides argo workers has a policy like this attached to its role:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::batch-artifact-repository-${ACCOUNT_ID}",
        "arn:aws:s3:::batch-artifact-repository-${ACCOUNT_ID}/*"
      ]
    }
  ]
}
```

**Comment by alexec** [comment]
Super interesting bug related to how Go deals with pointer and non-pointer structs. Another example of where Go is a bit too C-like, and makes me want to learn Rust more.

**Comment by alexec** [comment]
I've just uploaded a new executor image for you to test:

```
docker pull alexcollinsintuit/argoexec:fix-5110  
```

**Comment by Guillermogsjc** [comment]
Sorry do you have a short guideline about kubectl appy of argo manifest for deploying custom images?

**Comment by alexec** [comment]
update argoexec in `workflow-controller` deployment and/or `workflow-controller-configmap` configmap.

**Comment by Guillermogsjc** [comment]
Yep, fixed
