### ISSUE TITLE
TestResubmitPendingPods is flakey

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5365]
```
2021-03-11T15:31:55.1662889Z         	Test:       	TestResubmitPendingPods
2021-03-11T15:31:55.1663985Z time="2021-03-11T15:31:46Z" level=info msg="Processing workflow" namespace=my-ns workflow=my-wf
2021-03-11T15:31:55.1665283Z time="2021-03-11T15:31:46Z" level=info msg="Updating node my-wf status Error -> Succeeded" namespace=my-ns workflow=my-wf
2021-03-11T15:31:55.1666794Z time="2021-03-11T15:31:46Z" level=panic msg="workflow is already fulfilled" fromPhase=Error namespace=my-ns toPhase=Succeeded workflow=my-wf
2021-03-11T15:31:55.1679794Z time="2021-03-11T15:31:46Z" level=error msg="Recovered from panic" namespace=my-ns r="&{0xc000146000 map[fromPhase:Error namespace:my-ns toPhase:Succeeded workflow:my-wf] 2021-03-11 15:31:46.774305556 +0000 UTC m=+39.104786916 panic <nil> workflow is already fulfilled <nil> <nil> }" stack="goroutine 7777 [running]:\nruntime/debug.Stack(0xc04f6330ac, 0x1d7ef60, 0xc000275730)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc0003f9e40, 0x207d340, 0xc00011c010)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:181 +0xd1\npanic(0x1d7ef60, 0xc000275730)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:975 +0x47a\ngithub.com/sirupsen/logrus.Entry.log(0xc000146000, 0xc0014def00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345\ngithub.com/sirupsen/logrus.(*Entry).Log(0xc000275650, 0x0, 0xc000b775a0, 0x1, 0x1)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0\ngithub.com/sirupsen/logrus.(*Entry).Panic(0xc000275650, 0xc000b775a0, 0x1, 0x1)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:325 +0x55\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowPhase(0xc0003f9e40, 0x207d340, 0xc00011c010, 0x1db9363, 0x9, 0x0, 0x0)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:1859 +0x2bd\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowSuccess(...)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:1970\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc0003f9e40, 0x207d340, 0xc00011c010)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:434 +0x2906\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.TestResubmitPendingPods(0xc001149380)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator_test.go:5477 +0x575\ntesting.tRunner(0xc001149380, 0x1eb7418)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0xef\ncreated by testing.(*T).Run\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1168 +0x2b3\n" workflow=my-wf
2021-03-11T15:31:55.1691125Z time="2021-03-11T15:31:46Z" level=info msg="Updated message Unexpected pod phase for my-wf:  -> &{0xc000146000 map[fromPhase:Error namespace:my-ns toPhase:Succeeded workflow:my-wf] 2021-03-11 15:31:46.774305556 +0000 UTC m=+39.104786916 panic <nil> workflow is already fulfilled <nil> <nil> }" namespace=my-ns workflow=my-wf
2021-03-11T15:31:55.1693048Z time="2021-03-11T15:31:46Z" level=info msg="Checking daemoned children of " namespace=my-ns workflow=my-wf
2021-03-11T15:31:55.1694514Z time="2021-03-11T15:31:46Z" level=info msg="Workflow update successful" namespace=my-ns phase=Error resourceVersion= workflow=my-wf
2021-03-11T15:31:55.1695420Z     operator_test.go:5479: 
2021-03-11T15:31:55.1695960Z         	Error Trace:	operator_test.go:5479
2021-03-11T15:31:55.1696493Z         	Error:      	Not equal: 
2021-03-11T15:31:55.1697024Z         	            	expected: "Succeeded"
2021-03-11T15:31:55.1697554Z         	            	actual  : "Error"
2021-03-11T15:31:55.1697965Z         	            	
2021-03-11T15:31:55.1698358Z         	            	Diff:
2021-03-11T15:31:55.1698944Z         	            	--- Expected
2021-03-11T15:31:55.1699387Z         	            	+++ Actual
2021-03-11T15:31:55.1699955Z         	            	@@ -1,2 +1,2 @@
2021-03-11T15:31:55.1700767Z         	            	-(v1alpha1.WorkflowPhase) (len=9) "Succeeded"
2021-03-11T15:31:55.1701660Z         	            	+(v1alpha1.WorkflowPhase) (len=5) "Error"
2021-03-11T15:31:55.1702238Z         	            	 
```

**Comment by alexec** [comment]
Close?
