### ISSUE TITLE
Metrics panic

### ISSUE THREAD

**Issue by simster7** [argoproj/argo-workflows#5392]
```
 controller | time="2021-03-13T17:09:46.486Z" level=info msg="stopped leading" id=local
 controller | panic: http: Server closed
 controller | goroutine 77 [running]:
 controller | github.com/argoproj/argo-workflows/v3/workflow/metrics.runServer.func1(0x1, 0xc0006b11a8, 0x8, 0x2382, 0x0, 0x0, 0xc0002461c0)
 controller | 	/Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/workflow/metrics/server.go:53 +0x117
 controller | created by github.com/argoproj/argo-workflows/v3/workflow/metrics.runServer
 controller | 	/Users/sbeharyutk/go/src/github.com/argoproj/argo-workflows/workflow/metrics/server.go:50 +0x25f
 controller | Terminating controller
```

`commit fcb098995e4703028e09e580cb3909986a65a595`

**Comment by simster7** [comment]
```
ontroller | E0313 17:19:38.165472   32888 leaderelection.go:325] error retrieving resource lock argo/workflow-controller: Get https://0.0.0.0:55026/apis/coordination.k8s.io/v1/namespaces/argo/leases/workflow-controller: context deadline exceeded
 controller | I0313 17:19:38.165514   32888 leaderelection.go:278] failed to renew lease argo/workflow-controller: timed out waiting for the condition
 controller | E0313 17:19:38.165570   32888 leaderelection.go:301] Failed to release lock: resource name may not be empty
 controller | E0313 17:19:38.165584   32888 event.go:273] Unable to write event: 'can't create an event with namespace 'default' in namespace 'argo'' (may retry after sleeping)
 controller | time="2021-03-13T17:19:38.165Z" level=debug msg="Event(v1.ObjectReference{Kind:\"Lease\", Namespace:\"\", Name:\"\", UID:\"\", APIVersion:\"coordination.k8s.io/v1\", ResourceVersion:\"\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' local stopped leading"
 controller | time="2021-03-13T17:19:38.165Z" level=info msg="Shutting workflow TTL worker"
 controller | time="2021-03-13T17:19:38.165Z" level=info msg="stopped leading" id=local
```

**Comment by simster7** [comment]
@sarabala1979 I see some `leaderelection` in the logs. Review?

**Comment by alexec** [comment]
I think this is just the process being killed as I've seen it. We can leave this.
