### ISSUE TITLE
`TestResubmitPendingPods` occasionally panics and fails

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#5855]
```
time="2021-05-06T21:19:55Z" level=error msg="Recovered from panic" namespace=my-ns r="&{0xc0000ea000 map[fromPhase:Error namespace:my-ns toPhase:Succeeded workflow:my-wf] 2021-05-06 21:19:55.197053876 +0000 UTC m=+40.052239924 panic <nil> workflow is already fulfilled <nil> <nil> }" stack="goroutine 8110 [running]:\nruntime/debug.Stack(0xc0eb85ab28, 0x1da5060, 0xc001166000)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc001030630, 0x20acac0, 0xc0000c8010)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:182 +0xf1\npanic(0x1da5060, 0xc001166000)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:975 +0x47a\ngithub.com/sirupsen/logrus.Entry.log(0xc0000ea000, 0xc00131bc50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345\ngithub.com/sirupsen/logrus.(*Entry).Log(0xc000fd1f80, 0x0, 0xc001029698, 0x1, 0x1)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0\ngithub.com/sirupsen/logrus.(*Entry).Panic(0xc000fd1f80, 0xc001029698, 0x1, 0x1)\n\t/home/runner/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:325 +0x55\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowPhase(0xc001030630, 0x20acac0, 0xc0000c8010, 0x1ddf59b, 0x9, 0x0, 0x0)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:1836 +0x2dd\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).markWorkflowSuccess(...)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:1947\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc001030630, 0x20acac0, 0xc0000c8010)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator.go:417 +0x2b65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.TestResubmitPendingPods(0xc000bbed80)\n\t/home/runner/work/argo-workflows/argo-workflows/workflow/controller/operator_test.go:5590 +0x4f3\ntesting.tRunner(0xc000bbed80, 0x1ee3850)\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0xef\ncreated by testing.(*T).Run\n\t/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1168 +0x2b3\n" workflow=my-wf
time="2021-05-06T21:19:55Z" level=info msg="Updated message Unexpected pod phase for my-wf:  -> &{0xc0000ea000 map[fromPhase:Error namespace:my-ns toPhase:Succeeded workflow:my-wf] 2021-05-06 21:19:55.197053876 +0000 UTC m=+40.052239924 panic <nil> workflow is already fulfilled <nil> <nil> }" namespace=my-ns workflow=my-wf
time="2021-05-06T21:19:55Z" level=info msg="Checking daemoned children of " namespace=my-ns workflow=my-wf
time="2021-05-06T21:19:55Z" level=info msg="Workflow update successful" namespace=my-ns phase=Error resourceVersion= workflow=my-wf
--- FAIL: TestResubmitPendingPods (0.11s)
    operator_test.go:5582: 
        	Error Trace:	operator_test.go:5582
        	Error:      	Not equal: 
        	            	expected: "Running"
        	            	actual  : "Error"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.WorkflowPhase) (len=7) "Running"
        	            	+(v1alpha1.WorkflowPhase) (len=5) "Error"
        	            	 
        	Test:       	TestResubmitPendingPods
    operator_test.go:5583: 
        	Error Trace:	operator_test.go:5583
        	Error:      	Should be true
        	Test:       	TestResubmitPendingPods
    operator_test.go:5592: 
        	Error Trace:	operator_test.go:5592
        	Error:      	Not equal: 
        	            	expected: "Succeeded"
        	            	actual  : "Error"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(v1alpha1.WorkflowPhase) (len=9) "Succeeded"
        	            	+(v1alpha1.WorkflowPhase) (len=5) "Error"
        	            	 
        	Test:       	TestResubmitPendingPods
```

**Comment by alexec** [comment]
Unable to repro.
