### ISSUE TITLE
Missing file for global output param crashes controller (3.1.0-rc3)

### ISSUE THREAD

**Issue by crenshaw-dev** [argoproj/argo-workflows#5912]
## Summary 

What happened/what you expected to happen?

I expected a missing file for a global output param to cause the Workflow to fail, not the workflow-controller. The workflow only fails if I specify a `globalName`.

At first, I thought it might be the same issue as https://github.com/argoproj/argo-workflows/issues/5843, but I can't reproduce the issue in either 3.0.2 or 3.0.4.

## Diagnostics

What Kubernetes provider are you using? 

docker-desktop (but similar issue seen in AWS)

What version of Argo Workflows are you running? 

3.1.0-rc3

Original Workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: output-parameter-fail
spec:
  entrypoint: output-parameter
  templates:
    - name: output-parameter
      steps:
        - - name: generate-parameter
            template: whalesay
        - - name: consume-parameter
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "{{steps.generate-parameter.outputs.parameters.hello-param}}"

    - name: whalesay
      script:
        image: docker/whalesay:latest
        command: [sh]
        source: |
          sleep 1;
      outputs:
        parameters:
          - name: hello-param
            valueFrom:
              path: /tmp/hello_world.txt
            globalName: global-hello-param

    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

```

Workflow from cluster:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Workflow","metadata":{"annotations":{},"name":"output-parameter-fail","namespace":"default"},"spec":{"entrypoint":"output-parameter","templates":[{"name":"output-parameter","steps":[[{"name":"generate-parameter","template":"whalesay"}],[{"arguments":{"parameters":[{"name":"message","value":"{{steps.generate-parameter.outputs.parameters.hello-param}}"}]},"name":"consume-parameter","template":"print-message"}]]},{"name":"whalesay","outputs":{"parameters":[{"globalName":"global-hello-param","name":"hello-param","valueFrom":{"path":"/tmp/hello_world.txt"}}]},"script":{"command":["sh"],"image":"docker/whalesay:latest","source":"sleep 1;\n"}},{"container":{"args":["{{inputs.parameters.message}}"],"command":["cowsay"],"image":"docker/whalesay:latest"},"inputs":{"parameters":[{"name":"message"}]},"name":"print-message"}]}}
  creationTimestamp: "2021-05-14T15:41:05Z"
  generation: 2
  labels:
    workflows.argoproj.io/phase: Running
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:entrypoint: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-05-14T15:41:05Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:workflows.argoproj.io/phase: {}
      f:spec:
        f:arguments: {}
        f:templates: {}
      f:status:
        .: {}
        f:artifactRepositoryRef: {}
        f:finishedAt: {}
        f:nodes: {}
        f:phase: {}
        f:progress: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2021-05-14T15:41:05Z"
  name: output-parameter-fail
  namespace: default
  resourceVersion: "5093819"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/output-parameter-fail
  uid: 166d1165-0edf-4cee-9401-333f55678ba7
spec:
  arguments: {}
  entrypoint: output-parameter
  templates:
  - inputs: {}
    metadata: {}
    name: output-parameter
    outputs: {}
    steps:
    - - arguments: {}
        name: generate-parameter
        template: whalesay
    - - arguments:
          parameters:
          - name: message
            value: '{{steps.generate-parameter.outputs.parameters.hello-param}}'
        name: consume-parameter
        template: print-message
  - inputs: {}
    metadata: {}
    name: whalesay
    outputs:
      parameters:
      - globalName: global-hello-param
        name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
    script:
      command:
      - sh
      image: docker/whalesay:latest
      name: ""
      resources: {}
      source: |
        sleep 1;
  - container:
      args:
      - '{{inputs.parameters.message}}'
      command:
      - cowsay
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: message
    metadata: {}
    name: print-message
    outputs: {}
status:
  artifactRepositoryRef:
    default: true
  finishedAt: null
  nodes:
    output-parameter-fail:
      children:
      - output-parameter-fail-3849320361
      displayName: output-parameter-fail
      finishedAt: null
      id: output-parameter-fail
      name: output-parameter-fail
      phase: Running
      progress: 0/1
      startedAt: "2021-05-14T15:41:05Z"
      templateName: output-parameter
      templateScope: local/output-parameter-fail
      type: Steps
    output-parameter-fail-3849320361:
      boundaryID: output-parameter-fail
      children:
      - output-parameter-fail-4178428376
      displayName: '[0]'
      finishedAt: null
      id: output-parameter-fail-3849320361
      name: output-parameter-fail[0]
      phase: Running
      progress: 0/1
      startedAt: "2021-05-14T15:41:05Z"
      templateScope: local/output-parameter-fail
      type: StepGroup
    output-parameter-fail-4178428376:
      boundaryID: output-parameter-fail
      displayName: generate-parameter
      finishedAt: null
      id: output-parameter-fail-4178428376
      name: output-parameter-fail[0].generate-parameter
      phase: Pending
      progress: 0/1
      startedAt: "2021-05-14T15:41:05Z"
      templateName: whalesay
      templateScope: local/output-parameter-fail
      type: Pod
  phase: Running
  progress: 0/1
  startedAt: "2021-05-14T15:41:05Z"
```

Controller logs:

```
time="2021-05-14T15:41:33.895Z" level=info msg="Pod failed: Error (exit code 1): Error: No such container:path: b88e5455a386129790a819cb35b61da9ec9e9eaca962eee7c1faa2bf9399309d:/tmp/hello_world.txt\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors" displayName=generate-parameter namespace=default pod=output-parameter-fail-4178428376 templateName=whalesay workflow=output-parameter-fail
time="2021-05-14T15:41:33.897Z" level=info msg="Updating node output-parameter-fail-4178428376 exit code 0" namespace=default workflow=output-parameter-fail
time="2021-05-14T15:41:33.897Z" level=info msg="Setting node output-parameter-fail-4178428376 outputs: {\"parameters\":[{\"name\":\"hello-param\",\"valueFrom\":{\"path\":\"/tmp/hello_world.txt\"},\"globalName\":\"global-hello-param\"}]}" namespace=default workflow=output-parameter-fail
time="2021-05-14T15:41:33.897Z" level=info msg="Updating node output-parameter-fail-4178428376 status Pending -> Error" namespace=default workflow=output-parameter-fail
time="2021-05-14T15:41:33.897Z" level=info msg="Updating node output-parameter-fail-4178428376 message: Error (exit code 1): Error: No such container:path: b88e5455a386129790a819cb35b61da9ec9e9eaca962eee7c1faa2bf9399309d:/tmp/hello_world.txt\ntar: This does not look like a tar archive\ntar: Exiting with failure status due to previous errors" namespace=default workflow=output-parameter-fail
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a76851]

goroutine 241 [running]:
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).addParamToGlobalScope(0xc0005f48f0, 0xc000645d30, 0xb, 0x0, 0x0, 0xc00026d180, 0xc0006399e0, 0x12, 0x0, 0x0, ...)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2613 +0xd1
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).addOutputsToGlobalScope(0xc0005f48f0, 0xc000782980)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2512 +0x118
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func1(0xc000100800)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:884 +0xc91
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc000645c80, 0xc00084e230, 0xc0005f48f0, 0x2170a80, 0xc000196000, 0xc0006397e0, 0xc000841b90, 0xc00008b5c0, 0xc000100800)
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:935 +0x62
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation
        /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:933 +0x305
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@mac9416 is it happening in v3.0 also?

**Comment by mac9416** [comment]
@sarabala1979 no, it is not happening in 3.0.2 or 3.0.4. So should probably be on the v3.1 milestone?
