### ISSUE TITLE
sync.(*Manager).ReleaseAll: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by whyvez** [argoproj/argo-workflows#5939]
## Summary 

I'm not sure what caused this but I started getting these errors this morning and Argo is completely down.  Looks like it's related to a lock. I am using a template level lock. I tried removing all CMs mentioning the lock key but no luck. Everything was working fine this morning. The only event that I can think of that happen this morning is a GKE update but pretty sure things were working fine after.

## Diagnostics

What Kubernetes provider are you using? `GKE -> v1.19.9-gke.1400`

What version of Argo Workflows are you running?  `3.0.4`

Example template using synchronization.

```yaml
- name: save-es-raw
  synchronization:
    semaphore:
      configMapKeyRef:
        name: config-revere
        key: REVERE_SAVE_ES_CONCURRENCY
  inputs:
    parameters: &commonInputParams
      - name: form
      - name: question
      - name: uuid
      - name: size
    artifacts: &rawArtifact
      - name: raw
        path: /tmp/raw.ldjson
        gcs:
          bucket: revere-artifacts
          key: "{{inputs.parameters.uuid}}_raw.ldjson.tgz"
  podSpecPatch: *podSpecPatch
  container:
    image: revere
    imagePullPolicy: Always
    command: ["python", "./bin/{{workflow.parameters.action}}_sentiment_question.py"]
    args: ["--save_es_raw", "--data", "/tmp/raw.ldjson"]
    env: *env
    envFrom: *envFrom
```

```
E0518 17:00:18.736170       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 170 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b6eb00, 0x2c9aa80)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1b6eb00, 0x2c9aa80)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c99ab0, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b6eb00, 0x2c9aa80)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc001c37950, 0xc001bc8400, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:551 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001a6a80, 0x206c3e0, 0xc00012a000, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:648 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001a6a80)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:573 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d68920)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d68920, 0x2021920, 0xc0007ee750, 0x1, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d68920, 0x3b9aca00, 0x0, 0x1, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000d68920, 0x3b9aca00, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:285 +0x48a
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1960f2e]

goroutine 170 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b6eb00, 0x2c9aa80)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c99ab0, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b6eb00, 0x2c9aa80)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc001c37950, 0xc001bc8400, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:551 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000657ef0, 0x206c3e0, 0xc00012a000)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001a6a80, 0x206c3e0, 0xc00012a000, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:648 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001a6a80)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:573 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d68920)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d68920, 0x2021920, 0xc0007ee750, 0x1, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d68920, 0x3b9aca00, 0x0, 0x1, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000d68920, 0x3b9aca00, 0xc00249c6c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:285 +0x48a
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by whyvez** [comment]
I'm not sure how to get out of this bad state. I uninstalled/reinstalled Argo, deleted all references of the semaphore but as soon as the controller starts it gets into a `CrashLoopBackOff` with the error above.

**Comment by alexec** [comment]
https://github.com/argoproj/argo-workflows/blob/v3.0.4/workflow/sync/sync_manager.go#L262

The variable `lock` must be nil on this line.

**Comment by whyvez** [comment]
I was able to fix this. I renamed the semaphore key but there were some running workflows using the semaphore. As soon as I suspended the cron of the workflow in question and deleted all related workflows the controller started without error. 

Where is the lock info/state persisted?

**Comment by alexec** [comment]
@sarabala1979 ?
