### ISSUE TITLE
panic in argo server when artifact name unknown

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#6024]
We should try to never panic, as this can crashes the application:
 
```
time="2021-05-26T09:47:03.606Z" level=info msg="Download artifact" artifactName=main-logs isInput=true namespace=argo nodeId=terraform-tsvg5-3595155252 workflowName=terraform-tsvg5
2021/05/26 09:47:03 http: panic serving 100.96.15.6:41622: runtime error: invalid memory address or nil pointer dereference
goroutine 2284 [running]:
net/http.(*conn).serve.func1(0xc0006f6fa0)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x2315e20, 0x43a8770)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.(*Inputs).GetArtifactByName(...)
	/go/src/github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/workflow_types.go:2473
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).returnArtifact(0xc00020e300, 0x3407100, 0xc000d5cab0, 0x33fe5c0, 0xc0007947e0, 0xc000ec2500, 0xc0001f1c00, 0xc00061098a, 0x1a, 0xc0006109a5, ...)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:148 +0x118
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).getArtifact(0xc00020e300, 0x33fe5c0, 0xc0007947e0, 0xc000ec2500, 0x1)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:76 +0x5b1
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).GetInputArtifact(...)
	/go/src/github.com/argoproj/argo-workflows/server/artifacts/artifact_server.go:51
net/http.HandlerFunc.ServeHTTP(0xc000923910, 0x33fe5c0, 0xc0007947e0, 0xc000ec2500)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000920a40, 0x33fe5c0, 0xc0007947e0, 0xc000ec2500)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000794000, 0x33fe5c0, 0xc0007947e0, 0xc000ec2500)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0006f6fa0, 0x3407040, 0xc0005f43c0)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c
```

@dinever would you like to own this?

Just add some nil checks:

```golang
func (in *Inputs) GetArtifactByName(name string) *Artifact {
    if in == nil {return nil}
	return in.Artifacts.GetArtifactByName(name)
}
```

and also

```golang
func (a Artifacts) GetArtifactByName(name string) *Artifact {
    if a==nil{return nil}
	for _, art := range a {
		if art.Name == name {
			return &art
		}
	}
	return nil
}
```

**Comment by dinever** [comment]
Yep, I can take this. Thanks for creating!
