### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by whyvez** [argoproj/argo-workflows#6224]
## Summary 

I've already reported a similar problem [here](https://github.com/argoproj/argo-workflows/issues/5939).  I've updated to 3.0.8 but the problem persists. My problematic workflow is the same as I had reported in the original issue. The error brought down the controller and all other workflows I had scheduled/running. I was able to bring things back up by suspending all cron workflows which reference this lock and delete a running workflow.

## Diagnostics

What Kubernetes provider are you using? `GKE (1.19.9-gke.1900)`

What version of Argo Workflows are you running?  `v3.0.8`

What executor are you running? `PNS`

```
...
time="2021-06-24T21:13:45.011Z" level=info msg="Checking daemoned children of revere-by-minute-loads-1624466940" namespace=stable workflow=revere-by-minute-loads-1624466940
time="2021-06-24T21:13:45.011Z" level=info msg="Updated phase Running -> Succeeded" namespace=stable workflow=revere-by-minute-loads-1624466940
time="2021-06-24T21:13:45.011Z" level=info msg="Marking workflow completed" namespace=stable workflow=revere-by-minute-loads-1624466940
time="2021-06-24T21:13:45.011Z" level=info msg="Checking daemoned children of " namespace=stable workflow=revere-by-minute-loads-1624466940
E0624 21:13:45.013543       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 177 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b70a40, 0x2c9da90)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c9cab8, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc00a4e9c50, 0xc00acad800, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:553 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001e3180, 0x206e700, 0xc000058010, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:674 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001e3180)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00a754590)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a754590, 0x2023bc0, 0xc00a75e240, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a754590, 0x3b9aca00, 0x0, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00a754590, 0x3b9aca00, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:289 +0x48a
E0624 21:13:45.013733       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 177 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b70a40, 0x2c9da90)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c9cab8, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:51 +0xce
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc00a4e9c50, 0xc00acad800, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:553 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001e3180, 0x206e700, 0xc000058010, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:674 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001e3180)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00a754590)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a754590, 0x2023bc0, 0xc00a75e240, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a754590, 0x3b9aca00, 0x0, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00a754590, 0x3b9aca00, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:289 +0x48a
E0624 21:13:45.013873       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 177 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b70a40, 0x2c9da90)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c9cab8, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc00a4e9c50, 0xc00acad800, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:553 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001e3180, 0x206e700, 0xc000058010, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:674 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001e3180)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00a754590)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a754590, 0x2023bc0, 0xc00a75e240, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a754590, 0x3b9aca00, 0x0, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00a754590, 0x3b9aca00, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:289 +0x48a
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x196168e]

goroutine 177 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x2c9cab8, 0x1, 0x1)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1b70a40, 0x2c9da90)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).ReleaseAll(0xc00a4e9c50, 0xc00acad800, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:262 +0x64e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).persistUpdates(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:553 +0xd6d
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func1(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:177 +0xd2
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc00adf4420, 0x206e700, 0xc000058010)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:461 +0x25ef
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc0001e3180, 0x206e700, 0xc000058010, 0x0)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:674 +0x7f0
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc0001e3180)
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00a754590)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00a754590, 0x2023bc0, 0xc00a75e240, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00a754590, 0x3b9aca00, 0x0, 0x1, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc00a754590, 0x3b9aca00, 0xc00a7086c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
	/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:289 +0x48a
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritize the issues with the most 👍.

**Comment by whyvez** [comment]
@alexec Is there something I can do in the meantime to re-instate the workflow with the lock? Where is the lock persisted and what might be the best means of resetting?

**Comment by whyvez** [comment]
I've renamed the `synchronization.semaphore.configMapKeyRef.key` at that fixed it for now, but I'd like to get to the bottom of this. This has happened twice so far and it will likely happen again. Please let me know what I can do to help troubleshoot. 🙏🏻

**Comment by sarabala1979** [comment]
Can you try with v3.1?
