### ISSUE TITLE
Workflow Controller panic on addParamToGlobalScope 

### ISSUE THREAD

**Issue by blkperl** [argoproj/argo-workflows#6478]
## Summary 

The workflow operator panic'd

## Diagnostics

What Kubernetes provider are you using? 

EKS 1.19

What version of Argo Workflows are you running? 

3.1.2

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Not sure

Did this work in a previous version? I.e. is it a regression?

Might be a regression. Looks similar to some bugs https://github.com/argoproj/argo-workflows/issues?q=is%3Aissue+AddParamToGlobalScope+is%3Aclosed

```bash
workflow-controller-744d84ff5c-4wwnt workflow-controller time="2021-07-30T07:49:35.494Z" level=info msg="Get workflowtemplates 200"
workflow-controller-744d84ff5c-4wwnt workflow-controller panic: runtime error: invalid memory address or nil pointer dereference
workflow-controller-744d84ff5c-4wwnt workflow-controller [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a0ebf8]
workflow-controller-744d84ff5c-4wwnt workflow-controller 
workflow-controller-744d84ff5c-4wwnt workflow-controller goroutine 308 [running]:
workflow-controller-744d84ff5c-4wwnt workflow-controller github.com/argoproj/argo-workflows/v3/workflow/util.AddParamToGlobalScope(0xc004454800, 0xc00446a620, 0xc0044d7b38, 0x8, 0x0, 0x0, 0xc005031ce0, 0xc0044d7b50, 0xc, 0x0, ...)
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/util/util.go:477 +0x1d8
workflow-controller-744d84ff5c-4wwnt workflow-controller github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).addParamToGlobalScope(0xc0044648f0, 0xc0044d7b38, 0x8, 0x0, 0x0, 0xc005031ce0, 0xc0044d7b50, 0xc, 0x0, 0x0, ...)
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2624 +0x178
workflow-controller-744d84ff5c-4wwnt workflow-controller github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).addOutputsToGlobalScope(0xc0044648f0, 0xc002c4fc40)
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2520 +0x118
workflow-controller-744d84ff5c-4wwnt workflow-controller github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func1(0xc00170afc8)
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:887 +0xc91
workflow-controller-744d84ff5c-4wwnt workflow-controller github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation.func2(0xc0044d7ac0, 0xc003f29bd0, 0xc0044648f0, 0x2182d60, 0xc000198000, 0xc0046861e0, 0xc0046881f0, 0xc003f35d40, 0xc00170afc8)
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:938 +0x62
workflow-controller-744d84ff5c-4wwnt workflow-controller created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).podReconciliation
workflow-controller-744d84ff5c-4wwnt workflow-controller 	/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:936 +0x305
```

We can provide the workflow template if needed, it's just rather large and will need to be manually scrubbed first. 

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
#5931 was included in v3.1, so this is a new bug.

**Comment by alexec** [comment]
Caused by fix(conttroller): Always set finishedAt dote. Fixes #6135 (#6139)

**Comment by alexec** [comment]
Not sure what is going on here. For a nil panic, there must be a variable that could be nil on line 477

```
if prevVal == nil || *prevVal != *param.Value {
```

It must be `param.Value` that is nil.

So that expression should be:

```
if prevVal == nil || (param.Value != nil && *prevVal != *param.Value) {
```

@blkperl would you like to submit a PR to fix?

**Comment by blkperl** [comment]
@alexec PR submitted
