### ISSUE TITLE
Invalid memory address or nil pointer reference when using mutex with cache 

### ISSUE THREAD

**Issue by thatGreekGuy96** [argoproj/argo-workflows#6607]
## Summary 

I'm getting an invalid memory address error when trying to submit a workflow the uses both a `mutex` with a parametrised name and a `memoize` cache. 

The issue occurs only after the workflow has been run at least once (and the cache has been activated). 
The issue does not occur at all if the name of the `mutex` field is static. 
The issue also does not occur if the name of the `mutex` is a only a parameter, and not a static string + parameter.

## Diagnostics

👀 Yes! We need all of your diagnostics, please make sure you add it all, otherwise we'll go around in circles asking you for it:

What Kubernetes provider are you using? 
EKS

What version of Argo Workflows are you running? 
`v3.1.3`
I tried upgrading to the latest argo version (`3.1.8`) but it did not make a difference. 

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Did this work in a previous version? I.e. is it a regression?
I doubt it's a regression since I've tried it on two versions now and it does not work. 

Are you pasting thousands of log lines? That's too much information. 

Here is the workflow file that is causing the problem. You need to run it once and make sure that the cache has been used. It will then failed in subsequent runs. 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: sleep-then-hello
  arguments:
    parameters:
    - name: key
      value: test11
  templates:
  - name: sleep-then-hello
    steps:
    - - name: sleep
        template: sleep
    - - name: hello
        template: hello
  - name: sleep
    memoize:
      key: "{{workflow.parameters.key}}"
      maxAge: "10h"
      cache:
        configMap:
          name: my-config
          key: cache-test
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        echo "sleeping for 10 seconds"
        sleep 10
        echo "im in ur container, running ur code"
    synchronization:
      mutex:
        name: "test-{{workflow.parameters.key}}"
  - name: hello
    script:
      image: alpine:3.6
      command: [sh]
      source: |
        echo "im in ur container, running ur code"
```

Changing the name of either of the two options below fixes the issue:
```yaml
mutex:
  name: "test"
```

```yaml
mutex:
  name: "{{workflow.parameters.key}}"
```

Both of the above changes resolve the issue.

Here's the status of the workflow 
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
  creationTimestamp: "2021-08-26T09:23:56Z"
  generateName: hello-world-
  generation: 2
  labels:
    workflows.argoproj.io/archive-strategy: "false"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: hello-world-qqvw8
  namespace: user-andy
  resourceVersion: "129237828"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/user-andy/workflows/hello-world-qqvw8
  uid: 047b9ad2-1fb1-4916-853b-8cc513b04f77
spec:
  arguments:
    parameters:
    - name: key
      value: test10
  entrypoint: sleep-then-hello
  serviceAccountName: argo-workflow
  templates:
  - inputs: {}
    metadata: {}
    name: sleep-then-hello
    outputs: {}
    steps:
    - - arguments: {}
        name: sleep
        template: sleep
    - - arguments: {}
        name: hello
        template: hello
  - inputs: {}
    memoize:
      cache:
        configMap:
          key: cache-test
          name: my-config
      key: '{{workflow.parameters.key}}'
      maxAge: 10h
    metadata: {}
    name: sleep
    outputs: {}
    script:
      command:
      - sh
      image: alpine:3.6
      name: ""
      resources: {}
      source: |
        echo "sleeping for 10 seconds"
        sleep 10
        echo "im in ur container, running ur code"
    synchronization:
      mutex:
        name: test-{{workflow.parameters.key}}
  - inputs: {}
    metadata: {}
    name: hello
    outputs: {}
    script:
      command:
      - sh
      image: alpine:3.6
      name: ""
      resources: {}
      source: |
        echo "im in ur container, running ur code"
status:
  artifactRepositoryRef:
    artifactRepository:
      s3:
        accessKeySecret:
          key: accesskey
          name: argo-artifact-bucket-credentials
        bucket: ci-argo-artifact-store-dev
        endpoint: s3.amazonaws.com
        insecure: true
        secretKeySecret:
          key: secretkey
          name: argo-artifact-bucket-credentials
    configMap: artifact-repositories
    key: default-v1
    namespace: user-andy
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-08-26T09:23:56Z"
  message: 'runtime error: invalid memory address or nil pointer dereference'
  nodes:
    hello-world-qqvw8:
      children:
      - hello-world-qqvw8-1817220546
      displayName: hello-world-qqvw8
      finishedAt: null
      id: hello-world-qqvw8
      message: Workflow operation error
      name: hello-world-qqvw8
      phase: Error
      startedAt: "2021-08-26T09:23:56Z"
      templateName: sleep-then-hello
      templateScope: local/hello-world-qqvw8
      type: Steps
    hello-world-qqvw8-828097543:
      boundaryID: hello-world-qqvw8
      displayName: sleep
      finishedAt: "2021-08-26T09:23:56Z"
      id: hello-world-qqvw8-828097543
      memoizationStatus:
        cacheName: my-config
        hit: true
        key: test10
      name: hello-world-qqvw8[0].sleep
      outputs:
        exitCode: "0"
      phase: Succeeded
      progress: 1/1
      startedAt: "2021-08-26T09:23:56Z"
      templateName: sleep
      templateScope: local/hello-world-qqvw8
      type: Pod
    hello-world-qqvw8-1817220546:
      boundaryID: hello-world-qqvw8
      displayName: '[0]'
      finishedAt: null
      id: hello-world-qqvw8-1817220546
      name: hello-world-qqvw8[0]
      phase: Running
      startedAt: "2021-08-26T09:23:56Z"
      templateScope: local/hello-world-qqvw8
      type: StepGroup
  phase: Error
  progress: 1/1
  startedAt: "2021-08-26T09:23:56Z"
```

# Logs from the workflow controller:
```bash
time="2021-08-26T09:23:56.533Z" level=info msg="Processing workflow" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.540Z" level=info msg="Updated phase  -> Running" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.540Z" level=info msg="Steps node hello-world-qqvw8 initialized Running" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.540Z" level=info msg="StepGroup node hello-world-qqvw8-1817220546 initialized Running" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=info msg="Pod node hello-world-qqvw8-828097543 initialized Pending" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=error msg="Recovered from panic" namespace=user-andy r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 209 [running]:\nruntime/debug.Stack(0xc0055e6653, 0x1c53200, 0x2e15840)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc000c24c60, 0x2183060, 0xc00005a010)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:183 +0xd1\npanic(0x1c53200, 0x2e15840)\n\t/usr/local/go/src/runtime/panic.go:975 +0x47a\ngithub.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1.(*SynchronizationStatus).GetStatus(...)\n\t/go/src/github.com/argoproj/argo-workflows/pkg/apis/workflow/v1alpha1/workflow_types.go:3037\ngithub.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).Release(0xc000ecef30, 0xc000c09400, 0xc000da9ca0, 0x1b, 0xc000a581f0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:195 +0x310\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000c24c60, 0x2183060, 0xc00005a010, 0xc000da9320, 0x1a, 0x21437a0, 0xc00095b5c0, 0xc0011de680, 0x0, 0x0, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1582 +0x518\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc000c24c60, 0x2183060, 0xc00005a010, 0xc00095b500, 0x1, 0x4, 0xc000da90e0, 0x14, 0xc001106450, 0xc000da86a0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:235 +0x1295\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc000c24c60, 0x2183060, 0xc00005a010, 0xc000da86a0, 0x11, 0xc0011de680, 0xc000da8ea0, 0x17, 0xc00113afc0, 0x21437a0, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:92 +0x475\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000c24c60, 0x2183060, 0xc00005a010, 0xc000da86a0, 0x11, 0x21437a0, 0xc00095aa80, 0xc0011de640, 0xc000c709b0, 0x1, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1726 +0x2338\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000c24c60, 0x2183060, 0xc00005a010)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:331 +0xf05\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc00006f800, 0x2183060, 0xc00005a010, 0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:727 +0x7fb\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc00006f800)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:648 +0x9b\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000a28d90)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:155 +0x5f\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000a28d90, 0x2135320, 0xc000de5a70, 0x1, 0xc00071d4a0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:156 +0xad\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000a28d90, 0x3b9aca00, 0x0, 0x1, 0xc00071d4a0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:133 +0x98\nk8s.io/apimachinery/pkg/util/wait.Until(0xc000a28d90, 0x3b9aca00, 0xc00071d4a0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.19.6/pkg/util/wait/wait.go:90 +0x4d\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:298 +0x48a\n" workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=info msg="Updated phase Running -> Error" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=info msg="Marking workflow completed" namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.557Z" level=info msg="Checking daemoned children of " namespace=user-andy workflow=hello-world-qqvw8
time="2021-08-26T09:23:56.570Z" level=info msg="Workflow update successful" namespace=user-andy phase=Error resourceVersion=129237828 workflow=hello-world-qqvw8
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@thatGreekGuy96  I couldn't reproduce in the latest. Can you try with 3.2-rc2 or v3.1.8?

**Comment by thatGreekGuy96** [comment]
> @thatGreekGuy96 Does Panic occurs first-time workflow submission or after memoize like 2nd or 3rd time of submission?

The panic occurs after the 2nd or 3rd submission, i.e. after the cache has been used.

**Comment by thatGreekGuy96** [comment]
> @thatGreekGuy96 I couldn't reproduce in the latest. Can you try with 3.2-rc2 or v3.1.8?

I tried with `3.1.8`, it didn't really make a difference but i can give it another try with version 3.2 to see if that solves it.
