### ISSUE TITLE
`argo node set` panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo-workflows#6648]
## Summary 

```
$ argo node set --help

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewNodeCommand.func1(0xc0000dedc0, 0xc0007df7e0, 0x1, 0x1)
	/private/tmp/argo-20210819-66832-1vv6wzp/cmd/argo/commands/node.go:81 +0x8f9
github.com/spf13/cobra.(*Command).execute(0xc0000dedc0, 0xc0007df7b0, 0x1, 0x1, 0xc0000dedc0, 0xc0007df7b0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000132dc0, 0xc000000180, 0xc0008bff78, 0x1007b45)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/argo-20210819-66832-1vv6wzp/cmd/argo/main.go:14 +0x2b
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by jessesuen** [comment]
Resolved in https://github.com/argoproj/argo-workflows/pull/6653
