### ISSUE TITLE
`argo auth token --verbose` segfaults

### ISSUE THREAD

**Issue by totycro** [argoproj/argo-workflows#7216]
## Summary

I'm probably experiencing #7175 . To confirm, I wanted to see what `argo auth token --verbose` would print, however it crashes with this: 

```
$ argo auth token --verbose
DEBU[2021-11-15T14:05:19.347Z] CLI version                                   version="{v3.2.3 2021-10-27T02:10:33Z e5dc961b7846efe0fe36ab3a0964180eaedd2672 v3.2.3 clean go1.16.9 gc linux/amd64}"
I1115 14:05:19.348479   67428 loader.go:372] Config loaded from file:  /home/mallinger/.kube/config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x61168a]

goroutine 1 [running]:
net/url.(*URL).String(0x0, 0xc00015c348, 0x0)
	/opt/hostedtoolcache/go/1.16.9/x64/src/net/url/url.go:813 +0x4a
k8s.io/client-go/transport.newRequestInfo(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.5/transport/round_trippers.go:323
k8s.io/client-go/transport.(*debuggingRoundTripper).RoundTrip(0xc0001173c8, 0xc0009ea800, 0xa, 0x2a243ae, 0x5)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.5/transport/round_trippers.go:429 +0x47
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc000403740, 0xc0009ea800, 0x2a2d657, 0xa, 0xc00062d688)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.21.5/transport/round_trippers.go:156 +0x286
github.com/argoproj/argo-workflows/v3/util/kubeconfig.userAgentRoundTripper.RoundTrip(0x2a243ae, 0x5, 0x3806000, 0xc000403740, 0xc0009ea800, 0x0, 0x2a29da8, 0x40df7b)
	/home/runner/work/argo-workflows/argo-workflows/util/kubeconfig/roundtripper.go:12 +0x109
github.com/argoproj/argo-workflows/v3/util/kubeconfig.GetBearerToken(0xc00012ab40, 0x0, 0x0, 0x455067, 0x0, 0xc000a3fbc8, 0x3)
	/home/runner/work/argo-workflows/argo-workflows/util/kubeconfig/kubeconfig.go:175 +0x42f
github.com/argoproj/argo-workflows/v3/util/kubeconfig.GetAuthString(0xc00012ab40, 0x0, 0x0, 0x2a2103e, 0x1, 0xc000458780, 0x1e)
	/home/runner/work/argo-workflows/argo-workflows/util/kubeconfig/kubeconfig.go:124 +0xde
github.com/argoproj/argo-workflows/v3/cmd/argo/commands/client.GetAuthString(0x37d09bc, 0x6)
	/home/runner/work/argo-workflows/argo-workflows/cmd/argo/commands/client/conn.go:102 +0x253
github.com/argoproj/argo-workflows/v3/cmd/argo/commands/auth.NewTokenCommand.func1(0xc000662c80, 0xc00092fc10, 0x0, 0x1)
	/home/runner/work/argo-workflows/argo-workflows/cmd/argo/commands/auth/token.go:21 +0x30
github.com/spf13/cobra.(*Command).execute(0xc000662c80, 0xc00092fc00, 0x1, 0x1, 0xc000662c80, 0xc00092fc00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009c4000, 0xc000084778, 0xc000a3ff78, 0x406365)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/runner/work/argo-workflows/argo-workflows/cmd/argo/main.go:14 +0x2b
```

Version:
```
$ argo version
argo: v3.2.3
  BuildDate: 2021-10-27T02:10:33Z
  GitCommit: e5dc961b7846efe0fe36ab3a0964180eaedd2672
  GitTreeState: clean
  GitTag: v3.2.3
  GoVersion: go1.16.9
  Compiler: gc
  Platform: linux/amd64
```

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```
argo auth token --verbose
```

What Kubernetes provider are you using?
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

None so far, i can't even access the UI

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by totycro** [comment]
I just tried this version and it printed the bearer token as expected, no segfault:

```
argo: v3.1.8
  BuildDate: 2021-08-19T00:06:02Z
  GitCommit: 0df0f3a98fac4e2aa5bc02213fb0a2ccce9a682a
  GitTreeState: clean
  GitTag: v3.1.8
  GoVersion: go1.15.7
  Compiler: gc
  Platform: linux/amd64
```

**Comment by totycro** [comment]
Thanks for the quick fix!
