### ISSUE TITLE
Submitting Cluster Workflow Template using namespaced install fails immediately with runtime error

### ISSUE THREAD

**Issue by tachyus-ryan** [argoproj/argo-workflows#7266]
## Summary

What happened/what you expected to happen?

I created a new cluster workflow template from the Argo UI. I then submitted that cluster workflow template from the UI with all default values. I expected the workflow to run successfully. Instead, the workflow failed immediately with `Error: runtime error: invalid memory address or nil pointer dereference`

What version of Argo Workflows are you running? v3.2.4 using namespaced-install

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2021-11-23T16:30:36Z"
  generateName: awesome-bear-
  generation: 4
  labels:
    example: "true"
    workflows.argoproj.io/cluster-workflow-template: awesome-bear
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: awesome-bear-d8fm2
  namespace: default
  resourceVersion: "67885927"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/awesome-bear-d8fm2
  uid: d659db1d-7072-4cbe-b98e-9dc0c3759f6f
spec:
  arguments: {}
  serviceAccountName: workflow
  workflowTemplateRef:
    clusterScope: true
    name: awesome-bear
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2021-11-23T16:30:55Z"
  message: 'runtime error: invalid memory address or nil pointer dereference'
  phase: Error
  progress: 0/0
  startedAt: "2021-11-23T16:30:55Z"
  storedTemplates:
    cluster/awesome-bear/argosay:
      container:
        args:
        - echo
        - '{{inputs.parameters.message}}'
        command:
        - /argosay
        image: argoproj/argosay:v2
        name: main
        resources: {}
      inputs:
        parameters:
        - name: message
          value: '{{workflow.parameters.message}}'
      metadata: {}
      name: argosay
      outputs: {}
```

What Kubernetes provider are you using? GKE

What executor are you running? K8SAPI

```bash
# Logs from the workflow controller:
kubectl logs deploy/workflow-controller | grep ${workflow}
```
```yaml
time="2021-11-23T16:30:36.285Z" level=info msg="Processing workflow" namespace=default workflow=awesome-bear-d8fm
time="2021-11-23T16:30:36.285Z" level=error msg="Recovered from panic" namespace=default r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 184 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:189 +0xd4\npanic({0x1dafc20, 0x352e0e0})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).fetchWorkflowSpec(0xc0004bce40)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3323 +0x48\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setStoredWfSpec(0xc0004bce40)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3430 +0x79\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setExecWorkflow(0xc0004bce40, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3342 +0x226\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc0004bce40, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:203 +0x17a\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000474000, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:767 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:689 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fc3ad78ab88)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x632e73726574656d, {0x23db660, 0xc000528360}, 0x1, 0xc0000e0360)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x225c2c7d7d225c7d, 0x3b9aca00, 0x0, 0x6d, 0x73225c2c225c656d)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x225c5b3a225c646e, 0x5c68732f6e69622f, 0x616d69225c2c5d22)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:318 +0x68d\n" workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:36.286Z" level=info msg="Updated phase  -> Error" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:36.286Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:36.286Z" level=info msg="Marking workflow completed" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:36.286Z" level=info msg="Checking daemoned children of " namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:36.312Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=67885764 workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.223Z" level=info msg="Processing workflow" namespace=default workflow=awesome-bear-d8fm
time="2021-11-23T16:30:55.224Z" level=error msg="Recovered from panic" namespace=default r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 185 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:189 +0xd4\npanic({0x1dafc20, 0x352e0e0})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).fetchWorkflowSpec(0xc0010e2180)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3323 +0x48\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setStoredWfSpec(0xc0010e2180)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3430 +0x79\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).setExecWorkflow(0xc0010e2180, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:3342 +0x226\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc0010e2180, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:203 +0x17a\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000474000, {0x241ef08, 0xc00005a018})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:767 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:689 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fc3ad5296d0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x7469726f676c6122, {0x23db660, 0xc0008f40f0}, 0x1, 0xc0000e0360)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0x67616d4973616164, 0x3b9aca00, 0x0, 0x7d, 0x22746e696f707972)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x682d74697865223a, 0x2c2272656c646e61, 0x7453797274657222)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:318 +0x68d\n" workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.224Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.224Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.224Z" level=info msg="Marking workflow completed" namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.224Z" level=info msg="Checking daemoned children of " namespace=default workflow=awesome-bear-d8fm2
time="2021-11-23T16:30:55.237Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=67885927 workflow=awesome-bear-d8fm2
```

```bash
# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```
```yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```bash
# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
No resources found in default namespace.
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
@tachyus-ryan Namespaced-install should not have `clusterworkflowtemplate` RBAC. can. you. please. provide your usecase for `clusterworkflowtemplate` for namespaced install? 

you should have clusterworkflowtemplatte RBAC on argo-role

**Comment by alexec** [comment]
I think that `(woc *wfOperationCtx) createTemplateContext` must be returning nil.

**Comment by sarabala1979** [comment]
yes, I am adding a fix to check nil for `cwftmplInformer`

**Comment by tachyus-ryan** [comment]
@sarabala1979 I want to run workflows in multiple namespaces with different resource limits applied to each namespace. The managed namespace option doesn't work because it only accepts one. When I tried to use a cluster install, I couldn't get any workflow templates, cluster or namespaced, to work. So I was trying to use multiple namespace installs with cluster workflow templates.

I didn't check RBAC. Thanks for the reminder. I'll try that.

**Comment by sarabala1979** [comment]
@dpadhiar Can you. work on this Issue?

**Comment by dpadhiar** [comment]
Yes, I will take it.
