### ISSUE TITLE
Java SDK - Streaming requests fail

### ISSUE THREAD

**Issue by paulaylingdev** [argoproj/argo-workflows#7278]
## Summary

What happened/what you expected to happen?

When using the Java SDK `v3.2.4` doing a streaming request such as `WorkflowService.WatchWorkflows` will never return successfully and always throws an exception. The expectation is the SDK can successfully return a result.

What version of Argo Workflows are you running?

`v3.2.4`

## Diagnostics

Either a workflow that reproduces the bug, or paste you whole workflow YAML, including status, something like:

1. Create a simple workflow that waits indefinitely.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: wait1
        template: wait

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]

  - name: wait
    suspend: {}
```

2. Submit the workflow on the UI

3. Create an application using the `WorkflowService.WatchWorkflows` [example](https://github.com/argoproj/argo-workflows/blob/master/sdks/java/client/docs/WorkflowServiceApi.md#workflowServiceWatchWorkflows).

4. Amend the example with the following:
```groovy
// Missing deserializers
Gson gson = defaultClient.getJSON().getGson().newBuilder().setLenient().registerTypeAdapter(DateTime.class, new JsonDeserializer<DateTime>() {
    @Override
    public DateTime deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context)
            throws JsonParseException {
        return new DateTime(json.getAsString());
    }
}).registerTypeAdapter(Instant.class, new JsonDeserializer<Instant>() {
    @Override
    public Instant deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return ZonedDateTime.parse(json.getAsJsonPrimitive().getAsString()).toInstant();
    }
}).create();

defaultClient.setJSON(defaultClient.getJSON().setGson(gson))

defaultClient.setDebugging(true)
String namespace = <your argo namespace> //my-namespace
String listOptionsFieldSelector = "metadata.name=<name of your workflow>" //steps-5bsdf
Boolean listOptionsWatch = true
Boolean listOptionsAllowWatchBookmarks = true
String listOptionsTimeoutSeconds = "5" //If set to null Exception thrown is a client side socket timeout
// Set every other parameter to null

// try request catch ...
```

5. Observe an exception thrown

```
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: <-- 200 https://argo-workflows.com/api/v1/workflow-events/my-namespace?listOptions.fieldSelector=metadata.name%3Dsteps-5bsdf&listOptions.watch=true&listOptions.allowWatchBookmarks=true&listOptions.timeoutSeconds=5 (46ms)
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: server: nginx/1.19.2
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: date: Thu, 25 Nov 2021 11:05:48 GMT
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: content-type: application/json
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: vary: Accept-Encoding
Nov 25, 2021 11:05:49 AM okhttp3.internal.platform.Platform log
INFO: grpc-metadata-content-type: application/grpc
Nov 25, 2021 11:05:54 AM okhttp3.internal.platform.Platform log
INFO: 
Nov 25, 2021 11:05:54 AM okhttp3.internal.platform.Platform log
INFO: {"result":{"type":"ADDED","object":{"metadata":{"name":"steps-5bsdf","generateName":"steps-","namespace":"my-namespace","selfLink":"/apis/argoproj.io/v1alpha1/namespaces/my-namespace/workflows/steps-5bsdf","uid":"944224ab-2591-45fc-b28f-1d66011441f6","resourceVersion":"274937724","generation":3,"creationTimestamp":"2021-11-25T11:04:10Z","labels":{"workflows.argoproj.io/creator":"system-serviceaccount-my-namespace-argo-workflows-server","workflows.argoproj.io/phase":"Running"},"managedFields":[{"manager":"argo","operation":"Update","apiVersion":"argoproj.io/v1alpha1","time":"2021-11-25T11:04:10Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:workflows.argoproj.io/creator":{}}},"f:spec":{".":{},"f:arguments":{},"f:entrypoint":{},"f:templates":{}},"f:status":{".":{},"f:finishedAt":{}}}},{"manager":"workflow-controller","operation":"Update","apiVersion":"argoproj.io/v1alpha1","time":"2021-11-25T11:04:20Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{"f:workflows.argoproj.io/phase":{}}},"f:status":{"f:artifactRepositoryRef":{},"f:conditions":{},"f:nodes":{},"f:phase":{},"f:progress":{},"f:startedAt":{}}}}]},"spec":{"templates":[{"name":"hello-hello-hello","inputs":{},"outputs":{},"metadata":{},"steps":[[{"name":"hello1","template":"whalesay","arguments":{"parameters":[{"name":"message","value":"hello1"}]}}],[{"name":"wait1","template":"wait","arguments":{}}]]},{"name":"whalesay","inputs":{"parameters":[{"name":"message"}]},"outputs":{},"metadata":{},"container":{"name":"","image":"docker/whalesay","command":["cowsay"],"args":["{{inputs.parameters.message}}"],"resources":{"limits":{"cpu":"50m","memory":"64Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}},{"name":"wait","inputs":{},"outputs":{},"metadata":{},"suspend":{}}],"entrypoint":"hello-hello-hello","arguments":{}},"status":{"phase":"Running","startedAt":"2021-11-25T11:04:10Z","finishedAt":null,"progress":"0/1","nodes":{"steps-5bsdf":{"id":"steps-5bsdf","name":"steps-5bsdf","displayName":"steps-5bsdf","type":"Steps","templateName":"hello-hello-hello","templateScope":"local/steps-5bsdf","phase":"Running","startedAt":"2021-11-25T11:04:10Z","finishedAt":null,"progress":"0/1","children":["steps-5bsdf-2996575271"]},"steps-5bsdf-288291960":{"id":"steps-5bsdf-288291960","name":"steps-5bsdf[0].hello1","displayName":"hello1","type":"Pod","templateName":"whalesay","templateScope":"local/steps-5bsdf","phase":"Running","boundaryID":"steps-5bsdf","startedAt":"2021-11-25T11:04:10Z","finishedAt":null,"progress":"0/1","inputs":{"parameters":[{"name":"message","value":"hello1"}]},"hostNodeName":"gke-standard2021031516343079160-2833fcfe-4giz"},"steps-5bsdf-2996575271":{"id":"steps-5bsdf-2996575271","name":"steps-5bsdf[0]","displayName":"[0]","type":"StepGroup","templateScope":"local/steps-5bsdf","phase":"Running","boundaryID":"steps-5bsdf","startedAt":"2021-11-25T11:04:10Z","finishedAt":null,"progress":"0/1","children":["steps-5bsdf-288291960"]}},"conditions":[{"type":"PodRunning","status":"True"}],"artifactRepositoryRef":{"default":true,"artifactRepository":{}}}}}}
{"error":{"grpc_code":2,"http_code":500,"message":"EOF","http_status":"Internal Server Error"}}
Nov 25, 2021 11:05:54 AM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (3210-byte body)
Exception in thread "main" com.google.gson.JsonIOException: JSON document was not fully consumed.
	at com.google.gson.Gson.assertFullConsumption(Gson.java:905)
	at com.google.gson.Gson.fromJson(Gson.java:898)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.argoproj.workflow.JSON.deserialize(JSON.java:146)
	at io.argoproj.workflow.ApiClient.deserialize(ApiClient.java:797)
	at io.argoproj.workflow.ApiClient.handleResponse(ApiClient.java:1003)
	at io.argoproj.workflow.ApiClient.execute(ApiClient.java:927)
	at io.argoproj.workflow.apis.WorkflowServiceApi.workflowServiceWatchWorkflowsWithHttpInfo(WorkflowServiceApi.java:2478)
	at io.argoproj.workflow.apis.WorkflowServiceApi.workflowServiceWatchWorkflows(WorkflowServiceApi.java:2448)
	at io.argoproj.workflow.apis.WorkflowServiceApi$workflowServiceWatchWorkflows$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
```

As can be seen in the logs above a result can be produced both the initial get from the watch and the following EOF message. However it always produces an exception because the return type `StreamResultOfIoArgoprojWorkflowV1alpha1WorkflowWatchEvent` has no concept of storing multiple JSON documents (hence the exception around document not fully consumed).

Ultimately I think the problem is the code is generated from the swagger docs and it does not represent the streaming nature of this HTTP call.

What Kubernetes provider are you using?

GKE

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

Docker

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

No logs produced

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

Workflow isn't problematic

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

Workflow isn't problematic
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
I think there might be two problems here:

* Your server return 500 error.
* Maybe SDK does not support steaming.

Could you please attach the argo-server logs detailing the 500 error so we can understand more?

**Comment by alexec** [comment]
I've finally gotten around to looking into this. The Java SDK is generated from OpenAPI specs. OpenAPI does not support server-send events (aka SSE). So this cannot be fixed.

**Comment by alexec** [comment]
This works:

https://adambien.blog/roller/abien/entry/receiving_server_sent_events_sses
