### ISSUE TITLE
v3.2.6: leadship election panics and crashes controller

### ISSUE THREAD

**Issue by qingfeng777** [argoproj/argo-workflows#7661]
## Summary

What happened/what you expected to happen?

workflow-controller panic and restart:

`
NAME                                  READY   STATUS    RESTARTS   AGE 

workflow-controller-f7b85c9cd-lmn49   1/1     Running   12         23d
`

What version of Argo Workflows are you running?
v3.2.6

## Diagnostics

What Kubernetes provider are you using?

Amazon EKS
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

What executor are you running? Docker/K8SAPI/Kubelet/PNS/Emissary

```bash
# Logs from the workflow controller:
kubectl logs -n argo deploy/workflow-controller | grep ${workflow}
`
time="2022-01-26T09:57:37.160Z" level=info msg="Patch events 200"
I0126 09:57:37.168364       1 leaderelection.go:278] failed to renew lease argo/workflow-controller: timed out waiting for the condition
time="2022-01-26T09:57:37.169Z" level=info msg="archiving workflow" namespace=default uid=997074f6-2042-4c72-a120-17b2f07edfcd workflow=a79be78e-0c48-4461-ab0c-1141af630cd9
time="2022-01-26T09:57:37.172Z" level=info msg="Create events 201"
time="2022-01-26T09:57:37.173Z" level=info msg="Patch events 200"
time="2022-01-26T09:57:37.174Z" level=error msg="failed to archive workflow" error="failed to archive workflow: pq: relation \"argo_archived_workflows\" does not exist" key=default/a79be78e-0c48-4461-ab0c-1141af630cd9
time="2022-01-26T09:57:37.175Z" level=info msg="Update leases 409"
E0126 09:57:37.175960       1 leaderelection.go:301] Failed to release lock: Operation cannot be fulfilled on leases.coordination.k8s.io "workflow-controller": the object has been modified; please apply your changes to the latest version and try again
time="2022-01-26T09:57:37.176Z" level=info msg="stopped leading" id=workflow-controller-f7b85c9cd-lmn49
time="2022-01-26T09:57:37.176Z" level=info msg="Shutting workflow TTL worker"
E0126 09:57:37.176293       1 runtime.go:78] Observed a panic: "close of closed channel" (close of closed channel)
goroutine 331 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1f226a0, 0x2488a50)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1f226a0, 0x2488a50)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).pop(0xc00323a780)
        /go/pkg/mod/k8s.io/client-go@v0.21.5/tools/cache/shared_informer.go:752 +0x2a5
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000179720, 0xc0111e8580)
        /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:71 +0x65
panic: http: Server closed

goroutine 217 [running]:
github.com/argoproj/argo-workflows/v3/workflow/metrics.runServer.func1(0x1, 0x21eabe1, 0x8, 0x2382, 0x0, 0x0, 0xc000e408c0)
        /go/src/github.com/argoproj/argo-workflows/workflow/metrics/server.go:56 +0x11d
created by github.com/argoproj/argo-workflows/v3/workflow/metrics.runServer
        /go/src/github.com/argoproj/argo-workflows/workflow/metrics/server.go:53 +0x27e
panic: close of closed channel [recovered]
        panic: close of closed channel

`


---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Controller crash maybe acceptable. Did controller start-up again and continue processing workflows?

**Comment by qingfeng777** [comment]
> Controller crash maybe acceptable. Did controller start-up again and continue processing workflows?

yes,it start-up and work again

**Comment by kenoshi** [comment]
Have been running into the same problem...sure it restarts but this can't be the solution...the server hangs when this happens
