### ISSUE TITLE
Failed to release SDKs for v3.3.0-rc1 release

### ISSUE THREAD

**Issue by terrytangyuan** [argoproj/argo-workflows#7692]
The SDK release workflow failed because Python SDK release build failed and then Java SDK release build got canceled. 
```
Run make --directory sdks/python publish -B
make: Entering directory '/home/runner/work/argo-workflows/argo-workflows/sdks/python'
Traceback (most recent call last):
  File "./sdk_version.py", line 35, in <module>
    raise e
  File "./sdk_version.py", line 28, in <module>
    version_digits = [int(i) for i in git_tag.replace(VERSION_PREFIX, '').split('.')]
  File "./sdk_version.py", line 28, in <listcomp>
    version_digits = [int(i) for i in git_tag.replace(VERSION_PREFIX, '').split('.')]
ValueError: invalid literal for int() with base 10: '0-rc1'
Makefile:3: *** "Failed to obtain a valid version for the SDK".  Stop.
```
I’ll look into the errors soon.

Build: https://github.com/argoproj/argo-workflows/runs/4987739996?check_suite_focus=true

**Comment by terrytangyuan** [comment]
This will be fixed in https://github.com/argoproj/argo-workflows/pull/7693. 

@sarabala1979 @alexec Could we re-trigger the SDK release workflow once it's merged?

**Comment by sarabala1979** [comment]
sure

**Comment by terrytangyuan** [comment]
Just checked that both SDKs have been released successfully.
