### ISSUE TITLE
oss-fuzz: artifacts.(*ArtifactServer).GetInputArtifactByUID panic

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#7717]
https://oss-fuzz.com/testcase-detail/5098631152140288

```
panic: runtime error: index out of range [2] with length 2
goroutine 17 [running, locked to thread]:
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).getArtifactByUID(0x10c0004a4780, {0x2b3f5c0, 0x10c0002d56a0}, 0x10c000559d00, 0x1)
 github.com/argoproj/argo-workflows/v3/server/artifacts/artifact_server.go:101 +0x5d2
github.com/argoproj/argo-workflows/v3/server/artifacts.(*ArtifactServer).GetInputArtifactByUID(...)
 github.com/argoproj/argo-workflows/v3/server/artifacts/artifact_server.go:95
github.com/argoproj/argo-workflows/v3/server/artifacts.FuzzGetOutputArtifactByUID({0x602000000090, 0x0, 0x1})
 github.com/argoproj/argo-workflows/v3/server/artifacts/artifacts_fuzzer.go:61 +0x35c
```

**Comment by alexec** [comment]
Easy fix, add let check here:

https://github.com/argoproj/argo-workflows/blob/877d6569754be94f032e1c48d1f7226a83adfbec/server/artifacts/artifact_server.go#L101

**Comment by pacoguzman** [comment]
Working on it!
