### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by frimuchkov** [argoproj/argo-workflows#7786]
Hi!

It's a pretty rare bug and I don't know how to reproduce it, but maybe it will be useful

```
runtime error: invalid memory address or nil pointer dereference" stack="goroutine 286 [running]:
runtime/debug.Stack(0xc0b3f9f015, 0x1f215c0, 0x3319940)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2(0xc001739500, 0x24f1cc8, 0xc000126000)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:188 +0xd1
panic(0x1f215c0, 0x3319940)
 /usr/local/go/src/runtime/panic.go:971 +0x499
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).processAggregateNodeOutputs(0xc001739500, 0xc01b25e3f0, 0xc00a4b0120, 0x26, 0xc00a88e000, 0x4b, 0x8b, 0x0, 0x0)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:2724 +0xc2b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeSteps(0xc001739500, 0x24f1cc8, 0xc000126000, 0xc00272ce80, 0x38, 0xc01b8e0a40, 0xc00a204640, 0x1d, 0xc009edcb40, 0x24db060, ...)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/steps.go:133 +0x12fb
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001739500, 0x24f1cc8, 0xc000126000, 0xc00272ce80, 0x38, 0x24db060, 0xc009e494a0, 0xc01b8e01c0, 0x0, 0x0, ...)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1828 +0x258e
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc001739500, 0x24f1cc8, 0xc000126000, 0xc00a1aa5b0, 0xc00a204440, 0x20)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:483 +0x90b
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc001739500, 0x24f1cc8, 0xc000126000, 0xc017656588, 0x17, 0xc01b8e01c0, 0xc00a204320, 0x1d, 0xc004bcad80, 0x24dc1d0, ...)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x309
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001739500, 0x24f1cc8, 0xc000126000, 0xc017656588, 0x17, 0x24dc1d0, 0xc004bd2000, 0xc01b8e0040, 0x0, 0x0, ...)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1834 +0x16bc
github.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc001739500, 0x24f1cc8, 0xc000126000)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:338 +0xede
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000600800, 0x24f1cc8, 0xc000126000, 0x0)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:770 +0x830
github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0xc000600800)
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:692 +0x9b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0000280b0)
 /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0000280b0, 0x24aa720, 0xc00adb8ff0, 0x534d696f6a497501, 0xc005107ec0)
 /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0000280b0, 0x3b9aca00, 0x0, 0x3258615a564f4801, 0xc005107ec0)
 /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0000280b0, 0x3b9aca00, 0xc005107ec0)
 /go/pkg/mod/k8s.io/apimachinery@v0.21.5/pkg/util/wait/wait.go:90 +0x4d
created by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).startLeading
 /go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:309 +0x48a
```

**Comment by frimuchkov** [comment]
> @frimuchkov can you provide the argo controller version? sample workflow

argoproj/workflow-controller:v3.2.4

```
      - args:
        - --namespaced
        - --configmap
        - argo-workflow-controller-configmap
        - --executor-image
        - argoproj/argoexec:v3.2.4
        - --container-runtime-executor
        - emissary
        - --loglevel
        - info
        - --gloglevel
        - "0"
        - --workflow-workers
        - "96"
        - --workflow-ttl-workers
        - "16"
        - --pod-workers
        - "64"
        - --burst
        - "60"
        - --qps
        - "40"
        command:
        - workflow-controller
```

Unfortunately, there are a lot of client's data in workflow :(
But looks like it doesn't depend on workflow

**Comment by sarabala1979** [comment]
Do you have any of skipped steps/tasks on your failed workflow?

**Comment by frimuchkov** [comment]
> Do you have any of skipped steps/tasks on your failed workflow?
Only this one, but it was retried
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/19934346/152938177-23346ca8-e60a-4af0-950e-8b1f7042eb4b.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/19934346/152938343-403df8b5-93b3-4c61-a03c-4607ba42ab9c.png">

Unfortunately, there are no artifacts for this pod
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/19934346/152938536-b5a184da-38fa-4ed6-a970-0bdfc667ffba.png">

**Comment by alexec** [comment]
Duplicates #7786. Closing.
