### ISSUE TITLE
Full CRDs are incomplete and causes json2jsii to fail

### ISSUE THREAD

**Issue by adrianord** [argoproj/argo-workflows#8532]
## Summary
The generated CustomResourceDefinitions seem to be incomplete because of the `steps` property.

https://github.com/argoproj/argo-workflows/blob/ecd91b1c4215a2ab8742f7c43eaade98a1d47eba/manifests/base/crds/full/argoproj.io_workflowtemplates.yaml#L7673-L7676

The `items` property has a `type` property but does not have an accompanying `items` property. 

 This causes `json2jsii` to fail. 
https://github.com/cdklabs/json2jsii/blob/60e891447e35a8bb1a9dac3496d6adce87d73292/src/type-generator.ts#L534-L540
This is an issue for tools that depend on `json2jsii`. https://github.com/cdk8s-team/cdk8s/issues/2157

However, the json schema has these missing properties.

https://github.com/argoproj/argo-workflows/blob/ecd91b1c4215a2ab8742f7c43eaade98a1d47eba/api/jsonschema/schema.json#L7315-L7321

https://github.com/argoproj/argo-workflows/blob/ecd91b1c4215a2ab8742f7c43eaade98a1d47eba/api/jsonschema/schema.json#L6449-L6454

It looks like this problem was fixed at one point with #4828, but was later reverted by @JPZ13 here #4810 because of the CRDs becoming too long. 

Is there way we can get the full CRDs for use with `json2jsii` as I do not believe it has any limit on CRD size like Kubernetes does. I'd like to have all the types for `steps` so that I can get strong typing with cdk8s.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
Would you like to submit a PR to fix this?

**Comment by adrianord** [comment]
I would need some guidance, I spent some time looking into the issue yesterday on a fork https://github.com/adrianord/argo-workflows, but I believe the fix I've done there causes the CRDs to be too large for Kubernetes, which is why it was reverted before.

**Comment by alexec** [comment]
Share you PR and maybe we can take a look at it.

**Comment by sstaley-hioscar** [comment]
Also getting an issue here with crds and json2jsii.
```
Error: unsupported array type undefined
                         at TypeGenerator.typeForArray (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:404:19)
                         at TypeGenerator.emitArray (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:260:25)
                         at TypeGenerator.emitTypeInternal (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:186:29)
                         at TypeGenerator.typeForProperty (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:383:21)
                         at TypeGenerator.typeForArray (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:406:21)
                         at TypeGenerator.emitArray (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:260:25)
                         at TypeGenerator.emitTypeInternal (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:186:29)
                         at TypeGenerator.typeForProperty (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:383:21)
                         at TypeGenerator.emitProperty (/snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:322:35)
                         at /snapshot/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:302:22
```

**Comment by MasonM** [comment]
Re-opening because having full CRDs would enable a lot of requested features, e.g. `kubectl explain` output (#8190) and validating admission policies (#13503)
