### ISSUE TITLE
'Copy To Clipboard' does not work

### ISSUE THREAD

**Issue by lxc902** [argoproj/argo-workflows#8652]
The console log says 
```
clipboard-text.tsx:22 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at onClick (clipboard-text.tsx:22:49)
    at Object.<anonymous> (react-dom.production.min.js:14:428)
    at p (react-dom.production.min.js:15:118)
    at react-dom.production.min.js:15:172
    at E (react-dom.production.min.js:17:210)
    at k (react-dom.production.min.js:18:248)
    at C (react-dom.production.min.js:18:57)
    at D (react-dom.production.min.js:21:69)
    at Mn (react-dom.production.min.js:84:409)
    at Ns (react-dom.production.min.js:250:397)
```

I guess it's because the code (https://github.com/argoproj/argo-workflows/blob/3abeb0120c80fcdf9b8b161178c296c6efccb63d/ui/src/app/shared/components/clipboard-text.tsx#L22) didn't call the Permissions API (ref: https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard/writeText )

![image](https://user-images.githubusercontent.com/4177403/167064832-0bb5289a-4eda-4f03-bd17-90e2f62dc859.png)

**Comment by alexec** [comment]
Do you have a fix?

**Comment by tczhao** [comment]
I think the Permissions API is not an issue, the English version of the document says `Permissions API, is granted automatically`, maybe the chinese document is outdated.

I think the following might be related
https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

Hi @lxc902 , were you running the argo server with `--secure=false`?
