### ISSUE TITLE
Cannot run `yarn start`

### ISSUE THREAD

**Issue by alexec** [argoproj/argo-workflows#8756]
```
         ui | /Users/acollins8/go/src/github.com/argoproj/argo-workflows/ui/node_modules/react-hot-loader/node_modules/source-map/lib/read-wasm.js:8
         ui |       throw new Error("You must provide the URL of lib/mappings.wasm by calling " +
         ui |             ^
         ui | Error: You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer
         ui |     at readWasm (/Users/acollins8/go/src/github.com/argoproj/argo-workflows/ui/node_modules/react-hot-loader/node_modules/source-map/lib/read-wasm.js:8:13)
         ui |     at wasm (/Users/acollins8/go/src/github.com/argoproj/argo-workflows/ui/node_modules/react-hot-loader/node_modules/source-map/lib/wasm.js:25:16)
         ui |     at /Users/acollins8/go/src/github.com/argoproj/argo-workflows/ui/node_modules/react-hot-loader/node_modules/source-map/lib/source-map-consumer.js:264:14
         ui | Node.js v18.0.0
         ui | error Command failed with exit code 1.
```

Fix is to add this somewhere:

```
export NODE_OPTIONS=--no-experimental-fetch
```

**Comment by juliev0** [comment]
I'm completely new to React so don't fully know what I'm doing here, but is this what you had in mind?
