### ISSUE TITLE
bug: GitHub Codespaces not building

### ISSUE THREAD

**Issue by venkatamutyala** [argoproj/argo-workflows#9094]
## Summary

What happened/what you expected to happen?

**The GitHub Codespaces image is not building for this repository. This impacts me and other future contributors who want to get a dev environment up and running quickly so that they can make a contribution.**

What version are you running?

**latest - [0b2fe2f](https://github.com/argoproj/argo-workflows/commit/0b2fe2face955f31941496c1a99c13e1b12909d9)**

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

**Open GitHub Codespaces against this repository and the build process will fail.**

Logs:
```
2022-07-02 03:10:29.301Z: Configuration starting...
2022-07-02 03:10:29.333Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch master --depth 1 https://github.com/argoproj/argo-workflows "/var/lib/docker/codespacemount/workspace/argo-workflows"
2022-07-02 03:10:29.351Z: Cloning into '/var/lib/docker/codespacemount/workspace/argo-workflows'...
2022-07-02 03:10:31.961Z: git process exited with exit code 0
2022-07-02 03:10:32.000Z: $ git -C "/var/lib/docker/codespacemount/workspace/argo-workflows" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2022-07-02 03:10:32.014Z: git process exited with exit code 0
2022-07-02 03:10:33.721Z: @microsoft/vscode-dev-containers-cli 0.63.0.
2022-07-02 03:10:33.746Z: Start: Resolving Remote
2022-07-02 03:10:33.760Z: $ docker ps -q -a --filter label=Type=codespaces
2022-07-02 03:10:33.772Z: Stop (53 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-07-02 03:10:33.784Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/argo-workflows --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-02 03:10:33.816Z: @microsoft/vscode-dev-containers-cli 0.63.0.
2022-07-02 03:10:33.829Z: $ docker buildx version
2022-07-02 03:10:33.841Z: Stop (124 ms): Run: docker buildx version
2022-07-02 03:10:33.854Z: Start: Resolving Remote
2022-07-02 03:10:33.867Z: $ docker ps -q -a --filter label=Type=codespaces
2022-07-02 03:10:33.879Z: Stop (41 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-07-02 03:10:33.892Z: $ docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/Dockerfile -t vsc-argo-workflows-32f8de76b4e8ed5ac8fa6a91f4586150 --build-arg VARIANT=bullseye --build-arg NEW_USERNAME= --build-arg HOME= --build-arg VSCODE_SCRIPT_VERSION=v0.234.0 /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer
2022-07-02 03:10:34.661Z: #1 [internal] load .dockerignore
2022-07-02 03:10:34.694Z: #1 ...
2022-07-02 03:10:34.709Z: 
2022-07-02 03:10:34.735Z: #2 [internal] load build definition from Dockerfile
2022-07-02 03:10:34.768Z: #2 transferring dockerfile: 2.59kB done
2022-07-02 03:10:34.791Z: #2 DONE 0.4s
2022-07-02 03:10:34.802Z: 
2022-07-02 03:10:34.815Z: #1 [internal] load .dockerignore
2022-07-02 03:10:34.827Z: #1 transferring context: 2B done
2022-07-02 03:10:34.840Z: #1 DONE 0.5s
2022-07-02 03:10:34.865Z: 
2022-07-02 03:10:34.889Z: #3 [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/base:0-bullseye
2022-07-02 03:10:35.407Z: #3 DONE 0.9s
2022-07-02 03:10:35.423Z: 
2022-07-02 03:10:35.442Z: #4 [1/2] FROM mcr.microsoft.com/vscode/devcontainers/base:0-bullseye@sha256:269cbbb2056243e2a88e21501d9a8166d1825d42abf6b67846b49b1856f4b133
2022-07-02 03:10:35.487Z: #4 resolve mcr.microsoft.com/vscode/devcontainers/base:0-bullseye@sha256:269cbbb2056243e2a88e21501d9a8166d1825d42abf6b67846b49b1856f4b133 0.0s done
2022-07-02 03:10:35.509Z: 
2022-07-02 03:10:41.323Z: #4 ...
2022-07-02 03:10:41.345Z: 
2022-07-02 03:10:41.361Z: #5 [2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y apt-transport-https ca-certificates git sudo     && usermod -l  -d /home/ -m vscode     && groupmod -n  vscode     && echo  ALL=(root) NOPASSWD:ALL > /etc/sudoers.d/     && chmod 0440 /etc/sudoers.d/     && curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg     && echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list     && apt-get update     && apt-get install -y kubectl     && curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip     && unzip -o protoc-3.14.0-linux-x86_64.zip -d /usr/local bin/protoc     && unzip -o protoc-3.14.0-linux-x86_64.zip -d /usr/local 'include/*'     && rm -f protoc-3.14.0-linux-x86_64.zip     && chmod 755 /usr/local/bin/protoc     && chmod -R 755 /usr/local/include/     && wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/go-debian.sh")" -- "1.18" "/usr/local/go" "/go" "automatic" "true" "false"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/docker-in-docker-debian.sh")" -- "true" "automatic" "true" "20.10" "v1"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/node-debian.sh")" -- "/usr/local/share/nvm" "16" "automatic" "true" "true"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/python-debian.sh")" -- "3.9"     && apt-get clean -y && rm -rf /var/lib/apt/lists/*
2022-07-02 03:10:41.382Z: 
2022-07-02 03:10:41.407Z: #0 1.546 Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
2022-07-02 03:10:41.425Z: 
2022-07-02 03:10:41.450Z: #0 1.733 Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
2022-07-02 03:10:41.473Z: #0 1.749 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
2022-07-02 03:10:41.498Z: #0 1.927 Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [161 kB]
2022-07-02 03:10:41.516Z: #0 2.050 Get:5 http://deb.debian.org/debian bullseye/contrib amd64 Packages [50.5 kB]
2022-07-02 03:10:41.534Z: #0 2.057 Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8182 kB]
2022-07-02 03:10:41.568Z: #0 2.304 Get:7 http://deb.debian.org/debian bullseye/non-free amd64 Packages [93.8 kB]
2022-07-02 03:10:41.605Z: #0 2.319 Get:8 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2592 B]
2022-07-02 03:10:41.628Z: #0 3.384 Fetched 8690 kB in 2s (4537 kB/s)
2022-07-02 03:10:41.657Z: #0 3.384 Reading package lists...
2022-07-02 03:10:41.677Z: #0 3.940 Reading package lists...
2022-07-02 03:10:41.696Z: #0 4.466 Building dependency tree...
2022-07-02 03:10:41.714Z: #0 4.609 Reading state information...
2022-07-02 03:10:41.733Z: #0 4.776 apt-transport-https is already the newest version (2.2.4).
2022-07-02 03:10:41.752Z: #0 4.776 ca-certificates is already the newest version (20210119).
2022-07-02 03:10:41.769Z: #0 4.776 git is already the newest version (1:2.30.2-1).
2022-07-02 03:10:41.785Z: #0 4.776 sudo is already the newest version (1.9.5p2-3).
2022-07-02 03:10:41.803Z: #0 4.776 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2022-07-02 03:10:41.819Z: #0 4.797 usermod: invalid user name '-d'
2022-07-02 03:10:41.832Z: #5 ERROR: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y apt-transport-https ca-certificates git sudo     && usermod -l $NEW_USERNAME -d /home/$NEW_USERNAME -m $OLD_USERNAME     && groupmod -n $NEW_USERNAME $OLD_USERNAME     && echo $NEW_USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$NEW_USERNAME     && chmod 0440 /etc/sudoers.d/$NEW_USERNAME     && curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg     && echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list     && apt-get update     && apt-get install -y kubectl     && curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/${PROTOC_ZIP}     && unzip -o ${PROTOC_ZIP} -d /usr/local bin/protoc     && unzip -o ${PROTOC_ZIP} -d /usr/local 'include/*'     && rm -f ${PROTOC_ZIP}     && chmod 755 /usr/local/bin/protoc     && chmod -R 755 /usr/local/include/     && wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/go-debian.sh")" -- "1.18" "/usr/local/go" "$HOME/go" "automatic" "true" "false"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/docker-in-docker-debian.sh")" -- "true" "automatic" "true" "20.10" "v1"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/node-debian.sh")" -- "/usr/local/share/nvm" "16" "automatic" "true" "true"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/python-debian.sh")" -- "3.9"     && apt-get clean -y && rm -rf /var/lib/apt/lists/*]: exit code: 3
2022-07-02 03:10:41.846Z: 
2022-07-02 03:10:41.864Z: #4 [1/2] FROM mcr.microsoft.com/vscode/devcontainers/base:0-bullseye@sha256:269cbbb2056243e2a88e21501d9a8166d1825d42abf6b67846b49b1856f4b133
2022-07-02 03:10:41.879Z: ------
2022-07-02 03:10:41.893Z:  > [2/2] RUN apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y apt-transport-https ca-certificates git sudo     && usermod -l  -d /home/ -m vscode     && groupmod -n  vscode     && echo  ALL=(root) NOPASSWD:ALL > /etc/sudoers.d/     && chmod 0440 /etc/sudoers.d/     && curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg     && echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list     && apt-get update     && apt-get install -y kubectl     && curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/protoc-3.14.0-linux-x86_64.zip     && unzip -o protoc-3.14.0-linux-x86_64.zip -d /usr/local bin/protoc     && unzip -o protoc-3.14.0-linux-x86_64.zip -d /usr/local 'include/*'     && rm -f protoc-3.14.0-linux-x86_64.zip     && chmod 755 /usr/local/bin/protoc     && chmod -R 755 /usr/local/include/     && wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/go-debian.sh")" -- "1.18" "/usr/local/go" "/go" "automatic" "true" "false"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/docker-in-docker-debian.sh")" -- "true" "automatic" "true" "20.10" "v1"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/node-debian.sh")" -- "/usr/local/share/nvm" "16" "automatic" "true" "true"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/v0.234.0/script-library/python-debian.sh")" -- "3.9"     && apt-get clean -y && rm -rf /var/lib/apt/lists/*:
2022-07-02 03:10:41.907Z: #0 3.384 Reading package lists...
2022-07-02 03:10:41.920Z: #0 3.940 Reading package lists...
2022-07-02 03:10:41.934Z: #0 4.466 Building dependency tree...
2022-07-02 03:10:41.946Z: #0 4.609 Reading state information...
2022-07-02 03:10:41.960Z: #0 4.776 apt-transport-https is already the newest version (2.2.4).
2022-07-02 03:10:41.976Z: #0 4.776 ca-certificates is already the newest version (20210119).
2022-07-02 03:10:41.989Z: #0 4.776 git is already the newest version (1:2.30.2-1).
2022-07-02 03:10:42.002Z: #0 4.776 sudo is already the newest version (1.9.5p2-3).
2022-07-02 03:10:42.017Z: #0 4.776 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2022-07-02 03:10:42.030Z: #0 4.797 usermod: invalid user name '-d'
2022-07-02 03:10:42.043Z: ------
2022-07-02 03:10:42.056Z: error: failed to solve: executor failed running [/bin/sh -c apt-get update && export DEBIAN_FRONTEND=noninteractive     && apt-get install -y apt-transport-https ca-certificates git sudo     && usermod -l $NEW_USERNAME -d /home/$NEW_USERNAME -m $OLD_USERNAME     && groupmod -n $NEW_USERNAME $OLD_USERNAME     && echo $NEW_USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$NEW_USERNAME     && chmod 0440 /etc/sudoers.d/$NEW_USERNAME     && curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg     && echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list     && apt-get update     && apt-get install -y kubectl     && curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/${PROTOC_ZIP}     && unzip -o ${PROTOC_ZIP} -d /usr/local bin/protoc     && unzip -o ${PROTOC_ZIP} -d /usr/local 'include/*'     && rm -f ${PROTOC_ZIP}     && chmod 755 /usr/local/bin/protoc     && chmod -R 755 /usr/local/include/     && wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/go-debian.sh")" -- "1.18" "/usr/local/go" "$HOME/go" "automatic" "true" "false"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscod
2022-07-02 03:10:42.069Z: e-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/docker-in-docker-debian.sh")" -- "true" "automatic" "true" "20.10" "v1"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/node-debian.sh")" -- "/usr/local/share/nvm" "16" "automatic" "true" "true"     && bash -ec "$(curl -fsSL "https://raw.githubusercontent.com/microsoft/vscode-dev-containers/$VSCODE_SCRIPT_VERSION/script-library/python-debian.sh")" -- "3.9"     && apt-get clean -y && rm -rf /var/lib/apt/lists/*]: exit code: 3
2022-07-02 03:10:42.082Z: Stop (7801 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/Dockerfile -t vsc-argo-workflows-32f8de76b4e8ed5ac8fa6a91f4586150 --build-arg VARIANT=bullseye --build-arg NEW_USERNAME= --build-arg HOME= --build-arg VSCODE_SCRIPT_VERSION=v0.234.0 /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer
2022-07-02 03:10:42.095Z: Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/Dockerfile -t vsc-argo-workflows-32f8de76b4e8ed5ac8fa6a91f4586150 --build-arg VARIANT=bullseye --build-arg NEW_USERNAME= --build-arg HOME= --build-arg VSCODE_SCRIPT_VERSION=v0.234.0 /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer
2022-07-02 03:10:42.109Z:     at jR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:240:1143)
2022-07-02 03:10:42.127Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-07-02 03:10:42.144Z:     at async Uu (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:2142)
2022-07-02 03:10:42.156Z:     at async Jy (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:239:1168)
2022-07-02 03:10:42.169Z:     at async zR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:2006)
2022-07-02 03:10:42.182Z:     at async nb (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:3110)
2022-07-02 03:10:42.194Z:     at async JR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:13046)
2022-07-02 03:10:42.206Z:     at async KR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:12802)
2022-07-02 03:10:42.218Z: Stop (8089 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/argo-workflows --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-02 03:10:42.234Z: Exit code 1
2022-07-02 03:10:42.247Z: Failed to create container.
2022-07-02 03:10:42.288Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/argo-workflows --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/argo-workflows/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-02 03:10:42.306Z: Error Code: 1302
2022-07-02 03:10:42.324Z: Container creation failed.
2022-07-02 03:10:42.341Z: 
2022-07-02 03:10:42.367Z: Creating recovery container.


```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by venkatamutyala** [comment]
@tczhao i noticed you committed the original files [here](https://github.com/argoproj/argo-workflows/tree/master/.devcontainer). Would you be OK with me committing a PR to fix those files so that they work with GitHub codespaces?

**Comment by tczhao** [comment]
Of course, you are very welcome.
Please go ahead and make a PR
