### ISSUE TITLE
list_workflows: `argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'finished_at'`

### ISSUE THREAD

**Issue by abhilasharevur** [argoproj/argo-workflows#9122]
## Checklist

 

* [x] Double-checked my configuration.
* [ ] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?
listing workflows using Python sdk example in the document returns this error:
```
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'finished_at'. Required value type is datetime and passed type was NoneType at ['received_data']['items'][0]['status']['finished_at']
```

What version are you running?
argo==3.3.7
argo-workflows==6.3.0rc2

## Diagnostics
1. create, delete workflows work fine
2. list workflow has issue
```python
from pprint import pprint
import requests
import argo_workflows
from argo_workflows.api import workflow_service_api

configuration = argo_workflows.Configuration(host="https://127.0.0.1:2746")
configuration.verify_ssl = False
with argo_workflows.ApiClient(configuration) as api_client:
    api_instance = workflow_service_api.WorkflowServiceApi(api_client)
    namespace = "dev" 
    try:
        api_response = api_instance.list_workflows(namespace)
        pprint(api_response)
    except argo_workflows.ApiException as e:
        print("Exception when calling WorkflowServiceApi->list_workflows: %s\n" % e)
```

```bash
# Logs from the workflow controller:
Traceback (most recent call last):
  File "./python_sdk_example.py", line 122, in <module>
    api_response = api_instance.list_workflows(namespace)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api_client.py", line 771, in __call__
    return self.callable(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api/workflow_service_api.py", line 682, in __list_workflows
    return self.call_with_http_info(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api_client.py", line 833, in call_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api_client.py", line 408, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api_client.py", line 223, in __call_api
    return_data = self.deserialize(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/api_client.py", line 324, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1540, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1436, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1427, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1347, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 343, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model/io_argoproj_workflow_v1alpha1_workflow_list.py", line 184, in _from_openapi_data
    self.items = items
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 183, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 483, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 155, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1590, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1540, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1436, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1427, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1347, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 343, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model/io_argoproj_workflow_v1alpha1_workflow.py", line 198, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 183, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 483, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 155, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1540, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1436, in attempt_convert_item
    raise conversion_exc
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1427, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1347, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 343, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 44, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model/io_argoproj_workflow_v1alpha1_workflow_status.py", line 240, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 183, in __setattr__
    self[attr] = value
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 483, in __setitem__
    self.set_attribute(name, value)
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 155, in set_attribute
    value = validate_and_convert_types(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1540, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/usr/local/lib/python3.8/dist-packages/argo_workflows/model_utils.py", line 1422, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
argo_workflows.exceptions.ApiTypeError: Invalid type for variable 'finished_at'. Required value type is datetime and passed type was NoneType at ['received_data']['items'][0]['status']['finished_at']
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by abhilasharevur** [comment]
There was only one workflow and it was still running when I executed "list_workflow".
So the value for the variable 'finished_at' is null.

**Comment by larsschwegmann** [comment]
`_check_return_type=False` seems more like a workaround rather than a fix for the problem. Any plans on fixing this?

**Comment by EEvacheNN** [comment]
This problem is really important when I was trying to use this whole argo python client, please see this comment and consider make this function more friendly, please

**Comment by agilgur5** [comment]
The SDKs are autogenerated via OpenAPI. The OpenAPI spec should allow unset `finished_at`; if it doesn't, that is a fixable bug.

If the SDK generation tools have a bug though, that is not necessarily fixable within Argo code.

As of right now, [Hera](https://github.com/argoproj-labs/hera) is recommended as a Python SDK.

**Comment by ahaessly** [comment]
This behavior also happens when submitting a workflow (in my case it's a workflow template) via the python client. The response to the submit contains a status where both the started_at and finished_at are NoneType and an exception is raised  because it tries to convert it to a datetime. I also don't want to have to set _check_return_type to false. Since both of these values are optional I would think they could just be omitted from the response if there is not value for them. Let me know if there is another way I can vote for this issue.

**Comment by dnlbauer** [comment]
I was able to fix this for me simply by adopting the openapi spec to allow finishedAt to be null. No PR since for some reason I wasnt able to get `make pre-commit -B` running, but if you are interested, there is a branch for this in my fork.

**Comment by Joibel** [comment]
> I was able to fix this for me simply by adopting the openapi spec to allow finishedAt to be null. No PR since for some reason I wasnt able to get `make pre-commit -B` running, but if you are interested, there is a branch for this in my fork.

Your [fork](https://github.com/dnlbauer/argo-workflows/commit/3a18c44ea966b3e1774aaccdc5ca7958196726ca) only seems to modify generated files, so if you had successfully gotten `make pre-commit` to run it would have wiped out your changes.

If you can work out/tell me how to do this to the non-generated file to generate that I'm happy to assist with creating a PR.

**Comment by Joibel** [comment]
Closing as obsolete: the generated Python SDK this issue is about was deprecated in v3.6 and removed from the repository in v4.0 (#14995). The recommended Python client is now [Hera](https://github.com/argoproj-labs/hera), which does not have this deserialization problem. For anyone still on the old `argo-workflows` PyPI package, the workaround in this thread (`_check_return_type=False`) remains the answer.
