### ISSUE TITLE
Can't use `/` in mutex name

### ISSUE THREAD

**Issue by jsvk** [argoproj/argo-workflows#9394]
## Checklist

 

* [x] Double-checked my configuration.
* [x] Tested using the latest version.
* [x] Used the Emissary executor.

## Summary

What happened/what you expected to happen?

I tried to use a mutex with a `/` character in the name. This results in this (truncated):

```
time="2022-08-11T22:37:58.642Z" level=error msg="Recovered from panic" namespace=provisioner r="bug: lock that was just encoded does not match encoding" stack="goroutine 397 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24
```

The Workflow never starts.

What version are you running?

Argo Workflows 3.3.8

## Diagnostics

Paste the smallest workflow that reproduces the bug. We must be able to run the workflow.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
 name: dag-mutex
 namespace: default
spec:
 entrypoint: diamond
 templates:
 - name: diamond
   dag:
     tasks:
     - name: A
       template: mutex
       arguments:
         parameters:
         - name: message
           value: foo/bar
     - name: B
       depends: A
       template: mutex
       arguments:
         parameters:
         - name: message
           value: foo/bar
 - name: mutex
   synchronization:
     mutex:
       name: a/b
   inputs:
     parameters:
     - name: message
   container:
     image: alpine:3.7
     command: [sh, -c, "echo {{inputs.parameters.message}}"]
```

I've also PRed a proposed fix: https://github.com/argoproj/argo-workflows/pull/9404

```
# Logs from the workflow controller:
$ kubectl logs -n argo deploy/workflow-controller | grep dag-mutex-2
Defaulted container "workflow-controller" out of: workflow-controller, fluent-bit
time="2022-08-19T05:27:04.956Z" level=info msg="default/Mutex/foo-bar acquired by default/dag-mutex/dag-mutex-2434353580 " mutex=default/Mutex/foo-bar
time="2022-08-19T05:27:04.956Z" level=info msg="Pod node dag-mutex-2434353580 initialized Pending" namespace=default workflow=dag-mutex
time="2022-08-19T05:27:05.089Z" level=info msg="Created pod: dag-mutex.A (dag-mutex-2434353580)" namespace=default workflow=dag-mutex
time="2022-08-19T05:27:15.089Z" level=info msg="node changed" new.message= new.phase=Succeeded new.progress=0/1 nodeID=dag-mutex-2434353580 old.message= old.phase=Pending old.progress=0/1
time="2022-08-19T05:27:15.091Z" level=info msg="Lock has been released by default/dag-mutex/dag-mutex-2434353580. Available locks: 1" mutex=default/Mutex/foo-bar
time="2022-08-19T05:27:15.091Z" level=info msg="default/dag-mutex/dag-mutex-2434353580 released a lock from default/Mutex/foo-bar"
time="2022-08-19T05:27:15.102Z" level=info msg="default/dag-mutex/dag-mutex-2434353580 released a lock from default/Mutex/foo-bar"
time="2022-08-19T05:27:15.114Z" level=info msg="cleaning up pod" action=labelPodCompleted key=default/dag-mutex-2434353580/labelPodCompleted
time="2022-08-19T05:28:20.661Z" level=info msg="Processing workflow" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.666Z" level=info msg="Updated phase  -> Running" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.666Z" level=info msg="DAG node dag-mutex-2 initialized Running" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.666Z" level=info msg="All of node dag-mutex-2.A dependencies [] completed" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.667Z" level=error msg="Recovered from panic" namespace=default r="bug: lock that was just encoded does not match encoding" stack="goroutine 387 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate.func2()\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:194 +0xd4\npanic({0x1bf9440, 0x225c110})\n\t/usr/local/go/src/runtime/panic.go:1047 +0x266\ngithub.com/argoproj/argo-workflows/v3/workflow/sync.(*LockName).ValidateEncoding(0xc13c89c140, {0xc0286fe528, 0x11})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/sync/lock_name.go:101 +0x14b\ngithub.com/argoproj/argo-workflows/v3/workflow/sync.(*LockName).EncodeName(0xc13c89c140)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/sync/lock_name.go:74 +0x10d\ngithub.com/argoproj/argo-workflows/v3/workflow/sync.(*Manager).TryAcquire(0xc000998420, 0xc0114fa480, {0xc0286fe510, 0x16}, 0xc1183682d0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/sync/sync_manager.go:130 +0x1f3\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000150480, {0x22b0668, 0xc000056030}, {0xc01c0de460, 0xd}, {0x22910d0, 0xc0007934a0}, 0x0, {{0xc001325080, 0x1, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1780 +0x1245\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000150480, {0x22b0668, 0xc000056030}, 0xc003c013b0, {0x331d148, 0x1})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:513 +0x1888\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAGTask(0xc000150480, {0x22b0668, 0xc000056030}, 0xc003c013b0, {0x331d150, 0x1})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:438 +0x1f25\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeDAG(0xc000150480, {0x22b0668, 0xc000056030}, {0xc00dd54f00, 0x0}, 0xc14b46fbc0, {0xc0286fe3c0, 0x11}, 0xc0c8adb8c0, {0x2292360, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/dag.go:244 +0x433\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).executeTemplate(0xc000150480, {0x22b0668, 0xc000056030}, {0xc00dd54f00, 0xb}, {0x2292360, 0xc001312000}, 0xc001513aa0, {{0x0, 0x0, ...}, ...}, ...)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:1889 +0x232c\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*wfOperationCtx).operate(0xc000150480, {0x22b0668, 0xc000056030})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/operator.go:350 +0x16a8\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).processNextItem(0xc000580c00, {0x22b0668, 0xc000056030})\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:756 +0x8ee\ngithub.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).runWorker(0x0)\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:678 +0x9e\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f4ac431c120)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x226dbe0, 0xc00153c000}, 0x1, 0xc00015e060)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6\nk8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00063afb0, 0x3b9aca00, 0x0, 0x0, 0x175f4a0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89\nk8s.io/apimachinery/pkg/util/wait.Until(0x915baa, 0xa0046c201, 0xc00063afa0)\n\t/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25\ncreated by github.com/argoproj/argo-workflows/v3/workflow/controller.(*WorkflowController).Run\n\t/go/src/github.com/argoproj/argo-workflows/workflow/controller/controller.go:294 +0x1a6c\n" workflow=dag-mutex-2
time="2022-08-19T05:28:20.667Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.667Z" level=info msg="Updated message  -> bug: lock that was just encoded does not match encoding" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.667Z" level=info msg="Marking workflow completed" namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.667Z" level=info msg="Checking daemoned children of " namespace=default workflow=dag-mutex-2
time="2022-08-19T05:28:20.672Z" level=info msg="cleaning up pod" action=deletePod key=default/dag-mutex-2-1340600742-agent/deletePod
time="2022-08-19T05:28:20.676Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=756130584 workflow=dag-mutex-2
time="2022-08-19T05:28:20.676Z" level=info msg="Queueing Error workflow default/dag-mutex-2 for delete in 120h0m0s due to TTL"
time="2022-08-19T05:39:30.206Z" level=info msg="Queueing Error workflow default/dag-mutex-2 for delete in 119h48m50s due to TTL"
time="2022-08-19T05:59:25.494Z" level=info msg="Queueing Error workflow default/dag-mutex-2 for delete in 119h28m55s due to TTL"
```
(rest of diagnostics skipped because pods were not created)
```
# If the workflow's pods have not been created, you can skip the rest of the diagnostics.

# The workflow's pods that are problematic:
kubectl get pod -o yaml -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

# Logs from in your workflow's wait container, something like:
kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by sarabala1979** [comment]
This is not a bug. this was by design. I saw your PR for enhancing. Thanks for contributing

**Comment by jsvk** [comment]
gottcha, apologies for the incorrect labeling!
