### ISSUE TITLE
clicking artifact in archived workflows throws error

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-workflows#9627]
### Pre-requisites

- [X] I have double-checked my configuration
- [X] I can confirm the issues exists when I tested with `:latest`
- [ ] I'd like to contribute the fix myself (see [contributing guide](https://github.com/argoproj/argo-workflows/blob/master/docs/CONTRIBUTING.md))

### What happened/what you expected to happen?

follow these 2 screenshots:

![image](https://user-images.githubusercontent.com/33283496/191158314-d0c0fbad-5b85-4894-b5ea-46428b6da124.png)

![image](https://user-images.githubusercontent.com/33283496/191158330-4707816d-cfd7-43a9-9c50-3782dc33052b.png)

```
TypeError: Cannot read properties of undefined (reading 'type')
    at t.WorkflowNodeInfo (https://myhostredact/main.c845e3bb2516691ba6db.js:230:50834)
    at Gi (https://myhostredact/main.c845e3bb2516691ba6db.js:261:57931)
    at gs (https://myhostredact/main.c845e3bb2516691ba6db.js:261:104170)
    at ul (https://myhostredact/main.c845e3bb2516691ba6db.js:261:96718)
    at sl (https://myhostredact/main.c845e3bb2516691ba6db.js:261:96643)
    at Xs (https://myhostredact/main.c845e3bb2516691ba6db.js:261:93673)
    at https://myhostredact/main.c845e3bb2516691ba6db.js:261:45315
    at t.unstable_runWithPriority (https://myhostredact/main.c845e3bb2516691ba6db.js:269:3844)
    at Vo (https://myhostredact/main.c845e3bb2516691ba6db.js:261:45024)
    at Ko (https://myhostredact/main.c845e3bb2516691ba6db.js:261:45260)
	
	
	
DevTools failed to load source map: Could not parse content for https://myhostredact/archived-workflows/ReactToastify.css.map: Unexpected token '<', "<!doctype "... is not valid JSON

DevTools failed to load source map: Could not parse content for https://myhostredact/archived-workflows/swagger-ui.css.map: Unexpected token '<', "<!doctype "... is not valid JSON

react-dom.production.min.js:209 TypeError: Cannot read properties of undefined (reading 'type')
    at t.WorkflowNodeInfo (workflow-node-info.tsx:471:28)
    at Gi (react-dom.production.min.js:153:146)
    at gs (react-dom.production.min.js:261:496)
    at ul (react-dom.production.min.js:246:265)
    at sl (react-dom.production.min.js:246:194)
    at Xs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
    at Ko (react-dom.production.min.js:123:61)
```

### Version

3.4.0

### Paste a small workflow that reproduces the issue. We must be able to run the workflow; don't enter a workflows that uses private images.

```YAML
n/a
```

### Logs from the workflow controller

kubectl logs -n argo deploy/workflow-controller | grep ${workflow}

### Logs from in your workflow's wait container

kubectl logs -c wait -l workflows.argoproj.io/workflow=${workflow},workflow.argoproj.io/phase!=Succeeded

**Comment by rajaie-sg** [comment]
@tooptoop4 would you happen to have a `retryStrategy` defined for your workflow? I am running into a similar error that only shows up when I have `retryStrategy` set.

**Comment by tooptoop4** [comment]
@rajaie-sg yes applied on all wf

**Comment by sarabala1979** [comment]
@rajaie-sg can you try on v3.3.9?

**Comment by tooptoop4** [comment]
@sarabala1979 these icons are new feature only in 3.4

**Comment by terrytangyuan** [comment]
Might be that we need a `.?` when accessing `WorkflowNodeInfo` in the UI. Anyone want to look into this?

**Comment by juliev0** [comment]
I don't think artifact visualization ever got incorporated into archived workflows. You can see [this](https://github.com/argoproj/argo-workflows/commit/c781a582821c4e08416eba9a3889eb2588596aa6#diff-0670537605e4212d6dada675c6498eabe38d45eb0d3594d59c0779905a83f18b) change was the first change which incorporated artifact visualization. In ui/src/app/workflows/components/workflow-details you can see the new artifact-panel.tsx, which is referenced in workflow-details.tsx. However, none of that got incorporated into ui/src/app/archived-workflows/components/archived-workflow-details/archived-workflow-details.tsx and probably should be.

**Comment by tooptoop4** [comment]
crispy
